---

- name: Set up for spawn
  hosts: instances
  connection: local
  vars_files:
    - clouds.yaml
  tasks:
    - name: Randomly select cloud for spawn
      set_fact:
        cloud_id: "{{ clouds.keys() | random }}"
        volume_name: "{{ inventory_hostname }}"
      delegate_to: localhost

- name: Spawn instance(s)
  hosts: instances
  connection: local
  environment:
     OS_CLOUD: "{{ cloud_id }}"
     OS_IDENTITY_API_VERSION: '3'
  tasks:
    - name: Collect docker volume snapshot id
      command: "openstack volume snapshot list -f value -c ID --volume {{ docker_snapshot_name }}"
      register: docker_snapshot_id_out
      delegate_to: localhost
    - name: Set volume snapshot id fact
      set_fact:
        volume_snapshot_id: "{{ docker_snapshot_id_out.stdout }}"
    - name: Create volume
      os_volume:
        cloud: "{{ cloud_id }}"
        size: "{{ volume_size }}"
        display_name: "{{ volume_name }}"
        snapshot_id: "{{ volume_snapshot_id | default(omit) }}"
      when: volume_name is defined
      delegate_to: localhost
    - name: Spawn new instance
      os_server:
        cloud: "{{ cloud_id }}"
        name: "{{ inventory_hostname }}"
        image: "{{ image }}"
        flavor: "{{ flavor }}"
        key_name: "{{ key_name }}"
        nics: "{{ nics }}"
        security_groups: "{{ security_groups }}"
        volumes: "{{ volume_name | default(omit) }}"
        auto_ip: "{{ auto_ip }}"
        userdata: |
          #cloud-config
          package_upgrade: false
      delegate_to: localhost
      register: spawned_out
    - name: Update inventory with spawned instance IP
      set_fact:
        ansible_host: "{{ spawned_out.server.private_v4 }}"
        ansible_ssh_common_args: "-F {{ inventory_dir }}/ssh_config.{{ spawned_out.server.cloud }}"
        cloud_id: "{{ spawned_out.server.cloud }}"
        volume_dev: "{{ spawned_out.server.volumes[0].device }}"
        floating_ip: "{{ spawned_out.server.public_v4 }}"
      delegate_to: localhost
    - name: Update inventory
      ini_file:
        dest: inventory
        section: instances
        option: "{{ inventory_hostname }} ansible_user"
        value: "centos ansible_host={{ ansible_host }} cloud_id={{ cloud_id }}"
        no_extra_spaces: yes
      delegate_to: localhost
    - name: Spin waiting for instance to become accessible
      command: >
        ssh -o BatchMode=yes -o UserKnownHostsFile=/dev/null
        -o StrictHostKeyChecking=no -o ConnectTimeout=10
        {{ ansible_ssh_common_args }}
        {{ ansible_user }}@{{ ansible_host }} /bin/true
      register: alive
      until: alive | success
      retries: 45  # if it's not up in 1.5 minutes, give up
      delay: 2
      delegate_to: localhost

- name: Configure worker(s)
  hosts: instances
  become: yes
  tasks:
    - name: Ensure node hostname is correctly set
      hostname:
        name: "{{ inventory_hostname }}"
    - name: Restart docker service to ensure correct node hostname
      service:
        name: docker
        state: restarted
    - name: Acquire worker join token
      command: docker swarm join-token -q worker
      delegate_to: "{{ groups[cloud_id][0] }}"
      register: worker_join_token_out
    - name: Join docker swarm
      command: "docker swarm join --advertise-addr {{ floating_ip }} --token {{ worker_join_token_out.stdout }} {{ docker_swarm_manager }}"
