# see run_tests.sh for a version that can be run locally
language: python
python: 3.6
script:
  - rm ${TRAVIS_BUILD_DIR}/ansible.cfg
  - virtualenv ${TRAVIS_BUILD_DIR}/.ansible-venv
  - ${TRAVIS_BUILD_DIR}/.ansible-venv/bin/pip install ansible
  - ${TRAVIS_BUILD_DIR}/.ansible-venv/bin/ansible -i localhost, localhost -c local -m template -a "src=${TRAVIS_BUILD_DIR}/env/common/templates/galaxy/config/job_router_conf.yml.j2 dest=${TRAVIS_BUILD_DIR}/env/common/files/galaxy/dynamic_rules/test/unit/job_router_conf.yml" --extra-vars=@${TRAVIS_BUILD_DIR}/env/main/group_vars/galaxyservers/tools_conf.yml
  - ${TRAVIS_BUILD_DIR}/.ansible-venv/bin/ansible -i localhost, localhost -c local -m template -a "src=${TRAVIS_BUILD_DIR}/env/common/templates/galaxy/config/job_conf.yml.j2 dest=${TRAVIS_BUILD_DIR}/env/common/files/galaxy/dynamic_rules/test/unit/job_conf.yml" --extra-vars=@${TRAVIS_BUILD_DIR}/env/main/group_vars/galaxyservers/tools_conf.yml --extra-vars=@${TRAVIS_BUILD_DIR}/env/common/files/galaxy/dynamic_rules/test/unit/mock_vars.yml
  - cp ${TRAVIS_BUILD_DIR}/env/common/files/galaxy/config/job_resource_params_conf.xml ${TRAVIS_BUILD_DIR}/env/common/files/galaxy/dynamic_rules/test/unit
  - export GALAXY_SKIP_CLIENT_BUILD=1
  - export GALAXY_VERSION=release_20.09
  - cd ${TRAVIS_BUILD_DIR}
  - wget https://github.com/galaxyproject/galaxy/archive/${GALAXY_VERSION}.tar.gz
  - tar xvzf ${GALAXY_VERSION}.tar.gz | tail
  - cd galaxy-${GALAXY_VERSION}
  - export GALAXY_DIR=$PWD
  - sh scripts/common_startup.sh
  - cd ${TRAVIS_BUILD_DIR}
  - mv ${GALAXY_DIR}/lib ${TRAVIS_BUILD_DIR}/env/common/files/galaxy/dynamic_rules/
  - source ${GALAXY_DIR}/.venv/bin/activate
  - pip install mock
  - pip install pytest
  - export PYTHONPATH=$PYTHONPATH:${TRAVIS_BUILD_DIR}/env/common/files/galaxy/dynamic_rules/lib/
  - cd ${TRAVIS_BUILD_DIR}/env/common/files/galaxy/dynamic_rules/test/
  - pytest -v  -s --log-level=debug
notifications:
  email: false
