---

- name: Create dynamic OS groups
  hosts: all
  remote_user: root
  tasks:
    - name: Group by OS family
      group_by: key=all_{{ ansible_os_family | lower }}_based_hosts
      changed_when: False

- name: Tasks for virtalized hosts
  hosts: virtualhosts
  remote_user: root
  roles:
    - virtual

- name: Manage users, packages, and other system configurations
  hosts: all:!tacc-vms
  remote_user: root
  roles:
    - requiretty
    - ssh
    - timezone
    - users
    - paths
    - packages
    - cron

- name: Install supervisor
  hosts: supervisorusers
  remote_user: root
  vars_files:
    - "{{ deploy_env }}/secret_vars/supervisorusers.yml"
  roles:
    - supervisor

- name: Manage PostgreSQL
  hosts: dbservers
  remote_user: root
  vars_files:
    - [ "{{ deploy_env }}/group_vars/{{ ansible_os_family | lower }}_dbservers.yml", "/dev/null" ]
  roles:
    - galaxyprojectdotorg.postgresql

- name: Manage nginx
  hosts: webservers
  remote_user: root
  vars_files:
    - "{{ deploy_env }}/secret_vars/ssl.yml"
  roles:
    - galaxyprojectdotorg.nginx
