---

# Allow root logins for hosts in EC2
- name: EC2 host initial setup
  hosts: ec2hosts
  remote_user: ubuntu
  sudo: yes
  roles:
    - users           # Add keys for direct root login
    - ssh             # Ensure direct root login is enabled
