---

- name: Update Galaxy on CVMFS stratum 0 server
  hosts: cvmfsstratum0servers
  remote_user: "{{ galaxy_user }}"
  tasks:
    - name: Begin CVMFS transaction
      command: /usr/bin/cvmfs_server transaction {{ galaxy_instance_codename }}.galaxyproject.org

    - name: Restart docker
      service:
        name: docker
        state: restarted

    - name: Fetch Galaxy commit
      command: "/usr/bin/git rev-parse HEAD"
      args:
        chdir: /cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/galaxy
      register: galaxy_commit_old

    - name: Update Galaxy
      # TODO: use docker_container maybe?
      command: "docker run --rm -v /cvmfs:/cvmfs galaxy/update su - {{ galaxy_user }} -c \"/cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/bin/update_galaxy.sh {{ galaxy_branch }}\""

    - name: Fetch Galaxy version
      command: "/usr/bin/docker run --rm -v /cvmfs:/cvmfs -e PYTHONPATH=/cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/galaxy/lib galaxy/update su {{ galaxy_user }} -c \"/cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/venv/bin/python -c 'from galaxy.version import VERSION; print VERSION'\""
      register: galaxy_version

    - name: Fetch Galaxy commit
      command: "/usr/bin/git rev-parse HEAD"
      args:
        chdir: /cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/galaxy
      register: galaxy_commit

    - name: Fetch Galaxy short commit
      command: "/usr/bin/git rev-parse --short HEAD"
      args:
        chdir: /cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/galaxy
      register: galaxy_commit_short

    - name: Abort CVMFS transaction
      command: /usr/bin/cvmfs_server abort -f {{ galaxy_instance_codename }}.galaxyproject.org
      when: galaxy_commit_old.stdout == galaxy_commit.stdout

    - name: Exit if no changes
      fail:
        msg: Galaxy commit ID did not change after updating, transaction aborted
      when: galaxy_commit_old.stdout == galaxy_commit.stdout

    - name: Store updated version information
      local_action:
        module: copy
        # Fixme: should probably use to_nice_yaml
        content: |
          ---
          galaxy_version: {{ galaxy_version.stdout }}
          galaxy_commit: {{ galaxy_commit.stdout }}
          galaxy_commit_short: {{ galaxy_commit_short.stdout }}
        dest: "{{ deploy_env }}/galaxy_version.yml"

    - name: Publish CVMFS transaction
      command: /usr/bin/cvmfs_server publish -a "galaxy_{{ galaxy_version.stdout }}_{{ galaxy_commit_short.stdout }}" -m "Update Galaxy to version {{ galaxy_version.stdout }} commit {{ galaxy_commit.stdout }} via Ansible" {{ galaxy_instance_codename }}.galaxyproject.org
  tags:
    - no-restart

- name: Snapshot CVMFS changes on stratum 1 servers
  hosts: cvmfsstratum1servers
  remote_user: "{{ galaxy_user }}"
  tags:
    - no-update
    - no-restart
  tasks:
    - name: CVMFS snapshot
      command: /usr/bin/cvmfs_server snapshot {{ galaxy_instance_codename }}.galaxyproject.org

    - name: Clear squid cache (restart)
      service:
        name: squid
        state: restarted

- name: Wipe CVMFS cache on Galaxy servers
  hosts: galaxyservers
  remote_user: "{{ galaxy_user }}"
  tags:
    - no-update
    - no-restart
  tasks:
    - name: Wipe CVMFS cache
      command: /usr/local/bin/cvmfs_wipecache

- name: Galaxy database and interactive environments
  hosts: galaxywebservers
  remote_user: "{{ galaxy_user }}"
  tags:
    - no-update
    - no-restart
    - no-cvmfs
  vars_files:
    - "{{ deploy_env }}/secret_vars/galaxyservers.yml"
    - "{{ deploy_env }}/galaxy_version.yml"
  vars:
    instance_root: "{{ galaxy_root }}"
    galaxy_config: "{{ galaxy_config_hash }}"
    interactive_environments_plugins_version: "{{ galaxy_commit }}"
    interactive_environments_proxy_version: "{{ galaxy_commit }}"
  roles:
    # manage the database
    - role: galaxyprojectdotorg.galaxy
      galaxy_manage_clone: no
      galaxy_manage_static_setup: no
      galaxy_manage_mutable_setup: no
      galaxy_manage_database: yes
      galaxy_fetch_eggs: no
      when: inventory_hostname in groups['galaxymasters']
    # Set up interactive environments
    - role: galaxyprojectdotorg.interactive_environments

- name: Update version in welcome.html
  hosts: galaxywebservers
  remote_user: "{{ galaxy_privileged_user }}"
  tags:
    - no-update
    - no-restart
    - no-cvmfs
  vars_files:
    - "{{ deploy_env }}/secret_vars/galaxyservers.yml"
    - "{{ deploy_env }}/galaxy_version.yml"
  roles:
    - role: usegalaxy_static

- name: Restart Galaxy
  hosts: galaxyservers
  remote_user: "{{ galaxy_user }}"
  tags:
    - no-update
    - no-cvmfs
  tasks:
    - name: Restart Galaxy
      command: /home/{{ galaxy_user }}/bin/galaxy graceful

- name: Update Galaxy on Pulsar servers
  hosts: pulsargalaxyservers
  remote_user: "{{ galaxy_user }}"
  tags:
    - no-update
    - no-cvmfs
  vars_files:
    - "{{ deploy_env }}/secret_vars/pulsarservers.yml"
    - "{{ deploy_env }}/galaxy_version.yml"
  vars:
    galaxy_changeset_id: "{{ galaxy_commit }}"
  roles:
    # set up galaxy clone
    - role: galaxyprojectdotorg.galaxy
      galaxy_manage_mutable_setup: no
      galaxy_manage_database: no
