---

# FIXME: can't notify for restart across plays

- name: Galaxy web code and eggs, manage static configs
  hosts: galaxyservers
  remote_user: "{{ galaxy_privileged_user }}"
  vars_files:
    - "{{ deploy_env }}/secret_vars/galaxyservers.yml"
  vars:
    instance_root: "{{ galaxy_web_root }}"
    galaxy_root: "{{ galaxy_web_root }}"
    galaxy_server_dir: "{{ galaxy_web_server_dir }}"
    galaxy_eggs_path: "{{ galaxy_web_eggs_path }}"
    galaxy_config: "{{ galaxy_config_hash }}"
  roles:
    # set up local galaxy clone and local config
    - role: galaxyprojectdotorg.galaxy
      galaxy_manage_clone: yes
      galaxy_manage_static_setup: yes
      galaxy_manage_mutable_setup: no
      galaxy_manage_database: no
      galaxy_fetch_eggs: yes
  post_tasks:
    # create impersonation config on Main
    - name: Set galaxy_config to impersonate_config_hash
      set_fact:
        galaxy_config: "{{ impersonate_config_hash }}"
      when: deploy_env == "production"

    - name: Create Galaxy impersonation configuration file
      template: src=roles/galaxyprojectdotorg.galaxy/templates/galaxy.ini.j2 dest={{ galaxy_config_dir }}/impersonate.ini backup=yes
      when: deploy_env == "production"

- name: Galaxy handler code and eggs
  hosts: galaxymasters
  remote_user: "{{ galaxy_privileged_user }}"
  vars_files:
    - "{{ deploy_env }}/secret_vars/galaxyservers.yml"
  vars:
    instance_root: "{{ galaxy_handler_root }}"
    galaxy_root: "{{ galaxy_handler_root }}"
    galaxy_server_dir: "{{ galaxy_handler_server_dir }}"
    galaxy_eggs_path: "{{ galaxy_handler_eggs_path }}"
    galaxy_config: "{{ galaxy_config_hash }}"
  roles:
    # set up handler galaxy clone
    - role: galaxyprojectdotorg.galaxy
      galaxy_manage_clone: yes
      galaxy_manage_static_setup: no
      galaxy_manage_mutable_setup: no
      galaxy_manage_database: no
      galaxy_fetch_eggs: yes

- name: Galaxy database and mutable configs
  hosts: galaxyservers
  remote_user: "{{ galaxy_user }}"
  vars_files:
    - "{{ deploy_env }}/secret_vars/galaxyservers.yml"
  vars:
    instance_root: "{{ galaxy_web_root }}"
    galaxy_root: "{{ galaxy_web_root }}"
    galaxy_server_dir: "{{ galaxy_web_server_dir }}"
    galaxy_eggs_path: "{{ galaxy_web_eggs_path }}"
    galaxy_config: "{{ galaxy_config_hash }}"
  roles:
    # manage the database
    - role: galaxyprojectdotorg.galaxy
      galaxy_manage_clone: no
      galaxy_manage_static_setup: no
      galaxy_manage_mutable_setup: yes
      galaxy_manage_database: yes
      galaxy_fetch_eggs: no
      when: inventory_hostname in groups['galaxymasters']
    # fetch and distribute mutable configs (needs the galaxy_mutable_configs
    # var set in galaxyprojectdotorg.galaxy)
    - role: usegalaxy

- name: Galaxy privileged user tasks and static content setup
  hosts: galaxyservers
  remote_user: "{{ galaxy_privileged_user }}"
  vars_files:
    - "{{ deploy_env }}/secret_vars/galaxyservers.yml"
  vars:
    galaxy_root: "{{ galaxy_web_root }}"
  roles:
    - role: usegalaxy_privileged
    # welcome page
    - role: usegalaxy_static

- name: Update Galaxy on Pulsar servers
  hosts: pulsarservers
  remote_user: "{{ galaxy_user }}"
  vars_files:
    - [ "{{ deploy_env }}/secret_host_vars/{{ inventory_hostname }}.yml", "{{ deploy_env }}/secret_host_vars/default.yml" ]
  roles:
    # set up galaxy clone
    - role: galaxyprojectdotorg.galaxy
      galaxy_manage_mutable_setup: no
      galaxy_manage_database: no
