---

# FIXME: can't notify for restart across plays

- name: Galaxy static configs
  hosts: galaxyservers
  remote_user: "{{ galaxy_privileged_user }}"
  vars_files:
    - "{{ deploy_env }}/secret_vars/galaxyservers.yml"
  vars:
    instance_root: "{{ galaxy_web_root }}"
    galaxy_root: "{{ galaxy_web_root }}"
    galaxy_server_dir: "{{ galaxy_web_server_dir }}"
    galaxy_eggs_path: "{{ galaxy_web_eggs_path }}"
    galaxy_config: "{{ galaxy_config_hash }}"
  roles:
    # set up local galaxy clone and local config
    - role: galaxyprojectdotorg.galaxy
      galaxy_manage_clone: no
      galaxy_manage_static_setup: yes
      galaxy_manage_mutable_setup: no
      galaxy_manage_database: no
      galaxy_fetch_eggs: no
  post_tasks:
    # create impersonation config on Main
    - name: Set galaxy_config to impersonate_config_hash
      set_fact:
        galaxy_config: "{{ impersonate_config_hash }}"
      when: deploy_env == "production"

    - name: Create Galaxy impersonation configuration file
      template: src=roles/galaxyprojectdotorg.galaxy/templates/galaxy.ini.j2 dest={{ galaxy_config_dir }}/impersonate.ini backup=yes
      when: deploy_env == "production"

    # create installer config
    - name: Set galaxy_config to installer_config_hash
      set_fact:
        galaxy_config: "{{ installer_config_hash }}"

    - name: Create Galaxy installer configuration file
      template: src=roles/galaxyprojectdotorg.galaxy/templates/galaxy.ini.j2 dest={{ galaxy_config_dir }}/installer.ini backup=yes

- name: Galaxy mutable configs
  hosts: galaxyservers
  remote_user: "{{ galaxy_user }}"
  vars_files:
    - "{{ deploy_env }}/secret_vars/galaxyservers.yml"
  vars:
    instance_root: "{{ galaxy_web_root }}"
    galaxy_root: "{{ galaxy_web_root }}"
    galaxy_server_dir: "{{ galaxy_web_server_dir }}"
    galaxy_eggs_path: "{{ galaxy_web_eggs_path }}"
    galaxy_config: "{{ galaxy_config_hash }}"
  roles:
    # fetch and distribute mutable configs (needs the galaxy_mutable_configs
    # var set in galaxyprojectdotorg.galaxy)
    - role: usegalaxy

- name: Galaxy privileged user tasks
  hosts: galaxyservers
  remote_user: "{{ galaxy_privileged_user }}"
  vars_files:
    - "{{ deploy_env }}/secret_vars/galaxyservers.yml"
  vars:
    galaxy_root: "{{ galaxy_web_root }}"
  roles:
    - role: usegalaxy_privileged
