---

- name: Manage PostgreSQL users, groups, databases, and permissions
  hosts: galaxydbservers
  remote_user: root
  sudo: yes
  sudo_user: postgres
  vars_files:
    - "{{ deploy_env }}/secret_vars/galaxydbservers.yml"
  roles:
    - natefoo.postgresql_objects

- name: Set sysctl values for uWSGI
  hosts: galaxywebservers:galaxystagingservers
  remote_user: root
  tasks:
    - name: Set sysctl values
      sysctl: name={{ item.name }} value={{ item.value }} reload=no sysctl_set=yes
      with_items: sysctl_conf

- name: nginx tasks
  hosts: galaxywebservers:galaxystagingservers
  remote_user: root
  vars_files:
    - "{{ deploy_env }}/secret_vars/galaxyservers.yml"
    # FIXME: nginx/ssl config should move to infrastructure-playbook
    - "common/secret_vars/ssl.yml"
  vars:
    instance_root: "{{ galaxy_root }}"
    # FIXME: this is defined by the supervisor role
    supervisord_conf_dir: /etc/opt/supervisor
  pre_tasks:
    - name: Configure Galaxy yum repository
      copy:
        content: |
          [galaxy]
          name=Galaxy Packages for Enterprise Linux $releasever - $basearch
          baseurl=https://depot.galaxyproject.org/yum/el/$releasever/$basearch/
          enabled=1
          gpgcheck=0
        dest: /etc/yum.repos.d/galaxy.repo
  roles:
    - galaxyprojectdotorg.nginx
  tags: nginx

- name: Webserver tasks
  hosts: galaxywebservers
  remote_user: root
  vars_files:
    - "{{ deploy_env }}/secret_vars/galaxyservers.yml"
  vars:
    instance_root: "{{ galaxy_root }}"
  roles:
    - errordocs
  tags: nginx

- name: Manage supervisor and root tasks
  hosts: galaxyservers
  remote_user: root
  vars_files:
    - "{{ deploy_env }}/secret_vars/galaxyservers.yml"
  vars:
    instance_root: "{{ galaxy_root }}"
  roles:
    - usegalaxy_admin
    - supervisor
  tags: supervisor
