---

- hosts: pulsarservers
  remote_user: "{{ galaxy_user }}"
  vars_files:
    - "{{ deploy_env }}/secret_vars/pulsarservers.yml"
  roles:
    # set up pulsar
    - galaxyprojectdotorg.pulsar
    - copy
