---

- hosts: pulsarservers
  remote_user: "{{ galaxy_user }}"
  vars_files:
    - "{{ deploy_env }}/secret_vars/pulsarservers.yml"
  roles:
    # set up pulsar
    - role: galaxyprojectdotorg.pulsar
    # set up galaxy clone
    - role: galaxyprojectdotorg.galaxy
      galaxy_manage_mutable_setup: no
      galaxy_manage_database: no
