---
- name: galaxyproject.postgresql
  version: 1.0.2
- name: galaxyproject.galaxy
  version: 0.9.2
- name: galaxyproject.galaxy_toolshed
  version: 0.2.2
- name: usegalaxy-eu.certbot
  src: https://github.com/usegalaxy-eu/ansible-certbot.git/
- name: galaxyproject.nginx
  version: 0.6.4
- name: galaxyproject.pulsar
  version: 1.0.4
- name: galaxyproject.proftpd
  version: 0.3.0
