---
- name: galaxyproject.postgresql
  version: 1.0.2
- name: galaxyproject.galaxy
  version: 0.9.12
- name: galaxyproject.galaxy_toolshed
  version: 0.2.3
- name: usegalaxy_eu.certbot
  version: 0.1.4
- name: galaxyproject.nginx
  version: 0.6.4
- name: galaxyproject.pulsar
  version: 1.0.7
- name: galaxyproject.proftpd
  version: 0.3.0
- name: usegalaxy_eu.tiaas2
  version: 0.0.6
