---
- name: galaxyproject.galaxy
  version: 0.9.1
- name: galaxyproject.galaxy_toolshed
  version: 0.2.0
- name: usegalaxy-eu.certbot
  src: https://github.com/usegalaxy-eu/ansible-certbot.git/
- name: galaxyproject.nginx
  version: 0.6.4
