---
roles:
  - name: galaxyproject.postgresql_objects
    version: 1.2.0
  - name: galaxyproject.galaxy
    src: https://github.com/galaxyproject/ansible-galaxy
    version: local-tools-sections
    # update after merge of https://github.com/galaxyproject/ansible-galaxy/pull/206
    #version: 0.10.21
  - name: usegalaxy_eu.certbot
    version: 0.1.4
  - name: galaxyproject.nginx
    version: 0.7.1
  - name: galaxyproject.pulsar
    version: 1.0.11
  - name: galaxyproject.tiaas2
    version: 2.1.6
  - name: galaxyproject.miniconda
    version: 0.3.1
  - name: galaxyproject.tusd
    version: 0.0.1
  - name: galaxyproject.cvmfsexec
    version: 1.1.1
  - name: usegalaxy_eu.tpv_auto_lint
    src: https://github.com/usegalaxy-eu/ansible-tpv-lint
    version: deploy-configs
  - name: geerlingguy.redis
    version: 1.8.0

collections:
  - name: kubernetes.core
    # really we just need >= 2.2.0 and this could be installed with ansible
    version: 2.3.2
