---
roles:
  - name: galaxyproject.galaxy
    version: 0.11.1
  - name: usegalaxy_eu.certbot
    version: 0.1.4
  - name: galaxyproject.nginx
    version: 0.7.1
  - name: galaxyproject.pulsar
    version: 1.0.11
  - name: galaxyproject.tiaas2
    version: 2.1.6
  - name: galaxyproject.miniconda
    version: 0.3.1
  - name: galaxyproject.tusd
    version: 0.0.1
  - name: galaxyproject.cvmfsexec
    version: 1.1.1
  - name: usegalaxy_eu.tpv_auto_lint
    src: https://github.com/usegalaxy-eu/ansible-tpv-lint
    version: deploy-configs
