---
- name: galaxyproject.postgresql
  version: 1.0.2
- name: galaxyproject.galaxy
  version: 0.9.6
- name: galaxyproject.galaxy_toolshed
  version: 0.2.3
- name: usegalaxy_eu.certbot
  version: 0.1.4
- name: galaxyproject.nginx
  version: 0.6.4
- name: galaxyproject.pulsar
  version: 1.0.6
- name: galaxyproject.proftpd
  version: 0.3.0
