---

- name: Manage packages
  hosts: toolsheddbservers
  remote_user: root
  roles:
    - packages

- name: Install and configure PostgreSQL
  hosts: toolsheddbservers
  remote_user: root
  roles:
    - galaxyprojectdotorg.postgresql

- name: Manage PostgreSQL users, groups, databases, and permissions
  hosts: toolsheddbservers
  remote_user: root
  sudo: yes
  sudo_user: postgres
  roles:
    - natefoo.postgresql_objects

- name: Install and configure supervisor and nginx vhosts and error documents
  hosts: toolshedservers
  remote_user: root
  vars_files:
    - "{{ deploy_env }}/secret_vars/toolshedservers.yml"
  roles:
    - galaxyprojectdotorg.nginx
    - supervisor
    - errordocs
