---
# FIXME: this is not ideal

- name: Distribute tool shed systemd unit
  hosts: toolshedservers
  remote_user: root
  tasks:
    - name: Distribute systemd unit
      template:
        src: "templates/systemd/tool_shed.service.j2"
        dest: "/etc/systemd/system/tool_shed.service"
        mode: "0600"
