---

paths:
  - path: /cvmfs/data.galaxyproject.org
    path_types: unstructured
    action: rewrite
    source_directory: /cvmfs/data.galaxyproject.org
    destination_directory: /work2/03166/xcgalaxy/stampede2/cvmfs/data.galaxyproject.org
