---

paths:
  - path: /cvmfs/data.galaxyproject.org
    path_types: unstructured
    action: rewrite
    source_directory: /cvmfs/data.galaxyproject.org
    destination_directory: /expanse/projects/qstore/pen160/xgalaxy/cvmfs/data.galaxyproject.org
