---

## used by: galaxyproject.galaxy
# galaxy_root is defined in host_vars
# galaxy_server_dir and galaxy_config_dir are set by galaxyproject.galaxy based on the layout
galaxy_layout: root-dir
galaxy_config_style: ini-paste
galaxy_venv_dir: "{{ galaxy_root }}/venv"
galaxy_config_file: "{{ galaxy_config_dir }}/galaxy.ini"

galaxy_config_files:
  - src: files/galaxy/config/ucsc_build_sites.txt
    dest: "{{ galaxy_config_dir }}/ucsc_build_sites.txt"
