---

## used by: galaxyproject.galaxy
galaxy_server_dir: "{{ galaxy_root }}/server"
galaxy_config_dir: "{{ galaxy_root }}/config"
galaxy_venv_dir: "{{ galaxy_root }}/venv"
galaxy_config_file: "{{ galaxy_config_dir }}/galaxy.ini"

galaxy_config_files:
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/ucsc_build_sites.txt
    dest: "{{ galaxy_config_dir }}/ucsc_build_sites.txt"
