---

zergmode_vassal_dir:
  path: "{{ galaxy_toolshed_config_dir }}/vassals"
  owner: "{{ toolshed_privileged_user }}"
zergmode_run_dir:
  path: "{{ galaxy_toolshed_root }}/var/zerg"
  owner: "{{ toolshed_user }}"
zergmode_pool_socket: "{{ zergmode_run_dir.path }}/pool.sock"
zergmode_uwsgi_socket: 127.0.0.1:8080
zergmode_app_dir: "{{ galaxy_toolshed_server_dir }}"
zergmode_app_config: "{{ galaxy_toolshed_config_file }}"
zergmode_app_description: "Galaxy Tool Shed Server"
zergmode_app_documentation: https://docs.galaxyproject.org/
zergmode_user: "{{ toolshed_user }}"
zergmode_environment:
  - "VIRTUAL_ENV={{ galaxy_toolshed_venv_dir }}"
  - "PATH={{ galaxy_toolshed_venv_dir }}/bin:/usr/sbin:/usr/bin"
  - "TMPDIR={{ toolshed_tmpdir }}"
zergmode_uwsgi_path: "{{ galaxy_toolshed_venv_dir }}/bin/uwsgi"
zergmode_service_name: toolshed

nginx_enable_default_server: false

nginx_conf_ssl_protocols:
    - TLSv1.2

nginx_conf_http:
  server_names_hash_bucket_size: 128
  client_max_body_size: 64M
  proxy_read_timeout: 3600
  uwsgi_read_timeout: 600
  gzip_vary: 'on'
  gzip_proxied: any
  gzip_comp_level: 6
  gzip_buffers: 16 8k
  gzip_http_version: 1.1
  gzip_types: text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript


## used by: galaxyproject.galaxy
nginx_srv: /srv/nginx
nginx_ssl_role: usegalaxy_eu.certbot
nginx_conf_ssl_certificate: /etc/ssl/certs/fullchain.pem
nginx_conf_ssl_certificate_key: /etc/ssl/private/privkey.pem

certbot_auto_renew_hour: "{{ 23 |random(seed=inventory_hostname)  }}"
certbot_auto_renew_minute: "{{ 59 |random(seed=inventory_hostname)  }}"
certbot_auth_method: --webroot
certbot_install_method: virtualenv
certbot_auto_renew: yes
certbot_auto_renew_user: root
certbot_environment: production
certbot_well_known_root: "{{ nginx_srv }}/_well-known_root"
#certbot_share_key_users:
#  - "{{ nginx_conf_user }}"
certbot_post_renewal: |
    systemctl restart nginx || true
certbot_agree_tos: --agree-tos
certbot_virtualenv_package_name: python3-venv
certbot_virtualenv_command: python3 -m venv

nginx_servers:
  - certbot_redirects

nginx_ssl_servers:
  - toolshed

certbot_domains:
  - "{{ inventory_hostname }}"
  - "{{ galaxy_toolshed_instance_hostname }}"

## used by the sysctl task in the stack playbook
# not supported in LX Brand
#sysctl_conf:
#  - name: net.core.rmem_max
#    value: 15990784
#  - name: net.core.wmem_max
#    value: 15990784
