---

# Tool Shed version
#galaxy_commit_id: 45527c64605778f33473ec4ae107690ba4ec7898
galaxy_commit_id: toolshed
# currently needed for client artifacts left in the source tree
galaxy_force_checkout: yes


# used by: toolshedservers/common_vars.yml
toolshed_backup_hour: 0
toolshed_tmpwatch_hour: 1
toolshed_dbname: galaxy_toolshed


## used by: other vars and various templates
galaxy_toolshed_instance_codename: main
galaxy_toolshed_instance_hostname: toolshed.g2.bx.psu.edu


## used by: galaxyproject.galaxy
galaxy_errordocs_server_name: "The Tool Shed"


# tool_shed.yml contents
galaxy_toolshed_config:
  uwsgi:
    module: tool_shed.webapp.buildapp:uwsgi_app()
    # bind a random socket
    socket: 127.0.0.1:0
    #socket: "{{ galaxy_toolshed_mutable_config_dir }}/uwsgi.sock"
    # FIXME: this breaks zerg mode
    #stats: "127.0.0.1:9192"
    processes: 4
    threads: 4
    offload-threads: 2
    reload-on-rss: 1100
    master: True
    logto: "{{ galaxy_toolshed_log_dir }}/uwsgi.log"
    pythonpath: lib
    unique-cron: "-15 -1 -1 -1 -1 {{ galaxy_venv_dir }}/bin/python scripts/tool_shed/build_ts_whoosh_index.py -c {{ galaxy_toolshed_config_file }} --config-section tool_shed -d"
  tool_shed:
    # secrets

    id_secret: "{{ galaxy_toolshed_config_id_secret }}"
    admin_users: "{{ galaxy_toolshed_config_admin_users }}"

    # paths

    file_path: "/srv/toolshed-repos/{{ galaxy_toolshed_instance_codename }}"
    new_file_path: "{{ galaxy_toolshed_mutable_data_dir }}/tmp"
    tool_data_path: "{{ galaxy_toolshed_mutable_data_dir }}/tool-data"

    # general stuff

    database_connection: "postgresql:///galaxy_toolshed?host=/var/run/postgresql"
    log_level: "DEBUG"
    ga_code: "UA-45719423-12"
    debug: "False"
    use_lint: "False"
    num_tool_test_results_saved: "5"
    support_url: "https://galaxyproject.org/support"
    smtp_server: "smtp.psu.edu"
    email_from: "galaxy-no-reply@toolshed.g2.bx.psu.edu"
    sentry_dsn: "{{ galaxy_toolshed_config_sentry_dsn }}"

     # stuff that shouldn't be here but actually has to
    conda_auto_init: false
    tool_dependency_dir: "{{ galaxy_toolshed_mutable_data_dir }}/dependencies"
