---

- name: Update Galaxy client on CVMFS stratum 0 server
  hosts: cvmfsstratum0servers
  remote_user: "{{ galaxy_user }}"
  vars_files:
    - "{{ galaxy_version_file }}"
  roles:
    - role: usegalaxy_cvmfs
      galaxy_cvmfs_client: "{{ galaxy_cvmfs_client_on_update }}"

- name: Include snapshot plays
  include: _inc_snapshot.yml
