---

- name: Update Galaxy client on CVMFS stratum 0 server
  hosts: cvmfsstratum0servers
  remote_user: "{{ galaxy_user }}"
  vars_files:
    - "{{ galaxy_version_file }}"
  roles:
    - role: usegalaxy_cvmfs
      galaxy_cvmfs_client: "{{ galaxy_cvmfs_client_on_update }}"
      galaxy_client_force_build: true

- name: Include snapshot plays
  import_playbook: _inc_snapshot.yml
