---

- name: Galaxy static configs
  hosts: galaxyservers
  # NOTE: we also use privsep mode in the role
  #remote_user: "{{ galaxy_privileged_user }}"
  vars:
    galaxy_config: "{{ galaxy_config_hash }}"
  pre_tasks:
    - name: Create privileged config subdirs
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ galaxy_root }}/bin"
        - "{{ galaxy_config.galaxy.panel_views_dir }}"
      become: true
    - name: Create unprivileged config subdirs
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ galaxy_user }}"
        group: "{{ galaxy_system_group }}"
        mode: "0755"
      loop:
        - "{{ galaxy_mutable_data_dir }}"
        - "{{ galaxy_log_dir }}"
      become: true
    - name: Locate TPV python blobs
      set_fact:
        tpv_python_blobs: "{{ (tpv_python_blobs | default({})) | combine({(item | basename | splitext | first): lookup('file', item)}) }}"
      with_fileglob: "{{ inventory_dir }}/files/galaxy/config/tpv/*.py"
  roles:
    # set up local galaxy clone and local config
    - role: galaxyproject.galaxy
      galaxy_separate_privileges: yes
      galaxy_manage_clone: no
      galaxy_manage_static_setup: yes
      galaxy_manage_mutable_setup: no
      galaxy_manage_subdomain_static: no
      galaxy_manage_themes: yes
      galaxy_manage_database: no
      galaxy_fetch_dependencies: no
      galaxy_manage_errordocs: no
      galaxy_build_client: no
      galaxy_manage_systemd: no
      galaxy_manage_gravity: no
    - role: usegalaxy_eu.tpv_auto_lint
      become: true
  handlers:
    - name: galaxy gravity graceful restart
      command: "{{ galaxy_gravity_command }} graceful"
      environment:
        GRAVITY_CONFIG_FILE: "{{ gravity_config_file }}"
      listen: "restart galaxy"
      when: restart is truthy(convert_bool=true)
    - name: galaxyctl update
      command: "{{ galaxy_gravity_command }} update"

- name: Galaxy mutable configs
  hosts: galaxyservers
  remote_user: "{{ galaxy_user }}"
  vars:
    galaxy_config: "{{ galaxy_config_hash }}"
  roles:
    # fetch and distribute mutable configs (needs the galaxy_mutable_config_files
    # var set in galaxyproject.galaxy)
    - role: usegalaxy
    - role: usegalaxy_backup

- name: Galaxy privileged user tasks
  hosts: galaxyservers
  become: true
  roles:
    - role: usegalaxy_privileged

#- name: Include restart plays
#  import_playbook: _inc_restart.yml
