---

- name: Galaxy static configs
  hosts: galaxyservers
  # NOTE: we also use privsep mode in the role
  remote_user: "{{ galaxy_privileged_user }}"
  vars:
    galaxy_config: "{{ galaxy_config_hash }}"
  pre_tasks:
    - name: Create config subdirs
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ galaxy_config.galaxy.panel_views_dir }}"
    - name: Locate TPV python blobs
      set_fact:
        tpv_python_blobs: "{{ (tpv_python_blobs | default({})) | combine({(item | basename | splitext | first): lookup('file', item)}) }}"
      with_fileglob: "{{ inventory_dir }}/files/galaxy/config/tpv/*.py"
  roles:
    # set up local galaxy clone and local config
    - role: galaxyproject.galaxy
      galaxy_separate_privileges: yes
      galaxy_manage_clone: no
      galaxy_manage_static_setup: yes
      galaxy_manage_mutable_setup: no
      galaxy_manage_subdomain_static: no
      galaxy_manage_themes: "{{ __galaxy_manage_themes | default(true) }}"
      galaxy_manage_database: no
      galaxy_fetch_dependencies: no
      galaxy_manage_errordocs: no
      galaxy_build_client: no
      galaxy_manage_systemd: no
      galaxy_manage_gravity: no
    - role: usegalaxy_webhooks
    - role: usegalaxy_eu.tpv_auto_lint
  handlers:
    - name: galaxy gravity graceful restart
      command: "{{ galaxy_gravity_command }} --no-user graceful"
      environment:
        GRAVITY_CONFIG_FILE: "{{ gravity_config_file }}"
      listen: "restart galaxy"
      when: restart is truthy(convert_bool=true)
      # FIXME: gravity has no way to force root mode when not root
      #become_user: "{{ galaxy_privileged_user }}"
    # FIXME: this has to run as root, but in theory should only change when the Gravity config changes
    - name: galaxyctl update
      debug:
        msg: "FIXME: galaxyctl update not implemented in this playbook"
      #command: "{{ galaxy_gravity_command }} --no-user update"
      #environment:
      #  GRAVITY_CONFIG_FILE: "{{ gravity_config_file }}"
      ##become: true

- name: Galaxy mutable configs
  hosts: galaxyservers
  remote_user: "{{ galaxy_user }}"
  vars:
    galaxy_config: "{{ galaxy_config_hash }}"
  roles:
    # fetch and distribute mutable configs (needs the galaxy_mutable_config_files
    # var set in galaxyproject.galaxy)
    - role: usegalaxy
    - role: usegalaxy_backup

- name: Galaxy privileged user tasks
  hosts: galaxyservers
  remote_user: "{{ galaxy_privileged_user }}"
  roles:
    - role: usegalaxy_privileged

#- name: Include restart plays
#  import_playbook: _inc_restart.yml
