---

- name: Galaxy static configs
  hosts: galaxyservers
  # NOTE: we also use privsep mode in the role
  remote_user: "{{ galaxy_privileged_user }}"
  vars:
    galaxy_config: "{{ galaxy_config_hash }}"
  roles:
    # set up local galaxy clone and local config
    - role: galaxyproject.galaxy
      galaxy_separate_privileges: yes
      galaxy_manage_clone: no
      galaxy_manage_static_setup: yes
      galaxy_manage_mutable_setup: no
      galaxy_manage_database: no
      galaxy_fetch_dependencies: no
      galaxy_manage_errordocs: no
      galaxy_build_client: no
      galaxy_manage_systemd: no
      galaxy_manage_gravity: no
  post_tasks:
    # create impersonation config on Main
    - name: Include config post-tasks
      include_tasks: _inc_config_post_tasks.yml
  handlers:
    - name: galaxy gravity restart
      remote_user: root
      command: "{{ galaxy_venv_dir }}/bin/galaxyctl graceful"
      environment:
        GRAVITY_CONFIG_FILE: "{{ galaxy_config_file }}"
      listen: "restart galaxy"
    - name: galaxyctl update
      remote_user: root
      command: "{{ galaxy_venv_dir }}/bin/galaxyctl update"
      environment:
        GRAVITY_CONFIG_FILE: "{{ galaxy_config_file }}"
  tags:
    - no-restart

- name: Galaxy mutable configs
  hosts: galaxyservers
  remote_user: "{{ galaxy_user }}"
  vars:
    galaxy_config: "{{ galaxy_config_hash }}"
  roles:
    # fetch and distribute mutable configs (needs the galaxy_mutable_config_files
    # var set in galaxyproject.galaxy)
    - role: usegalaxy
    - role: usegalaxy_backup
  tags:
    - no-restart

- name: Galaxy privileged user tasks
  hosts: galaxyservers
  remote_user: "{{ galaxy_privileged_user }}"
  roles:
    - role: usegalaxy_privileged
  tags:
    - no-restart

#- name: Include restart plays
#  import_playbook: _inc_restart.yml
