---

- name: Restart Galaxy
  hosts: galaxyservers
  become: true
  tasks:
    - name: Gracefully Restart Galaxy
      command: "{{ galaxy_gravity_command }} graceful"
      environment:
        GRAVITY_CONFIG_FILE: "{{ gravity_config_file }}"
