---

- name: Restart Galaxy
  hosts: galaxyservers
  remote_user: root
  tasks:
    - name: Gracefully Restart Galaxy
      command: "{{ galaxy_gravity_command }} graceful"
      environment:
        GRAVITY_CONFIG_FILE: "{{ gravity_config_file }}"
