---

- name: Tool Shed code, manage static configs
  hosts: toolshedservers
  remote_user: "{{ toolshed_privileged_user }}"
  roles:
    - role: galaxyproject.galaxy
      galaxy_manage_clone: yes
      galaxy_manage_static_setup: no
      galaxy_manage_mutable_setup: no
      galaxy_manage_database: no
      galaxy_fetch_dependencies: no
      galaxy_manage_errordocs: no
      # TODO: use this
      galaxy_build_client: no
    - role: galaxyproject.galaxy_toolshed
      galaxy_toolshed_manage_static_setup: yes
      galaxy_toolshed_manage_database: no

# This role was previously right after galaxyproject.galaxy_toolshed above, but for whatever reason, Ansible 2.3.* was
# running it the second time with the parameters from the first time. This fixes that. Perhaps it will be fixed in a
# later version.
- name: Tool Shed dependencies
  hosts: toolshedservers
  remote_user: "{{ toolshed_privileged_user }}"
  roles:
    - role: galaxyproject.galaxy
      galaxy_manage_clone: no
      galaxy_manage_static_setup: no
      galaxy_manage_mutable_setup: no
      galaxy_manage_database: no
      galaxy_fetch_dependencies: yes
      galaxy_manage_errordocs: yes
      galaxy_build_client: no

- name: Build client
  hosts: toolshedservers
  remote_user: "{{ toolshed_privileged_user }}"
  # This would be needed to fix ansible/ansible#14959 but the fix for that fix (ansible/ansible#17213) does not exist in
  # Ansible 2.3*, and such is the story of another few hours of my life wasted fighting with Ansible.
  #gather_facts: yes
  tasks:
    - include_tasks: _inc_client_build.yml

- name: Tool Shed database
  hosts: toolshedservers
  remote_user: "{{ toolshed_user }}"
  roles:
    - role: galaxyproject.galaxy_toolshed
      galaxy_toolshed_manage_static_setup: no
      galaxy_toolshed_manage_database: yes
  tasks:
    - name: Set hgweb archive types
      ini_file: dest=~/.hgrc backup=yes section=web option=allow_archive value="bz2, gz, zip"
