---

- name: Update Galaxy on CVMFS stratum 0 server
  hosts: cvmfsstratum0servers
  remote_user: "{{ galaxy_user }}"
  roles:
    - role: usegalaxy_cvmfs
      galaxy_cvmfs_update: yes
  vars:
    galaxy_config: "{{ galaxy_config_hash }}"
  environment:
    XDG_CACHE_HOME: "{{ xdg_cache_home | default(('/home', galaxy_user, '.cache') | path_join) }}"

- name: Include snapshot plays
  import_playbook: _inc_snapshot.yml

- name: Galaxy database
  hosts: galaxywebservers
  remote_user: "{{ galaxy_user }}"
  tags:
    - no-cvmfs
  vars:
    galaxy_config: "{{ galaxy_config_hash }}"
  roles:
    # manage the database
    - role: galaxyproject.galaxy
      galaxy_manage_clone: no
      galaxy_manage_static_setup: no
      galaxy_manage_mutable_setup: no
      galaxy_manage_database: yes
      galaxy_fetch_dependencies: no
      galaxy_manage_errordocs: no
      galaxy_build_client: no
      galaxy_manage_systemd: no
      galaxy_manage_gravity: no
      when: inventory_hostname in groups['galaxymasters']
  handlers:
    - name: galaxy gravity graceful restart
      remote_user: root
      command: "{{ galaxy_venv_dir }}/bin/galaxyctl graceful"
      environment:
        GRAVITY_CONFIG_FILE: "{{ galaxy_config_file }}"
      listen: "restart galaxy"
      when: restart is truthy(convert_bool=true)
    - name: galaxyctl update
      remote_user: root
      command: "{{ galaxy_venv_dir }}/bin/galaxyctl update"
      environment:
        GRAVITY_CONFIG_FILE: "{{ galaxy_config_file }}"

- name: Include static content plays
  import_playbook: _inc_static.yml
  tags:
    - no-cvmfs

#- name: Include restart plays
#  import_playbook: _inc_restart.yml
#  tags:
#    - no-cvmfs
#
#- name: Update Galaxy on Pulsar servers
#  hosts: pulsargalaxyservers
#  vars_files:
#    - files/galaxy/galaxy_version.yml
#  vars:
#    # FIXME: why are these named differently?
#    galaxy_commit_id: "{{ galaxy_commit }}"
#  roles:
#    - role: galaxyproject.galaxy
#      galaxy_manage_clone: yes
#      galaxy_manage_static_setup: yes    # config has to exist for conditional wheel fetching
#      galaxy_manage_mutable_setup: no
#      galaxy_manage_database: no
#      galaxy_fetch_dependencies: yes
#      galaxy_manage_errordocs: no
#      galaxy_build_client: no
#      galaxy_manage_systemd: no
#  tags:
#    - no-cvmfs
