---

- name: Update Galaxy on CVMFS stratum 0 server
  hosts: cvmfsstratum0servers
  remote_user: "{{ galaxy_user }}"
  roles:
    - role: usegalaxy_cvmfs
      galaxy_cvmfs_update: yes
  tags:
    - no-restart

- name: Include snapshot plays
  include: _inc_snapshot.yml

- name: Galaxy database
  hosts: galaxywebservers
  remote_user: "{{ galaxy_user }}"
  tags:
    - no-cvmfs
    - no-restart
  vars:
    instance_root: "{{ galaxy_root }}"
    galaxy_config: "{{ galaxy_config_hash }}"
  roles:
    # manage the database
    - role: galaxyproject.galaxy
      galaxy_manage_clone: no
      galaxy_manage_static_setup: no
      galaxy_manage_mutable_setup: no
      galaxy_manage_database: yes
      galaxy_fetch_dependencies: no
      galaxy_manage_errordocs: no
      when: inventory_hostname in groups['galaxymasters']

- name: Include GIE plays
  include: _inc_gie.yml
  tags:
    - no-cvmfs
    - no-restart

- name: Include static content plays
  include: _inc_static.yml
  tags:
    - no-cvmfs
    - no-restart

- name: Include restart plays
  include: _inc_restart.yml
  tags:
    - no-cvmfs
