---

# tools that use $GALAXY_SLOTS

# some tools have explicit mappings (e.g. for Bridges)
galaxy_multicore_tools_exclude:
  - abyss-pe
  - align_families
  - bwa_color_wrapper
  - bowtie_color_wrapper
  - hyphy_absrel
  - hyphy_fel
  - hyphy_gard
  - hyphy_meme
  - megablast_wrapper
  - ncbi_blastn_wrapper
  - ncbi_blastp_wrapper
  - ncbi_blastx_wrapper
  - ncbi_rpsblast_wrapper
  - ncbi_tblastn_wrapper
  - ncbi_tblastx_wrapper
  - rna_star
  - spades
  - star_fusion
  - trinity
  - trinity_psc
  - unicycler

galaxy_multicore_tools: "{{ __galaxy_multicore_tools + __galaxy_multicore_tools_include }}"

# missed by the method below because $GALAXY_SLOTS is in a macro file
__galaxy_multicore_tools_include:
  - deeptools_bam_compare
  - deeptools_bam_coverage
  - deeptools_bam_pe_fragmentsize
  - deeptools_bigwig_compare
  - deeptools_compute_gc_bias
  - deeptools_compute_matrix
  - deeptools_correct_gc_bias
  - deeptools_multi_bam_summary
  - deeptools_multi_bigwig_summary
  - deeptools_plot_coverage
  - deeptools_plot_fingerprint

# generated with:
#     grep -rlI GALAXY_SLOTS /cvmfs/main.galaxyproject.org/{shed,migrated}_tools/toolshed.g2.bx.psu.edu/repos \
#       | xargs grep '<tool.*id=' | sed -Ee 's/^.*id="([^"]+).*$/\1/' | sort | uniq
__galaxy_multicore_tools:
  - abyss-pe
  - align_families
  - alleyoop
  - bg_diamond
  - bg_diamond_makedb
  - bio_hansel
  - bowtie2
  - bowtie_color_wrapper
  - bowtie_wrapper
  - busco
  - bwa
  - bwa_color_wrapper
  - bwa_mem
  - bwameth
  - bwa_wrapper
  - correct_barcodes
  - cuffdiff
  - cufflinks
  - cuffmerge
  - cuffnorm
  - cuffquant
  - cutadapt
  - dada2_assignTaxonomyAddspecies
  - dada2_dada
  - dada2_learnErrors
  - deseq2
  - dexseq
  - disco
  - dunovo
  - egsea
  - exonerate
  - fargene
  - fasterq_dump
  - fastp
  - featurecounts
  - flash
  - freebayes
  - gatk4_mutect2
  - gatk_count_covariates
  - gatk_realigner_target_creator
  - gatk_unified_genotyper
  - gatk_variant_eval
  - gatk_variant_recalibrator
  - gatk_variant_select
  - gubbins
  - heinz
  - hifive
  - hisat2
  - iqtree
  - iuc_pear
  - kallisto_pseudo
  - kallisto_quant
  - kobas_annotate
  - kraken
  - kraken2
  - lastz_wrapper_2
  - lofreq_call
  - lofreq_viterbi
  - maker
  - maxbin2
  - metaspades
  - migmap
  - minimap2
  - mlst
  - mothur_align_seqs
  - mothur_chimera_bellerophon
  - mothur_chimera_ccode
  - mothur_chimera_check
  - mothur_chimera_perseus
  - mothur_chimera_pintail
  - mothur_chimera_slayer
  - mothur_chimera_uchime
  - mothur_chimera_vsearch
  - mothur_chop_seqs
  - mothur_classify_seqs
  - mothur_cluster_split
  - mothur_dist_seqs
  - mothur_dist_shared
  - mothur_filter_seqs
  - mothur_get_communitytype
  - mothur_indicator
  - mothur_make_contigs
  - mothur_metastats
  - mothur_pairwise_seqs
  - mothur_parsimony
  - mothur_pcr_seqs
  - mothur_phylo_diversity
  - mothur_pre_cluster
  - mothur_primer_design
  - mothur_rarefaction_single
  - mothur_screen_seqs
  - mothur_seq_error
  - mothur_shhh_flows
  - mothur_shhh_seqs
  - mothur_summary_seqs
  - mothur_summary_shared
  - mothur_tree_shared
  - mothur_trim_flows
  - mothur_trim_seqs
  - mothur_unifrac_unweighted
  - mothur_unifrac_weighted
  - multigps
  - mummer_nucmer
  - nanoplot
  - nonpareil
  - pilon
  - pipelign
  - plant_tribes_assembly_post_processor
  - plant_tribes_gene_family_aligner
  - plant_tribes_gene_family_classifier
  - plant_tribes_gene_family_phylogeny_builder
  - plant_tribes_kaks_analysis
  - presto_alignsets
  - presto_assemblepairs
  - presto_buildconsensus
  - presto_filterseq
  - presto_maskprimers
  - prokka
  - qualimap_bamqc
  - quast
  - rbc_mafft
  - repeatmasker_wrapper
  - rnaspades
  - rna_star
  - roary
  - sailfish
  - salmon
  - sam_to_bam
  - samtools_slice_bam
  - samtools_sort
  - scpipe
  - seqtk_mergefa
  - seqtk_mergepe
  - shovill
  - sina
  - sklearn_build_pipeline
  - sklearn_ensemble
  - sklearn_model_validation
  - sklearn_numeric_clustering
  - slamdunk
  - snippy
  - socru
  - spades
  - spaln
  - star_fusion
  - stringtie
  - stringtie_merge
  - tag_pileup_frequency
  - tb_profiler_profile
  - td
  - tetyper
  - tophat
  - tophat2
  - tophat_fusion_post
  - transdecoder
  - trimmomatic
  - trinity
  - trinity_align_and_estimate_abundance
  - trinity_psc
  - unicycler
  - valet
  - varscan_somatic
  - velvetoptimiser
