---

# TODO: merge this w/ Test (it is almost identical)

# these vars are consumed in both the job_conf.yml and job_router_conf.yml templates

# this is used in the "tools" section of the job_conf - make sure any you define here don't appear in lists below
galaxy_job_conf_tools:
  #- id: random_lines1
  #  environment: tacc_k8s
  #  handler: k8s
  - id: interactive_tool_jupyter_notebook
    environment: tacc_k8s
    handler: k8s
  - id: interactive_tool_rstudio
    environment: tacc_k8s
    handler: k8s
  - id: interactive_tool_panoply
    environment: tacc_k8s
    handler: k8s
  - id: interactive_tool_phinch
    environment: tacc_k8s
    handler: k8s
  - id: interactive_tool_pavian
    environment: tacc_k8s
    handler: k8s

# tools that use $GALAXY_SLOTS
galaxy_multicore_tools: "{{ (__galaxy_multicore_tools + __galaxy_multicore_tools_include) | difference(__galaxy_multicore_tools_exclude) }}"

# tools that e.g. use globs and should be excluded from running via pulsar until that is addressed
# generated with:
#     tools_dir='/cvmfs/main.galaxyproject.org/shed_tools'
#     find "$tools_dir" -name \*.xml -print0 | xargs -0 grep -l 'work_dir.*\*' | xargs grep '<tool' | grep -o 'id="[^"]*"' | awk -F'"' '{print $2}' | sort | uniq
#
# ideally we'd use full tool versions but this is good enough for now
galaxy_pulsar_incompatible_tools:
  - annotatemyids
  - bacteria_tradis
  - bandage_image
  - egsea
  - iqtree
  - limma_voom
  - macs2_callpeak
  - mothur_biom_info
  - mothur_chimera_ccode
  - mothur_chimera_pintail
  - mothur_chimera_uchime
  - mothur_chimera_vsearch
  - mothur_chop_seqs
  - mothur_classify_rf
  - mothur_classify_seqs
  - mothur_classify_tree
  - mothur_cluster
  - mothur_cluster_classic
  - mothur_cluster_fragments
  - mothur_cluster_split
  - mothur_consensus_seqs
  - mothur_cooccurrence
  - mothur_corr_axes
  - mothur_count_groups
  - mothur_count_seqs
  - mothur_create_database
  - mothur_degap_seqs
  - mothur_deunique_seqs
  - mothur_deunique_tree
  - mothur_dist_seqs
  - mothur_fastq_info
  - mothur_filter_seqs
  - mothur_get_communitytype
  - mothur_get_dists
  - mothur_get_groups
  - mothur_get_lineage
  - mothur_get_mimarkspackage
  - mothur_get_otulabels
  - mothur_get_otus
  - mothur_get_rabund
  - mothur_get_relabund
  - mothur_get_sabund
  - mothur_get_seqs
  - mothur_hcluster
  - mothur_heatmap_sim
  - mothur_homova
  - mothur_indicator
  - mothur_lefse
  - mothur_libshuff
  - mothur_list_seqs
  - mothur_make_contigs
  - mothur_make_fastq
  - mothur_make_group
  - mothur_make_lefse
  - mothur_make_lookup
  - mothur_make_shared
  - mothur_make_sra
  - mothur_mantel
  - mothur_merge_groups
  - mothur_mimarks_attributes
  - mothur_nmds
  - mothur_otu_hierarchy
  - mothur_pairwise_seqs
  - mothur_parsimony
  - mothur_pcoa
  - mothur_pcr_seqs
  - mothur_phylo_diversity
  - mothur_phylotype
  - mothur_pre_cluster
  - mothur_primer_design
  - mothur_remove_dists
  - mothur_remove_groups
  - mothur_remove_lineage
  - mothur_remove_otulabels
  - mothur_remove_otus
  - mothur_remove_rare
  - mothur_reverse_seqs
  - mothur_screen_seqs
  - mothur_sens_spec
  - mothur_seq_error
  - mothur_sffinfo
  - mothur_shhh_flows
  - mothur_shhh_seqs
  - mothur_sort_seqs
  - mothur_split_abund
  - mothur_sub_sample
  - mothur_summary_qual
  - mothur_summary_seqs
  - mothur_summary_shared
  - mothur_summary_single
  - mothur_summary_tax
  - mothur_tree_shared
  - mothur_trim_seqs
  - mothur_unifrac_unweighted
  - mothur_unifrac_weighted
  - mothur_unique_seqs
  - pathview
  - qualimap_bamqc
  - scanpy_plot
  - snpfreqplot
  - tradis_gene_insert_sites
  - velvetoptimiser

# some tools have explicit mappings (e.g. for Bridges)
__galaxy_multicore_tools_exclude:
  # what to do, what to do
  - trinity_psc
  - align_families
  - maker

# missed by the method below because $GALAXY_SLOTS is in a macro file
__galaxy_multicore_tools_include:
  - deeptools_bam_compare
  - deeptools_bam_coverage
  - deeptools_bam_pe_fragmentsize
  - deeptools_bigwig_compare
  - deeptools_compute_gc_bias
  - deeptools_compute_matrix
  - deeptools_correct_gc_bias
  - deeptools_multi_bam_summary
  - deeptools_multi_bigwig_summary
  - deeptools_plot_coverage
  - deeptools_plot_enrichment
  - deeptools_plot_fingerprint
  - hyphy_absrel
  - hyphy_fel
  - hyphy_gard
  - hyphy_meme
  - keras_train_and_eval
  - megablast_wrapper
  - mimodd_align
  - mimodd_varcall
  - model_prediction
  - sklearn_searchcv
  - stacking_ensemble_models
  - umi_tools_dedup
  # manual adds because I'm not running the thing below again
  - deepvariant

# generated with:
#     grep -rlI GALAXY_SLOTS /cvmfs/main.galaxyproject.org/{shed,migrated}_tools/toolshed.g2.bx.psu.edu/repos \
#       | xargs grep '<tool.*id=' | sed -Ee 's/^.*id="([^"]+).*$/\1/' | sort | uniq
#
# don't modify things here, this list is meant to be automatically regenerated. instead, list tools to exclude/include
# in the lists above.
#
__galaxy_multicore_tools:
  - alevin
  - align_families
  - alleyoop
  - antismash
  #- bedtools_bamtobed
  - bellerophon
  - bg_diamond
  - bg_diamond_makedb
  - bg_diamond_view
  - bioext_bealign
  - bio_hansel
  - bowtie_wrapper
  - bwameth
  - bwa_wrapper
  - correct_barcodes
  - ctb_chemfp_butina_clustering
  - ctb_pubchem_download_assays
  - ctb_pubchem_download_as_smiles
  - cuffdiff
  - cufflinks
  - cuffmerge
  - cuffnorm
  - cuffquant
  - cutadapt
  - dada2_assignTaxonomyAddspecies
  - dada2_dada
  - dada2_learnErrors
  - deseq2
  - dexseq
  - disco
  - docking
  - egsea
  - exonerate
  - fargene
  - fastp
  - featurecounts
  - flash
  - freebayes
  - gatk4_mutect2
  - gatk_count_covariates
  - gatk_realigner_target_creator
  - gatk_unified_genotyper
  - gatk_variant_eval
  - gatk_variant_recalibrator
  - gatk_variant_select
  - gmx_em
  - gubbins
  - heinz
  - hhsearch
  - hifive
  - hyphy_relax
  - iqtree
  - iuc_pear
  - ivar_trim
  - jasminesv
  - kallisto_pseudo
  - kallisto_quant
  - kobas_annotate
  - lastz_wrapper_2
  - lofreq_call
  - lofreq_viterbi
  - maker
  - maxbin2
  - maxquant
  - medaka_consensus
  - medaka_consensus_pipeline
  - medaka_variant_pipeline
  - megahit
  - meme_meme
  - meryl
  - metaspades
  - migmap
  - minimap2
  - mlst
  - mothur_align_seqs
  - mothur_chimera_bellerophon
  - mothur_chimera_ccode
  - mothur_chimera_check
  - mothur_chimera_perseus
  - mothur_chimera_pintail
  - mothur_chimera_slayer
  - mothur_chimera_uchime
  - mothur_chimera_vsearch
  - mothur_chop_seqs
  - mothur_classify_seqs
  - mothur_cluster_split
  - mothur_dist_seqs
  - mothur_dist_shared
  - mothur_filter_seqs
  - mothur_get_communitytype
  - mothur_indicator
  - mothur_make_contigs
  - mothur_metastats
  - mothur_pairwise_seqs
  - mothur_parsimony
  - mothur_pcr_seqs
  - mothur_phylo_diversity
  - mothur_pre_cluster
  - mothur_primer_design
  - mothur_rarefaction_single
  - mothur_screen_seqs
  - mothur_seq_error
  - mothur_shhh_flows
  - mothur_shhh_seqs
  - mothur_summary_seqs
  - mothur_summary_shared
  - mothur_tree_shared
  - mothur_trim_flows
  - mothur_trim_seqs
  - mothur_unifrac_unweighted
  - mothur_unifrac_weighted
  - multigps
  - mummer_mummer
  - mummer_nucmer
  - mz_to_sqlite
  - nanoplot
  - nonpareil
  - openbabel_multi_obgrep
  - openbabel_obgrep
  - openbabel_subsearch
  - OpenPepXL
  - orfipy
  - pangolin
  - peptide_shaker
  - pileometh
  - pilon
  - pipelign
  - plant_tribes_assembly_post_processor
  - plant_tribes_gene_family_aligner
  - plant_tribes_gene_family_classifier
  - plant_tribes_gene_family_phylogeny_builder
  - plant_tribes_kaks_analysis
  - presto_alignsets
  - presto_assemblepairs
  - presto_buildconsensus
  - presto_filterseq
  - presto_maskprimers
  - prokka
  - qualimap_bamqc
  - quast
  - racon
  - rapidnj
  - rbc_mafft
  - repeatmasker_wrapper
  - rnaspades
  - roary
  - sailfish
  - salmon
  - sam_to_bam
  - samtools_slice_bam
  - samtools_sort
  - scanpy_remove_confounders
  - scpipe
  - search_gui
  - seqtk_mergefa
  - seqtk_mergepe
  - shovill
  - sina
  - sklearn_build_pipeline
  - sklearn_ensemble
  - sklearn_lightgbm
  - sklearn_model_validation
  - sklearn_numeric_clustering
  - slamdunk
  - smina
  - sniffles
  - snippy
  - socru
  - spaln
  - staramr_search
  - star_fusion
  - stringtie
  - stringtie_merge
  - tag_pileup_frequency
  - tb_profiler_profile
  - td
  - tetyper
  - tophat
  - tophat2
  - tophat_fusion_post
  - transdecoder
  - trimmomatic
  - trinity_align_and_estimate_abundance
  - trinity_psc
  - valet
  - varscan_somatic
  - velveth
  - velvetoptimiser
