---

## these vars are defined in vault.yml
#
# used by: galaxyproject.galaxy (templating job_conf.xml)
galaxy_job_conf_amqp_url: "{{ vault_galaxy_job_conf_amqp_url }}"

## used by: galaxyproject.galaxy and the play itself
galaxy_system_group: G-803372

# FIXME: "{{ galaxy_remote_users.privsep | default(omit) }}" is blanking remote_user on the play. I set the below option
# to workaround but this needs to be fixed in galaxyproject.galaxy, nothing should be breaking when privsep mode is not
# enabled in the role
galaxy_remote_users:
  privsep: "{{ galaxy_privileged_user }}"
  errdocs: "{{ galaxy_privileged_user }}"
  galaxy: "{{ galaxy_user }}"

# FIXME: Same thing, the become log checks if galaxy_become_users.privsep is set and yet in the defaults we cause it to
# be always set
galaxy_become_users: {}

# used by the supervisor template
galaxy_uwsgi_config_file: "{{ galaxy_config_dir }}/uwsgi.ini"

galaxy_server_dir: /cvmfs/{{ galaxy_cvmfs_repo }}/galaxy
galaxy_shed_tools_dir: /cvmfs/{{ galaxy_cvmfs_repo }}/shed_tools
galaxy_shed_tool_conf_file: /cvmfs/{{ galaxy_cvmfs_repo }}/config/shed_tool_conf.xml

#galaxy_venv_dir defined in all.yml
galaxy_config_dir: "{{ galaxy_root }}/config"
galaxy_config_file: "{{ galaxy_config_dir }}/galaxy.ini"
galaxy_mutable_data_dir: "{{ galaxy_root }}/var"
galaxy_mutable_config_dir: "/galaxy-repl/{{ galaxy_instance_codename }}/config"
# these don't need to be set if the galaxyproject.galaxy layout tasks run, but usegalaxy_backup uses
# galaxyproject.galaxy's defaults without running the layout tasks and breaks if they are unset
galaxy_cache_dir: "{{ galaxy_mutable_data_dir }}/cache"

galaxy_admin_email_to: galaxy-lab@bx.psu.edu

## used by: galaxyproject.galaxy
galaxy_errordocs_dest: "{{ nginx_srv }}/{{ galaxy_instance_hostname }}/error"
galaxy_errordocs_502_message: |
  You are seeing this message because a request to Galaxy timed out or was refused. This may be a temporary issue which
  could be resolved by retrying the operation you were performing. If you receive this message repeatedly or for an
  extended amount of time, please report it to the Galaxy Team at
  <a href='mailto:galaxy-bugs@galaxyproject.org'>galaxy-bugs@galaxyproject.org</a>
  with details on what you were trying to do and the URL in the address bar. More information on the current state of
  Galaxy services may be available on the
  <a href="https://status.galaxyproject.org/">Galaxy status page</a>
  or the
  <a href="https://twitter.com/galaxyproject">@galaxyproject Twitter feed</a>.

## used by: usegalaxy_privileged
usegalaxy_nagios_tools:
  - echo_main_w1_handler0
  - echo_main_w1_handler1
  - echo_main_w1_handler2
  - echo_main_w2_handler0
  - echo_main_w2_handler1
  - echo_main_w2_handler2
  - echo_main_cluster
  - echo_main_jetstream_iu
  - echo_main_jetstream_tacc
  - echo_main_stampede
  - echo_main_bridges


## used by usegalaxy_privileged and templating job_conf.xml
galaxy_dynamic_rule_dir: "{{ galaxy_root }}/dynamic_rules"

galaxy_pgcleanup_actions:
  - delete_userless_histories
  - delete_exported_histories
  - purge_deleted_users
  - purge_deleted_histories
  - purge_deleted_hdas
  - purge_historyless_hdas
  # Might want to announce this before you do it
  #- purge_error_hdas
  - purge_hdas_of_purged_histories
  - delete_datasets
  - purge_datasets

## used by: usegalaxy_admin
galaxy_log_archive_dir: /galaxy-repl/{{ galaxy_instance_codename }}/backup/log


# galaxy_config hash moved to group_vars/all/galaxy_config_vars.yml

# specifies config files to copy from the playbook
galaxy_config_files:
  - src: files/galaxy/config/tool_data_table_conf.xml
    dest: "{{ galaxy_config_dir }}/tool_data_table_conf.xml"
  - src: files/galaxy/config/tool_conf.xml
    dest: "{{ galaxy_config_dir }}/tool_conf.xml"
  - src: files/galaxy/config/nagios_tool_conf.xml
    dest: "{{ galaxy_config_dir }}/nagios_tool_conf.xml"
  - src: files/galaxy/config/object_store_conf.xml
    dest: "{{ galaxy_config['app:main']['object_store_config_file'] }}"
  - src: files/galaxy/config/data_manager_conf.xml
    dest: "{{ galaxy_config['app:main']['data_manager_config_file'] }}"
  - src: files/galaxy/config/tool_sheds_conf.xml
    dest: "{{ galaxy_config['app:main']['tool_sheds_config_file'] }}"
  - src: files/galaxy/config/job_metrics_conf.xml
    dest: "{{ galaxy_config['app:main']['job_metrics_config_file'] }}"
  - src: files/galaxy/config/job_resource_params_conf.xml
    dest: "{{ galaxy_config['app:main']['job_resource_params_file'] }}"
  - src: files/galaxy/config/dependency_resolvers_conf.xml
    dest: "{{ galaxy_config['app:main']['dependency_resolvers_config_file'] }}"
  - src: files/galaxy/config/pulsar_stampede_actions.yml
    dest: "{{ galaxy_config_dir }}/pulsar_stampede_actions.yml"
  - src: files/galaxy/config/pulsar_bridges_actions.yml
    dest: "{{ galaxy_config_dir }}/pulsar_bridges_actions.yml"
  - src: files/galaxy/config/pulsar_jetstream.yml
    dest: "{{ galaxy_config_dir }}/pulsar_jetstream.yml"
  - src: files/galaxy/config/pulsar_jetstream_actions.yml
    dest: "{{ galaxy_config_dir }}/pulsar_jetstream_actions.yml"
  - src: files/galaxy/config/disposable_email_blacklist.conf
    dest: "{{ galaxy_config['app:main']['blacklist_file'] }}"
  - src: files/galaxy/config/workflow_schedulers_conf.xml
    dest: "{{ galaxy_config_dir }}/workflow_schedulers_conf.xml"

# specifies config files to template from the playbook
galaxy_config_templates:
  - src: templates/galaxy/config/job_conf.xml.j2
    dest: "{{ galaxy_config_dir }}/job_conf.xml"
  - src: templates/galaxy/config/build_sites.yml.j2
    dest: "{{ galaxy_config['app:main']['build_sites_config_file'] }}"
  #- src: templates/galaxy/config/reports.ini.j2
  #  dest: "{{ galaxy_config_dir }}/reports.ini"
  - src: templates/galaxy/config/uwsgi.ini.j2
    dest: "{{ galaxy_config_dir }}/uwsgi.ini"
