---

## these vars are defined in vault.yml
#
# used by: galaxyproject.pulsar (templating server.ini)
pulsar_message_queue_url: "{{ vault_pulsar_message_queue_url }}"


## used by: other vars in this vars file
galaxy_instance_hostname: usegalaxy.org


## used by: galaxyproject.pulsar
#pulsar_privsep_user: xcgalaxy
#pulsar_package_name: "git+https://github.com/galaxyproject/pulsar.git@ff2208baf43f6afb9770316e474d15f69c9fd4f9"
#pulsar_package_name: "git+https://github.com/galaxyproject/pulsar.git@2bfc784301c12634b6026113473767f1e3f4d017"
#pulsar_package_name: "git+https://github.com/natefoo/pulsar.git@stampede-parrot"
pulsar_package_version: "0.13.0"
pulsar_venv_dir: "{{ pulsar_root }}/venv"
pulsar_config_dir: "{{ pulsar_root }}/config"
pulsar_optional_dependencies:
  # git+pip pulsar install uses 'state: forcereinstall' which can upgrade galaxy-lib to a version not compatible with
  # the specified pulsar version, this downgrades it if necessary.
  #- galaxy-lib==18.5.13
  # actual optional things
  - pyOpenSSL
  - pycurl
  #- uwsgi
  - drmaa
  - kombu
  - requests
  #- poster
  #- psutil

pulsar_systemd_environment:
  - "GALAXY_VIRTUAL_ENV=/cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/venv"
