---

paths:
  - path: /galaxy/data
    path_types: unstructured
    action: rewrite
    source_directory: /galaxy/data
    destination_directory: /work/galaxy/data
  # until we clean the working directory prior to resubmissions, this is necessary to prevent cufflinks from failing.
  - path: "**/ref.fa*"
    match_types: glob
    path_types: workdir
    action: none
  - path: "**/ref.fa*"
    match_types: glob
    path_types: output_workdir
    action: none
