---

- name: Install admin scripts
  template:
    src: "{{ item }}.j2"
    dest: "{{ galaxy_root }}/bin/{{ item }}"
    mode: "0555"
  with_items:
    - "archive_logs.sh"
    - "cleanup_datasets.sh"
