---

# This is on NFS so it should only be done once
- name: Check for tool panel layout existence
  stat:
    path: "{{ galaxy_config[galaxy_app_config_section].integrated_tool_panel_config }}"
  register: tool_panel_stat_out
  run_once: true

- name: Push tool panel layout from playbook if missing
  synchronize:
    mode: push
    src: "files/galaxy/var/integrated_tool_panel.xml"
    dest: "{{ galaxy_config[galaxy_app_config_section].integrated_tool_panel_config }}"
  when: not tool_panel_stat_out.stat.exists
  run_once: true

- name: Create ~/bin and ~/etc
  file:
    path: ~/{{ item }}
    state: directory
  with_items:
    - bin
    - etc

- name: Distribute ~/bin files
  template:
    src: "{{ item }}.j2"
    dest: ~/bin/{{ item }}
    mode: "0555"
  with_items:
    - galaxyctl
