---

# distribute mutable configs to non-masters (this is not in the public role because I doubt anyone else is doing it)
# the file must exist in the (local) destination, I can't get synchronize to create it if it does not exist.
- name: Fetch mutable configs from master host
  synchronize: mode=pull src={{ item.dest }} dest=files/galaxy/{{ galaxy_instance_hostname }}/var/{{ item.dest | basename }}
  with_items: galaxy_mutable_configs
  when: inventory_hostname in groups['galaxymasters']

- name: Fetch tool panel layout
  synchronize: mode=pull src={{ galaxy_mutable_config_dir }}/integrated_tool_panel.xml dest=files/galaxy/{{ galaxy_instance_hostname }}/var/integrated_tool_panel.xml
  when: inventory_hostname in groups['galaxymasters']

- name: Distribute mutable configs to slave hosts
  synchronize: src=files/galaxy/{{ galaxy_instance_hostname }}/var/{{ item.dest | basename }} dest={{ item.dest }}
  with_items: galaxy_mutable_configs
  when: inventory_hostname not in groups['galaxymasters']

- name: Distribute tool panel layout
  synchronize: src=files/galaxy/{{ galaxy_instance_hostname }}/var/integrated_tool_panel.xml  dest={{ galaxy_mutable_config_dir }}/integrated_tool_panel.xml
  when: inventory_hostname not in groups['galaxymasters']
