---

- name: Install virtualenv
  yum: name=python-virtualenv
  when: ansible_os_family == "RedHat"

- name: Install supervisor
  pip: name=supervisor virtualenv={{ supervisord_venv_dir }} extra_args=--pre

- name: Create local supervisor directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ supervisord_conf_dir }}"
    - /var/log/supervisord

- name: Install supervisord.conf
  template: src=supervisord.conf.j2 dest={{ supervisord_conf_path }}
  notify:
    - restart supervisord

# These are split into two lists so host configs need not override group
# (that's Ansible group, not supervisor group) config lists.
- name: Install group supervisor configs for this host
  template: src=templates/supervisor/{{ item }}.j2 dest={{ supervisord_conf_dir }}/{{ item }}
  with_items: supervisord_group_configs
  notify:
    - update supervisord

- name: Install host supervisor configs for this host
  template: src=templates/supervisor/{{ item }}.j2 dest={{ supervisord_conf_dir }}/{{ item }}
  with_items: supervisord_host_configs
  notify:
    - update supervisord

- name: Detect systemd
  command: /usr/bin/pgrep -u root systemd
  register: systemd
  failed_when: False
  changed_when: False

- name: Install init script (SysV init)
  template: src={{ ansible_distribution | lower }}.init.j2 dest=/etc/init.d/supervisor mode=0755
  when: systemd.rc != 0

- name: Install init script (systemd)
  template: src=systemd.init.j2 dest=/etc/systemd/system/supervisor.service mode=0755
  when: systemd.rc == 0

- name: Enable and start supervisord
  service: name=supervisor enabled=yes state=started
