---

galaxy_host_codename: main_w4
galaxy_enable_celery_beat: false

gravity_handlers:
  main_w4_handler:
    name_template: "{name}{process}"
    processes: 3
    pools:
      - job-handlers
  main_w4_workflow_scheduler:
    name_template: "{name}{process}"
    processes: 1
    pools:
      - workflow-schedulers
