---

galaxy_host_codename: main_w3
galaxy_enable_celery_beat: true

gravity_handlers:
  main_w3_handler:
    name_template: "{name}{process}"
    processes: 3
    pools:
      - job-handlers
    environment:
      HDF5_USE_FILE_LOCKING: "FALSE"
  main_w3_workflow_scheduler:
    name_template: "{name}{process}"
    processes: 1
    pools:
      - workflow-schedulers
    environment:
      HDF5_USE_FILE_LOCKING: "FALSE"
