---

# FIXME: duplication from galaxyservers

galaxy_base_welcome_names:
  - usegalaxy.org
  - galaxy-main.usegalaxy.org
  - galaxy-main1.usegalaxy.org
  - galaxy-main2.usegalaxy.org
  - galaxy-main3.usegalaxy.org
  - galaxy-main4.usegalaxy.org

galaxy_layout: root-dir
galaxy_errordocs_dest: /srv/nginx/{{ galaxy_instance_hostname }}/error
