---
#
# WARNING: this is shared by both Test and Main
#

_bridges_home_root: "/home/xcgalaxy/{{ galaxy_instance_codename }}"
_bridges_pylon5_root: "/pylon5/mc48nsp/xcgalaxy/{{ galaxy_instance_codename }}"

pulsar_root: "{{ _bridges_home_root }}/pulsar"
galaxy_root: "{{ _bridges_pylon5_root }}/galaxy"

galaxy_user: xcgalaxy
pip_virtualenv_command: "/home/xcgalaxy/virtualenv/bin/virtualenv"

pulsar_drmaa_library_path: "{{ _bridges_home_root }}/slurm-drmaa/lib/libdrmaa.so"

pulsar_yaml_config:
  staging_directory: "{{ _bridges_pylon5_root }}/staging"
  persistence_directory: "{{ pulsar_root }}/var"
  tool_dependency_dir: "{{ _bridges_home_root }}/deps"
  conda_prefix: "/pylon5/mc48nsp/xcgalaxy/conda"
  job_metrics_config_file: "{{ pulsar_config_dir }}/job_metrics_conf.xml"
  message_queue_url: "{{ pulsar_message_queue_url }}"
  dependency_resolvers_config_file: "{{ pulsar_config_dir }}/dependency_resolvers_conf.xml"
  maximum_stream_size: 8388608  # 8 MB
  amqp_acknowledge: True
  amqp_ack_republish_time: 180
  amqp_publish_retry: True
  amqp_publish_retry_max_retries: 5
  amqp_publish_retry_interval_start: 10
  amqp_publish_retry_interval_step: 10
  amqp_publish_retry_interval_max: 60
  managers:
    bridges:
      type: queued_drmaa
      preprocess_action_max_retries: 10
      preprocess_action_interval_start: 2
      preprocess_action_interval_step: 2
      preprocess_action_interval_max: 60
      postprocess_action_max_retries: 20
      postprocess_action_interval_start: 2
      postprocess_action_interval_step: 4
      postprocess_action_interval_max: 120
      min_polling_interval: 15
    bridges_nagios:
      type: queued_python
      min_polling_interval: 5

pulsar_install_environments:
  pycurl:
    PYCURL_SSL_LIBRARY: "openssl"

host_files:
  - src: files/pulsar/config/bridges_dependency_resolvers_conf.xml
    dest: "{{ pulsar_config_dir }}/dependency_resolvers_conf.xml"
