---
#
# WARNING: this is shared by both Test and Main
#

# FIXME:
#   - conda installed by hand
#   - __python@3.8 conda-forge env installed by hand
#   - supervisor configured by hand
#   - parrot installed by hand in ~xcgalaxy
#   - CVMFS keys installed by hand in ~xcgalaxy
#   - no stratum1 failover for parrot, not sure if it's possible
#   - running a branch of pulsar with a hardcoded parrot wrapper

_stampede_work_root: "/work/03166/xcgalaxy/stampede2"
_stampede_scratch_root: "/scratch/03166/xcgalaxy"
_stampede_instance_root: "{{ _stampede_work_root }}/{{ galaxy_instance_codename }}"
_stampede_galaxy_root: "/cvmfs/{{ galaxy_cvmfs_repo }}/galaxy"

# Isn't this what conda's special virtualenv is supposed to fix?
#host_links:
#  - src: "{{ _stampede_scratch_root }}/conda/envs/_pulsar_/lib/libffi.so"
#    path: "{{ _stampede_instance_root }}/pulsar/venv/lib/libffi.so"
#  - src: "{{ _stampede_scratch_root }}/conda/envs/_pulsar_/lib/libffi.so.7"
#    path: "{{ _stampede_instance_root }}/pulsar/venv/lib/libffi.so.7"
#  - src: "{{ _stampede_scratch_root }}/conda/envs/_pulsar_/lib/libssl.so"
#    path: "{{ _stampede_instance_root }}/pulsar/venv/lib/libssl.so"
#  - src: "{{ _stampede_scratch_root }}/conda/envs/_pulsar_/lib/libssl.so.1.1"
#    path: "{{ _stampede_instance_root }}/pulsar/venv/lib/libssl.so.1.1"
#  - src: "{{ _stampede_scratch_root }}/conda/envs/_pulsar_/lib/libcrypto.so"
#    path: "{{ _stampede_instance_root }}/pulsar/venv/lib/libcrypto.so"
#  - src: "{{ _stampede_scratch_root }}/conda/envs/_pulsar_/lib/libcrypto.so.1.1"
#    path: "{{ _stampede_instance_root }}/pulsar/venv/lib/libcrypto.so.1.1"

host_directories:
  - path: "{{ pulsar_root }}/log"
    mode: "0750"

pulsar_root: "{{ _stampede_instance_root }}/pulsar"
#galaxy_root: not required

# Attempt to chown fails, let it create an empty dir instead
#pulsar_dependencies_dir: "/cvmfs/{{ galaxy_cvmfs_repo }}/deps"
_pulsar_dependencies_dir: "/cvmfs/{{ galaxy_cvmfs_repo }}/deps"
pulsar_persistence_dir: "{{ pulsar_root }}/var/persisted_data"
pulsar_staging_dir: "{{ _stampede_scratch_root }}/{{ galaxy_instance_codename }}/staging"

galaxy_user: xcgalaxy
pulsar_privsep_user: "{{ galaxy_user }}"
# Override group_vars version
pulsar_package_name: "git+https://github.com/natefoo/pulsar.git@stampede-parrot"
pip_virtualenv_command: "{{ _stampede_work_root }}/conda/envs/__python@3.8/bin/python3 -m venv"
pip_extra_args: "--index-url https://wheels.galaxyproject.org/ --extra-index-url https://pypi.org/simple"

pulsar_drmaa_library_path: "{{ _stampede_instance_root }}/slurm-drmaa/lib/libdrmaa.so"

pulsar_dependency_resolvers:
  - name: conda
    args:
      - name: prefix
        value: "{{ _pulsar_dependencies_dir }}/_conda"
  - name: conda
    args:
      - name: prefix
        value: "{{ _stampede_scratch_root }}/conda"
      - name: auto_install
        value: "true"
      - name: auto_init
        value: "true"
  - name: tool_shed_packages
  - name: galaxy_packages

pulsar_job_metrics_plugins:
  - name: core
  - name: cpuinfo
    args:
      - name: verbose
        value: "true"
  - name: meminfo
  - name: uname
  - name: cgroup

pulsar_yaml_config:
  staging_directory: "{{ pulsar_staging_dir }}"
  persistence_directory: "{{ pulsar_persistence_dir }}"
  tool_dependency_dir: "{{ _pulsar_dependencies_dir }}"
  job_metrics_config_file: "{{ pulsar_config_dir }}/job_metrics_conf.xml"
  message_queue_url: "{{ pulsar_message_queue_url }}"
  dependency_resolvers_config_file: "{{ pulsar_config_dir }}/dependency_resolvers_conf.xml"
  maximum_stream_size: 8388608  # 8 MB
  amqp_acknowledge: True
  amqp_ack_republish_time: 180
  amqp_publish_retry: True
  amqp_publish_retry_max_retries: 5
  amqp_publish_retry_interval_start: 10
  amqp_publish_retry_interval_step: 10
  amqp_publish_retry_interval_max: 60
  managers:
    stampede:
      type: queued_drmaa
      preprocess_action_max_retries: 10
      preprocess_action_interval_start: 2
      preprocess_action_interval_step: 2
      preprocess_action_interval_max: 60
      postprocess_action_max_retries: 20
      postprocess_action_interval_start: 2
      postprocess_action_interval_step: 4
      postprocess_action_interval_max: 120
      min_polling_interval: 15
    stampede_nagios:
      type: queued_python
      min_polling_interval: 5

#pulsar_install_environments:
#  pyOpenSSL:
#    PKG_CONFIG_PATH: "{{ _stampede_work_root }}/libffi/lib64/pkgconfig"
#    CFLAGS: "-I{{ _stampede_work_root }}/openssl/include"
#    LDFLAGS: "-L{{ _stampede_work_root }}/openssl/lib"
#  pycurl:
#    PYCURL_SSL_LIBRARY: "nss"
