---
#
# WARNING: this is shared by both Test and Main
#

# FIXME:
#   - slurm-drmaa installed by hand

_expanse_home_root: "/home/xgalaxy"
_expanse_project_root: "/expanse/lustre/projects/pen160/xgalaxy"
_expanse_scratch_root: "/expanse/lustre/scratch/xgalaxy/temp_project"
_expanse_instance_root: "{{ _expanse_project_root }}/{{ galaxy_instance_codename }}"

host_directories:
  - path: "{{ _expanse_home_root }}/bin"
    mode: "0755"
  - path: "{{ _expanse_home_root }}/etc"
    mode: "0750"
  - path: "{{ pulsar_root }}/log"
    mode: "0750"

host_files:
  - src: "files/pulsar/tmpwatch.el7"
    dest: "{{ _expanse_home_root }}/bin/tmpwatch"
    mode: "0755"

host_templates:
  - src: "templates/pulsar/expanse-supervisord-launch.sh.j2"
    dest: "{{ _expanse_home_root }}/bin/supervisord-launch.sh"
    mode: "0755"

# FIXME: User crontabs disabled on Expanse
#host_crontabs:
#  - id: "pulsar-clean-{{ galaxy_instance_codename }}-scratch"
#    use_cron_file: false
#    minute: "0"
#    hour: "*/6"
#    job: "{{ _expanse_home_root }}/bin/tmpwatch -v --all --mtime --dirmtime 7d '{{ pulsar_staging_dir }}' >> '{{ pulsar_root }}/log/cleanup.log'"

miniconda_prefix: "{{ _expanse_project_root }}/conda"
miniconda_channels:
  - conda-forge
  - defaults
miniconda_conda_environments:
  __python@3.9:
    packages:
      - python=3.9
  __curl@7.71:
    packages:
      - curl=7.71

supervisord_install: virtualenv-unprivileged
supervisord_prefix: "{{ _expanse_project_root }}/supervisor"
supervisord_conf_path: "{{ supervisord_prefix }}/etc/supervisord.conf"
supervisord_conf_dir: "{{ supervisord_prefix }}/etc/supervisord.d"
supervisord_log_dir: "{{ supervisord_prefix }}/var/log"
supervisord_run_dir: "{{ supervisord_prefix }}/var/run"
host_supervisor_configs:
  - "{{ galaxy_instance_codename }}_pulsar"

# FIXME: User crontabs disabled on Expanse
# User crontabs disabled on Expanse
#supervisord_unprivileged_command: "{ date; pgrep -u {{ ansible_user }} supervisord || /bin/bash '{{ _expanse_home_root }}/bin/supervisord-launch.sh'; } >> {{ supervisord_log_dir }}/supervisord-launch.log 2>&1"
supervisord_unprivileged_command: null

pulsar_root: "{{ _expanse_instance_root }}/pulsar"
pulsar_restart_handler_name: supervisor restart pulsar
pulsar_persistence_dir: "{{ _expanse_scratch_root }}/{{ galaxy_instance_codename }}/pulsar/var"
pulsar_staging_dir: "{{ _expanse_scratch_root }}/{{ galaxy_instance_codename }}/staging"
#galaxy_root: not required

pulsar_env:
  PATH: "{{ miniconda_prefix }}/envs/__curl@7.71/bin:/cm/shared/apps/slurm/current/sbin:/cm/shared/apps/slurm/current/bin:/cm/shared/apps/spack/cpu/opt/spack/linux-centos8-zen/gcc-8.3.1/gcc-10.2.0-n7su7jf54rc7l2ozegds5xksy6qhrjin/bin:/home/xgalaxy/.local/bin:/home/xgalaxy/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/dell/srvadmin/bin"


pulsar_supervisor_env:
  - PATH="{{ pulsar_venv_dir }}/bin:/cm/shared/apps/slurm/current/bin:%(ENV_PATH)s"
  - LD_LIBRARY_PATH="{{ miniconda_prefix }}/envs/__curl@7.71/lib:/cm/shared/apps/slurm/current/lib64"
  - SLURM_CONF="{{ _expanse_home_root }}/etc/slurm.conf"

galaxy_user: xgalaxy
pulsar_privsep_user: "{{ galaxy_user }}"
pip_virtualenv_command: "{{ miniconda_prefix }}/envs/__python@3.9/bin/python3 -m venv"
pip_extra_args: "--index-url https://wheels.galaxyproject.org/ --extra-index-url https://pypi.org/simple"

pulsar_pycurl_ssl_library: openssl
pulsar_drmaa_library_path: "{{ _expanse_instance_root }}/slurm-drmaa/lib/libdrmaa.so"

pulsar_job_metrics_plugins:
  - type: core
  - type: cpuinfo
    verbose: true
  - type: meminfo
  - type: uname
  - type: cgroup

pulsar_yaml_config:
  staging_directory: "{{ pulsar_staging_dir }}"
  persistence_directory: "{{ pulsar_persistence_dir }}"
  message_queue_url: "{{ pulsar_message_queue_url }}"
  maximum_stream_size: 8388608  # 8 MB
  amqp_acknowledge: True
  amqp_ack_republish_time: 180
  amqp_publish_retry: True
  amqp_publish_retry_max_retries: 5
  amqp_publish_retry_interval_start: 10
  amqp_publish_retry_interval_step: 10
  amqp_publish_retry_interval_max: 60
  dependency_resolution:
    resolvers:
      - type: conda
        prefix: "{{ miniconda_prefix }}"
        auto_init: false
        auto_install: true
  managers:
    expanse:
      type: queued_drmaa
      preprocess_action_max_retries: 10
      preprocess_action_interval_start: 2
      preprocess_action_interval_step: 2
      preprocess_action_interval_max: 60
      postprocess_action_max_retries: 10
      postprocess_action_interval_start: 2
      postprocess_action_interval_step: 2
      postprocess_action_interval_max: 60
      min_polling_interval: 15
