---
#
# WARNING: this is shared by both Test and Main
#

_stampede_work_root: "/work/galaxy/{{ galaxy_instance_codename }}"

pulsar_root: "{{ _stampede_work_root }}/pulsar"
galaxy_root: "{{ _stampede_work_root }}/galaxy"

galaxy_user: xcgalaxy
pip_virtualenv_command: "{{ _stampede_work_root }}/python/bin/virtualenv"

pulsar_drmaa_library_path: "{{ _stampede_work_root }}/slurm-drmaa/lib/libdrmaa.so"

pulsar_yaml_config:
  staging_directory: "/scratch/03166/xcgalaxy/{{ galaxy_instance_codename }}/staging"
  persistence_directory: "{{ pulsar_root }}/var/persisted_data"
  tool_dependency_dir: "{{ _stampede_work_root }}/deps"
  job_metrics_config_file: "{{ pulsar_config_dir }}/job_metrics_conf.xml"
  message_queue_url: "{{ pulsar_message_queue_url }}"
  dependency_resolvers_config_file: "{{ pulsar_config_dir }}/dependency_resolvers_conf.xml"
  maximum_stream_size: 8388608  # 8 MB
  amqp_acknowledge: True
  amqp_ack_republish_time: 180
  amqp_publish_retry: True
  amqp_publish_retry_max_retries: 5
  amqp_publish_retry_interval_start: 10
  amqp_publish_retry_interval_step: 10
  amqp_publish_retry_interval_max: 60
  managers:
    stampede:
      type: queued_drmaa
      preprocess_action_max_retries: 10
      preprocess_action_interval_start: 2
      preprocess_action_interval_step: 2
      preprocess_action_interval_max: 60
      postprocess_action_max_retries: 20
      postprocess_action_interval_start: 2
      postprocess_action_interval_step: 4
      postprocess_action_interval_max: 120
      min_polling_interval: 15
    stampede_nagios:
      type: queued_python
      min_polling_interval: 5

pulsar_install_environments:
  pyOpenSSL:
    PKG_CONFIG_PATH: "{{ _stampede_work_root }}/libffi/lib64/pkgconfig"
    CFLAGS: "-I{{ _stampede_work_root }}/openssl/include"
    LDFLAGS: "-L{{ _stampede_work_root }}/openssl/lib"
  pycurl:
    PYCURL_SSL_LIBRARY: "nss"

host_files:
  - src: files/pulsar/config/stampede_dependency_resolvers_conf.xml
    dest: "{{ pulsar_config_dir }}/dependency_resolvers_conf.xml"
