---
#
# WARNING: this is shared by both Test and Main
#

# FIXME:
#   - slurm-drmaa installed by hand

# No FUSE on Rockfish =(

_rockfish_home_root: "/home/galaxy"
_rockfish_nfs_root: "/data/nekrut/galaxy"
_rockfish_scratch_root: "/scratch4/nekrut/galaxy"
_rockfish_instance_root: "{{ _rockfish_nfs_root }}/{{ galaxy_instance_codename }}"

host_directories:
  - path: "{{ _rockfish_home_root }}/bin"
    mode: "0755"
  - path: "{{ _rockfish_home_root }}/etc"
    mode: "0750"
  - path: "{{ pulsar_root }}/log"
    mode: "0750"

host_files:
  - src: "files/pulsar/el8/tmpwatch"
    dest: "{{ _rockfish_home_root }}/bin/tmpwatch"
    mode: "0755"

host_templates:
  - src: "templates/pulsar/rockfish-supervisord-launch.sh.j2"
    dest: "{{ _rockfish_home_root }}/bin/supervisord-launch.sh"
    mode: "0755"

host_crontabs:
  - id: "pulsar-clean-{{ galaxy_instance_codename }}-scratch"
    use_cron_file: false
    minute: "0"
    hour: "*/6"
    job: "{{ _rockfish_home_root }}/bin/tmpwatch --all --mtime --dirmtime 7d {{ pulsar_staging_dir }}"
  - id: "pulsar-clean-{{ galaxy_instance_codename }}-amqp-consume"
    use_cron_file: false
    minute: "15"
    hour: "2"
    job: "{{ _rockfish_home_root }}/bin/tmpwatch 7d {{ pulsar_persistence_dir }}/amqp_ack-rockfish/consume"
  - id: "pulsar-clean-cvmfs-cache"
    use_cron_file: false
    minute: "30"
    hour: "*/6"
    job: "{{ _rockfish_home_root }}/bin/tmpwatch 4d {{ _rockfish_scratch_root }}/cvmfs_cache"

miniconda_prefix: "{{ _rockfish_nfs_root }}/conda"
miniconda_channels:
  - conda-forge
  - defaults
miniconda_conda_environments:
  __python@3.9:
    packages:
      - python=3.9
  __curl@7.71:
    packages:
      - curl=7.71

supervisord_install: virtualenv-unprivileged
supervisord_prefix: "{{ _rockfish_nfs_root }}/supervisor"
supervisord_conf_path: "{{ supervisord_prefix }}/etc/supervisord.conf"
supervisord_conf_dir: "{{ supervisord_prefix }}/etc/supervisord.d"
supervisord_log_dir: "{{ supervisord_prefix }}/var/log"
supervisord_run_dir: "{{ supervisord_prefix }}/var/run"
host_supervisor_configs:
  - "{{ galaxy_instance_codename }}_pulsar"

supervisord_unprivileged_command: "{ date; pgrep -u {{ ansible_user }} supervisord || /bin/bash '{{ _rockfish_home_root }}/bin/supervisord-launch.sh'; } >> {{ supervisord_log_dir }}/supervisord-launch.log 2>&1"

pulsar_root: "{{ _rockfish_instance_root }}/pulsar"
pulsar_restart_handler_name: supervisor restart pulsar
pulsar_persistence_dir: "{{ _rockfish_scratch_root }}/{{ galaxy_instance_codename }}/pulsar/var"
pulsar_staging_dir: "{{ _rockfish_scratch_root }}/{{ galaxy_instance_codename }}/staging"
#galaxy_root: not required

pulsar_env:
  PATH: "{{ miniconda_prefix }}/envs/__curl@7.71/bin:/cm/shared/apps/slurm/current/sbin:/cm/shared/apps/slurm/current/bin:/cm/shared/apps/spack/cpu/opt/spack/linux-centos8-zen/gcc-8.3.1/gcc-10.2.0-n7su7jf54rc7l2ozegds5xksy6qhrjin/bin:/home/xgalaxy/.local/bin:/home/xgalaxy/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/dell/srvadmin/bin"
  #/home/galaxy/.local/bin:/home/galaxy/bin:/data/apps/linux-centos8-cascadelake/gcc-9.3.0/git-2.28.0-uh6lz2zi2m3rwkfujclkz2qrtm6awu6s/bin:/data/apps/helpers:/cm/shared/apps/slurm/current/sbin:/cm/shared/apps/slurm/current/bin:/data/apps/linux-centos8-cascadelake/gcc-9.3.0/openmpi-3.1.6-rk3nyoehbq3pke4zy4hn7unns3ujtutx/bin:/data/apps/linux-centos8-cascadelake/gcc-9.2.0/gcc-9.3.0-bnvby67rgbqevwsd264rgz44xucnkhpm/bin:/usr/lpp/mmfs/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin

pulsar_supervisor_env:
  - PATH="{{ pulsar_venv_dir }}/bin:/cm/shared/apps/slurm/current/bin:%(ENV_PATH)s"
  - LD_LIBRARY_PATH="{{ miniconda_prefix }}/envs/__curl@7.71/lib:/cm/shared/apps/slurm/current/lib64"
  - SLURM_CONF="{{ _rockfish_home_root }}/etc/slurm.conf"

galaxy_user: galaxy
pulsar_privsep_user: "{{ galaxy_user }}"
pip_virtualenv_command: "{{ miniconda_prefix }}/envs/__python@3.9/bin/python3 -m venv"
pip_extra_args: "--index-url https://wheels.galaxyproject.org/ --extra-index-url https://pypi.org/simple"

pulsar_pycurl_ssl_library: openssl
pulsar_drmaa_library_path: "{{ _rockfish_instance_root }}/slurm-drmaa/lib/libdrmaa.so"

pulsar_job_metrics_plugins:
  - type: core
  - type: cpuinfo
    verbose: true
  - type: meminfo
  - type: uname
  - type: cgroup

pulsar_yaml_config:
  staging_directory: "{{ pulsar_staging_dir }}"
  persistence_directory: "{{ pulsar_persistence_dir }}"
  message_queue_url: "{{ pulsar_message_queue_url }}"
  maximum_stream_size: 8388608  # 8 MB
  amqp_acknowledge: True
  amqp_ack_republish_time: 180
  amqp_publish_retry: True
  amqp_publish_retry_max_retries: 5
  amqp_publish_retry_interval_start: 10
  amqp_publish_retry_interval_step: 10
  amqp_publish_retry_interval_max: 60
  dependency_resolution:
    resolvers:
      - type: conda
        prefix: "{{ miniconda_prefix }}"
        auto_init: false
        auto_install: false
  managers:
    rockfish:
      type: queued_drmaa
      preprocess_action_max_retries: 10
      preprocess_action_interval_start: 2
      preprocess_action_interval_step: 2
      preprocess_action_interval_max: 60
      postprocess_action_max_retries: 10
      postprocess_action_interval_start: 2
      postprocess_action_interval_step: 2
      postprocess_action_interval_max: 60
      min_polling_interval: 15

cvmfsexec_source: none
cvmfsexec_url: https://github.com/natefoo/cvmfsexec/archive/refs/heads/untar-no-preserve-times.tar.gz

cvmfsexec_files:
  - src: files/pulsar/galaxyproject.org.pub
    dest: /etc/cvmfs/keys/galaxyproject.org/galaxyproject.org.pub
  - src: files/pulsar/data.galaxyproject.org.pub
    dest: /etc/cvmfs/keys/galaxyproject.org/data.galaxyproject.org.pub
  - content: |
      CVMFS_SERVER_URL='http://cvmfs1-psu0.galaxyproject.org/cvmfs/@fqrn@;http://cvmfs1-iu0.galaxyproject.org/cvmfs/@fqrn@;http://cvmfs1-tacc0.galaxyproject.org/cvmfs/@fqrn@'
      CVMFS_KEYS_DIR=/etc/cvmfs/keys/galaxyproject.org
    dest: /etc/cvmfs/domain.d/galaxyproject.org.conf

cvmfsexec_local_options:
  - key: CVMFS_ALIEN_CACHE
    value: "{{ _rockfish_scratch_root }}/cvmfs_cache"
  - key: CVMFS_QUOTA_LIMIT
    value: "-1"
  - key: CVMFS_SHARED_CACHE
    value: "no"
  - key: CVMFS_CLAIM_OWNERSHIP
    value: "yes"
  - key: CVMFS_HTTP_PROXY
    value: "DIRECT"
