name: Vertebrate Genomes Project
type: generic
id: vgp
items:
- sections: [get_data, collection_operations, text_manipulation, filter_and_sort, join__subtract_and_group, fasta_fastq, fastq_quality_control, sam_bam, bed]
- type: section
  id: vgp_pipeline_tools
  name: VGP Pipeline Tools
  items:
  - type: tool
    id: Convert characters1
  - type: tool
    id: Cut1
  - type: tool
    id: Paste1
  - type: tool
    id: __EXTRACT_DATASET__
  - type: tool
    id: __SORTLIST__
  - type: tool
    id: addValue
  - type: tool
    id: cat1
  - type: tool
    id: export_remote
  - type: tool
    id: param_value_from_file
  - type: tool
    id: sort1
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/bgruening/bionano_scaffold/bionano_scaffold
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/bgruening/gfastats/gfastats
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/bgruening/gfastats/gfastats
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/bgruening/gfastats/gfastats
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/bgruening/hifiasm/hifiasm
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/bgruening/mitohifi/mitohifi
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_awk_tool
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_cat
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_easyjoin_tool
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_find_and_replace
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_grep_tool
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_replace_in_line
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_sed_tool
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_sort_header_tool
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_tail_tool
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/devteam/add_value/addValue
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/devteam/column_maker/Add_a_column1
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/devteam/column_maker/Add_a_column1
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_blastn_wrapper
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_dustmasker_wrapper
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/bandage/bandage_image
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/bedtools/bedtools_bamtobed
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/bellerophon/bellerophon
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/busco/busco
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/bwa_mem2/bwa_mem2
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/compose_text_param/compose_text_param
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/compress_file/compress_file
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/datamash_ops/datamash_ops
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/genomescope/genomescope
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/ggplot2_point/ggplot2_point
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/kraken2/kraken2
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/merqury/merqury
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/meryl/meryl
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/minimap2/minimap2
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/multiqc/multiqc
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/parse_mito_blast/parse_mito_blast
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/pretext_map/pretext_map
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/pretext_snapshot/pretext_snapshot
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/purge_dups/purge_dups
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/salsa/salsa
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/yahs/yahs
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/lparsons/cutadapt/cutadapt
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iuc/mitos2/mitos2
