---

- name: Include tasks for updating Galaxy
  include_tasks: update.yml
  when: galaxy_cvmfs_update is defined and galaxy_cvmfs_update

- name: Include tasks for updating Galaxy client (standalone)
  include_tasks: client.yml
  when: galaxy_cvmfs_client is defined and galaxy_cvmfs_client

- name: Include tasks for updating stratum 1 snapshots
  include_tasks: snapshot.yml
  when: galaxy_cvmfs_snapshot is defined and galaxy_cvmfs_snapshot

- name: Include tasks for wiping client caches
  include_tasks: flush_cache.yml
  when: galaxy_cvmfs_flush_cache is defined and galaxy_cvmfs_flush_cache
