---

- name: CVMFS snapshot
  command: /usr/bin/cvmfs_server snapshot {{ galaxy_cvmfs_repo }}
  environment:
    X509_CERT_BUNDLE: /etc/pki/tls/cert.pem

- name: Clear squid cache (restart)
  service:
    name: squid
    state: restarted
  when: usegalaxy_cvmfs_restart_squid | default(true)
