---

- name: Fetch mutable configs from master host
  synchronize:
    mode: pull
    src: "{{ item.dest }}"
    dest: "files/galaxy/var/{{ item.dest | basename }}"
  with_items: "{{ galaxy_mutable_configs }}"
  when: inventory_hostname == groups['galaxyservers'][0]

- name: Fetch tool panel layout
  synchronize:
    mode: pull
    src: "{{ galaxy_config[galaxy_app_config_section]['integrated_tool_panel_config'] }}"
    dest: "files/galaxy/var/integrated_tool_panel.xml"
  when: inventory_hostname == groups['galaxyservers'][0]
