---
# TODO: tools_conf, common vars should be merged into here

# This is in the all group_vars so that you can override values in galaxyservers group_vars if needed

galaxy_job_conf_environments:

  # these envs have id 'slurm_{{ id }}'
  slurm_environments:

    # non-singularity environments
    # TODO: these are for transition only and should not be used once all tools are transitioned to Singularity
    - id: normal_py2_direct
      native_specification: --partition=normal,jsnormal --nodes=1 --ntasks=1 --time=36:00:00
      use_singularity: false
      extra_params: {use_metadata_binary: true}
      tags: [normal_limit]
      append_envs:
        - file: /cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/venv/bin/activate
        - name: GALAXY_VIRTUAL_ENV
          value: None
        - name: PATH
          value: /cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/deps/_py2/bin:$PATH
    - id: test_normal_py2_direct
      native_specification: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=00:30:00 --mem=3840
      use_singularity: false
      extra_params: {use_metadata_binary: true}
      tags: [test_limit]
      append_envs:
        - file: /cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/venv/bin/activate
        - name: GALAXY_VIRTUAL_ENV
          value: None
        - name: PATH
          value: /cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/deps/_py2/bin:$PATH
    - id: normal_direct
      native_specification: --partition=normal,jsnormal --nodes=1 --ntasks=1 --time=36:00:00
      use_singularity: false
      java_mem: 7
      tags: [normal_limit]
    - id: test_normal_direct
      native_specification: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=00:30:00 --mem=3840
      use_singularity: false
      java_mem: 3
      tags: [test_limit]
    - id: normal_16gb_direct
      native_specification: --partition=normal,jsnormal --nodes=1 --ntasks=1 --time=36:00:00 --mem=15360
      use_singularity: false
      java_mem: 7
      tags: [normal_limit]
    - id: normal_32gb_direct
      native_specification: --partition=normal,jsnormal --nodes=1 --ntasks=1 --time=24:00:00 --mem=30720
      use_singularity: false
      java_mem: 7
      tags: [normal_limit]
    - id: normal_64gb_direct
      native_specification: --partition=normal,jsnormal --nodes=1 --ntasks=1 --time=4:00:00 --mem=61440
      use_singularity: false
      java_mem: 7
      tags: [normal_limit]
    - id: multi_direct
      native_specification: --partition=multi,jsmulti --nodes=1 --ntasks=6 --time=36:00:00
      use_singularity: false
      java_mem: 7
      tags: [multi_direct, multi_limit]
    - id: multi_py2_direct
      native_specification: --partition=multi,jsmulti --nodes=1 --ntasks=6 --time=36:00:00
      use_singularity: false
      extra_params: {use_metadata_binary: true}
      tags: [multi_py2_direct, multi_limit]
      append_envs:
        - file: /cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/venv/bin/activate
        - name: GALAXY_VIRTUAL_ENV
          value: None
        - name: PATH
          value: /cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/deps/_py2/bin:$PATH
    - id: multi_long_direct
      native_specification: --partition=multi,jsmulti --nodes=1 --ntasks=6 --time=72:00:00
      use_singularity: false
      java_mem: 28
      tags: [multi_long, multi_long_limit]

    # training environments
    - id: training
      native_specification: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=00:50:00 --mem=3840
      java_mem: 3
      use_singularity: false
      tags: [training_limit]
    - id: training_long
      native_specification: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=02:00:00 --mem=3840
      java_mem: 3
      use_singularity: false
      tags: [training_limit]
    - id: training_large
      native_specification: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=00:20:00 --mem=15360
      java_mem: 15
      use_singularity: false
      tags: [training_limit]
    - id: training_xlarge
      native_specification: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=00:10:00 --mem=23040
      java_mem: 22
      use_singularity: false
      tags: [training_limit]
    - id: training_multi
      native_specification: --partition=reserved,jsreserved --nodes=1 --ntasks=2 --time=01:20:00 --mem=7680
      java_mem: 7
      use_singularity: false
      tags: [training_limit]
    - id: training_multi_large
      native_specification: --partition=reserved,jsreserved --nodes=1 --ntasks=4 --time=01:20:00 --mem=15360
      java_mem: 15
      use_singularity: false
      tags: [training_limit]

    # legacy/conda environments
    - id: normal_conda
      native_specification: --partition=normal,jsnormal --nodes=1 --ntasks=1 --time=36:00:00
      tags: [normal_limit]
      container_override:
        - type: singularity
          shell: /bin/sh
          resolve_dependencies: true
          # TODO: commit to CVMFS
          # image is https://github.com/natefoo/usegalaxy.org-legacy-environment
          identifier: /corral4/main/singularity/usegalaxy.org-legacy-environment--0
    - id: test_normal_conda
      native_specification: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=00:30:00 --mem=3840
      java_mem: 3
      tags: [test_limit]
      container_override:
        - type: singularity
          shell: /bin/sh
          resolve_dependencies: true
          identifier: /corral4/main/singularity/usegalaxy.org-legacy-environment--0
    - id: multi_conda
      native_specification: --partition=multi,jsmulti --nodes=1 --ntasks=6 --time=36:00:00
      tags: [multi_limit]
      container_override:
        - type: singularity
          shell: /bin/sh
          resolve_dependencies: true
          identifier: /corral4/main/singularity/usegalaxy.org-legacy-environment--0
    - id: normal_py2
      native_specification: --partition=normal,jsnormal --nodes=1 --ntasks=1 --time=36:00:00
      default_container_id: /cvmfs/singularity.galaxyproject.org/all/python:2.7.16
      tags: [normal_limit]
    - id: test_normal_py2
      native_specification: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=00:30:00 --mem=3840
      java_mem: 3
      default_container_id: /cvmfs/singularity.galaxyproject.org/all/python:2.7.16
      tags: [test_limit]
    - id: multi_py2
      native_specification: --partition=multi,jsmulti --nodes=1 --ntasks=6 --time=36:00:00
      default_container_id: /cvmfs/singularity.galaxyproject.org/all/python:2.7.16
      tags: [multi_py2, multi_limit]
    - id: normal_galaxy_env
      native_specification: --partition=normal,jsnormal --nodes=1 --ntasks=1 --time=36:00:00
      tags: [normal_limit]
      append_envs:
        # FIXME: GALAXY_VIRTUAL_ENV/VIRTUAL_ENV not needed?
        - name: SINGULARITYENV_PREPEND_PATH
          value: /cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/venv/bin
    - id: test_normal_galaxy_env
      native_specification: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=00:30:00 --mem=3840
      java_mem: 3
      tags: [test_limit]
      append_envs:
        # FIXME: GALAXY_VIRTUAL_ENV/VIRTUAL_ENV not needed?
        - name: SINGULARITYENV_PREPEND_PATH
          value: /cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/venv/bin
    - id: normal_resolv_fix
      runner: slurm
      native_specification: --partition=normal,jsnormal --nodes=1 --ntasks=1 --time=36:00:00
      tags: [normal_limit]
      # https://github.com/bioconda/bioconda-recipes/issues/11583
      extra_params: {singularity_run_extra_arguments: --no-mount=tmp}
    - id: test_normal_resolv_fix
      runner: slurm
      native_specification: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=00:30:00 --mem=3840
      java_mem: 3
      tags: [test_limit]
      # https://github.com/bioconda/bioconda-recipes/issues/11583
      extra_params: {singularity_run_extra_arguments: --no-mount=tmp}

    # upload should not need a ton of resources but also needs RW access to the FTP dir
    #- id: upload
    #  native_specification: --partition=normal,jsnormal --nodes=1 --ntasks=1 --time=12:00:00 --mem=3840
    #  java_mem: 3
    #  volumes: "{{ galaxy_job_conf_singularity_volumes + [galaxy_ftp_upload_dir ~ ':rw', galaxy_nginx_upload_dir ~ ':rw'] }}"
    #  create_test_env: true
    #  tags:
    #    - normal

    # normal environments
    - id: normal
      native_specification: --partition=normal,jsnormal --nodes=1 --ntasks=1 --time=36:00:00
      java_mem: 7
      tags: [normal_limit]
    - id: test_normal
      native_specification: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=00:30:00 --mem=3840
      java_mem: 3
      tags: [test_limit]
    - id: normal_16gb
      native_specification: --partition=normal,jsnormal --nodes=1 --ntasks=1 --time=36:00:00 --mem=15360
      java_mem: 15
      tags: [normal_limit]
    - id: normal_32gb
      native_specification: --partition=normal,jsnormal --nodes=1 --ntasks=1 --time=24:00:00 --mem=30720
      java_mem: 30
      tags: [normal_limit]
    - id: normal_64gb
      native_specification: --partition=normal,jsnormal --nodes=1 --ntasks=1 --time=4:00:00 --mem=61440
      java_mem: 60
      tags: [normal_limit]

    # multicore environments
    - id: multi
      native_specification: --partition=multi,jsmulti --nodes=1 --ntasks=6 --time=36:00:00
      java_mem: 28
      tags: [multi, multi_limit]
    - id: multi_development
      native_specification: --partition=normal,jsnormal --nodes=1 --ntasks=2 --time=00:30:00
      java_mem: 15
    - id: multi_long
      native_specification: --partition=multi,jsmulti --nodes=1 --ntasks=6 --time=72:00:00
      java_mem: 28
      tags: [multi_long, multi_long_limit]
    - id: multi_resolv_fix
      runner: slurm
      native_specification: --partition=multi,jsmulti --nodes=1 --ntasks=6 --time=36:00:00
      tags: [multi_limit]
      # https://github.com/bioconda/bioconda-recipes/issues/11583
      extra_params: {singularity_run_extra_arguments: --no-mount=tmp}

    # priority (reserved) environments
    - id: reserved_normal
      native_specification: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=36:00:00
      java_mem: 7
      tags: [reserved]
    - id: reserved_normal_direct
      native_specification: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=36:00:00
      use_singularity: false
      java_mem: 7
      tags: [reserved]
    - id: reserved_normal_16gb
      native_specification: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=36:00:00 --mem=15360
      java_mem: 15
      tags: [reserved]
    - id: reserved_normal_32gb
      native_specification: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=24:00:00 --mem=30720
      java_mem: 30
      tags: [reserved]
    - id: reserved_normal_64gb
      native_specification: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=4:00:00 --mem=61440
      java_mem: 60
      tags: [reserved]
    - id: reserved_multi
      native_specification: --partition=reserved,jsreserved --nodes=1 --ntasks=6 --time=36:00:00 --mem=30720
      java_mem: 28
      tags: [reserved]

  # these envs have id 'jetstream_{{ id }}'
  jetstream_environments:

    # non-singularity environments
    # TODO: these are for transition only and should not be used once all tools are transitioned to Singularity
    - id: iu_multi_py2_direct
      runner: jetstream_iu
      native_specification: --partition=multi --nodes=1 --time=36:00:00
      use_singularity: false
      extra_params: {use_metadata_binary: true}
      tags: [multi_py2_direct, multi_limit]
      append_envs:
        - file: /cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/venv/bin/activate
        - name: GALAXY_VIRTUAL_ENV
          value: None
        - name: PATH
          value: /cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/deps/_py2/bin:$PATH
    - id: tacc_multi_py2_direct
      runner: jetstream_tacc
      native_specification: --partition=multi --nodes=1 --time=36:00:00
      use_singularity: false
      extra_params: {use_metadata_binary: true}
      tags: [multi_py2_direct, multi_limit]
      append_envs:
        - file: /cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/venv/bin/activate
        - name: GALAXY_VIRTUAL_ENV
          value: None
        - name: PATH
          value: /cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/deps/_py2/bin:$PATH
    - id: iu_multi_direct
      runner: jetstream_iu
      native_specification: --partition=multi --nodes=1 --time=36:00:00
      use_singularity: false
      java_mem: 28
      tags: [multi_direct, multi_limit]
    - id: tacc_multi_direct
      runner: jetstream_tacc
      native_specification: --partition=multi --nodes=1 --time=36:00:00
      use_singularity: false
      java_mem: 28
      tags: [multi_direct, multi_limit]
    - id: tacc_xlarge_direct
      runner: jetstream_tacc
      native_specification: --partition=xlarge --nodes=1 --time=36:00:00
      use_singularity: false
      java_mem: 58
      tags: [xlarge_limit]

    # multicore environments
    - id: iu_multi
      runner: jetstream_iu
      native_specification: --partition=multi --nodes=1 --time=36:00:00
      java_mem: 28
      tags: [multi, multi_limit]
    - id: tacc_multi
      runner: jetstream_tacc
      native_specification: --partition=multi --nodes=1 --time=36:00:00
      java_mem: 28
      tags: [multi, multi_limit]
    - id: iu_multi_long
      runner: jetstream_iu
      native_specification: --partition=multi --nodes=1 --time=60:00:00
      java_mem: 28
      tags: [multi_long, multi_long_limit]
    - id: tacc_multi_long
      runner: jetstream_tacc
      native_specification: --partition=multi --nodes=1 --time=60:00:00
      java_mem: 28
      tags: [multi_long, multi_long_limit]
    - id: tacc_xlarge
      runner: jetstream_tacc
      native_specification: --partition=xlarge --nodes=1 --time=36:00:00
      java_mem: 58
      tags: [xlarge_limit]

  stampede_environments:
    - id: normal
      memory_mb: 94208
      native_specification: --partition=normal --nodes=1 --account=TG-MCB140147 --ntasks=68 --time=36:00:00
    - id: development
      memory_mb: 94208
      native_specification: --partition=development --nodes=1 --account=TG-MCB140147 --ntasks=68 --time=00:30:00
    - id: skx_normal
      memory_mb: 192512
      native_specification: --partition=skx-normal --nodes=1 --account=TG-MCB140147 --ntasks=48 --time=36:00:00
    - id: skx_development
      memory_mb: 192512
      native_specification: --partition=skx-dev --nodes=1 --account=TG-MCB140147 --ntasks=48 --time=00:30:00
    - id: long
      memory_mb: 94208
      native_specification: --partition=long --nodes=1 --account=TG-MCB140147 --ntasks=68 --time=60:00:00
      tags: [multi_long, multi_long_limit]

  frontera_environments:
    - id: small
      native_specification: --partition=small --nodes=1 --ntasks=56 --time=48:00:00
      memory_mb: 194560
    - id: development
      native_specification: --partition=development --nodes=1 --ntasks=56 --time=00:30:00
      memory_mb: 194560

  bridges_environments:
    - id: normal
      native_specification: --partition=RM --time=24:00:00 --nodes=1 --ntasks=64
    - id: shared_128gb
      native_specification: --partition=RM-shared --time=24:00:00 --nodes=1 --ntasks=64
    - id: shared_64gb
      native_specification: --partition=RM-shared --time=24:00:00 --nodes=1 --ntasks=32
    - id: extreme_1tb
      native_specification: --partition=EM --time=24:00:00 --nodes=1 --ntasks=24
    - id: development
      native_specification: --partition=RM-shared --time=00:30:00 --nodes=1 --ntasks=8

  expanse_environments:
    - id: normal
      native_specification: --account=TG-MCB140147 --partition=compute --time=24:00:00 --nodes=1 --ntasks=64
    - id: shared_128gb
      native_specification: --account=TG-MCB140147 --partition=shared --time=24:00:00 --nodes=1 --ntasks=64 --mem=131072
    - id: shared_64gb
      native_specification: --account=TG-MCB140147 --partition=shared --time=24:00:00 --nodes=1 --ntasks=32 --mem=65536
    - id: development
      native_specification: --account=TG-MCB140147 --partition=debug --time=00:30:00 --nodes=1 --ntasks=4 --mem=8192
