---
# TODO: tools_conf, common vars should be merged into here

# This is in the all group_vars so that you can override values in galaxyservers group_vars if needed

galaxy_job_conf_environments:

  slurm_environments:
    # training destinations
    - id: training
      native_spec: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=00:50:00 --mem=3840
      java_mem: 3
      create_legacy_env: false
      create_reserved_env: false
      tags:
        - training
    - id: training_long
      native_spec: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=02:00:00 --mem=3840
      java_mem: 3
      create_legacy_env: false
      create_reserved_env: false
      tags:
        - training
    - id: training_large
      native_spec: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=00:20:00 --mem=15360
      java_mem: 15
      create_legacy_env: false
      create_reserved_env: false
      tags:
        - training
    - id: training_xlarge
      native_spec: --partition=reserved,jsreserved --nodes=1 --ntasks=1 --time=00:10:00 --mem=23040
      java_mem: 22
      create_legacy_env: false
      create_reserved_env: false
      tags:
        - training
    - id: training_multi
      native_spec: --partition=reserved,jsreserved --nodes=1 --ntasks=2 --time=01:20:00 --mem=7680
      java_mem: 7
      create_legacy_env: false
      create_reserved_env: false
      tags:
        - training
    - id: training_multi_large
      native_spec: --partition=reserved,jsreserved --nodes=1 --ntasks=4 --time=01:20:00 --mem=15360
      java_mem: 15
      create_legacy_env: false
      create_reserved_env: false
      tags:
        - training

    # upload should not need a ton of resources but also needs RW access to the FTP dir
    #- id: upload
    #  native_spec: --partition=normal,jsnormal --nodes=1 --ntasks=1 --time=12:00:00 --mem=3840
    #  java_mem: 3
    #  volumes: "{{ galaxy_job_conf_singularity_volumes + [galaxy_ftp_upload_dir ~ ':rw', galaxy_nginx_upload_dir ~ ':rw'] }}"
    #  create_test_env: true
    #  tags:
    #    - normal

    # normal destinations
    - id: normal
      native_spec: --partition=normal,jsnormal --nodes=1 --ntasks=1 --time=36:00:00
      java_mem: 7
      create_test_env: true
      create_deps_env: true
      create_legacy_env: true
      create_reserved_env: true
      tags:
        - normal
    - id: normal_16gb
      native_spec: --partition=normal,jsnormal --nodes=1 --ntasks=1 --time=36:00:00 --mem=15360
      java_mem: 15
      create_reserved_env: true
    - id: normal_32gb
      native_spec: --partition=normal,jsnormal --nodes=1 --ntasks=1 --time=24:00:00 --mem=30720
      java_mem: 30
      create_reserved_env: true
    - id: normal_64gb
      native_spec: --partition=normal,jsnormal --nodes=1 --ntasks=1 --time=4:00:00 --mem=61440
      java_mem: 60
      create_reserved_env: true

    # multicore destinations
    - id: multi
      native_spec: --partition=multi,jsmulti --nodes=1 --ntasks=6 --time=36:00:00
      java_mem: 28
      create_legacy_env: true
      create_reserved_env: true
      tags:
        - multi
    - id: multi_development
      native_spec: --partition=normal,jsnormal --nodes=1 --ntasks=2 --time=00:30:00
      java_mem: 15
    - id: multi_long
      native_spec: --partition=multi,jsmulti --nodes=1 --ntasks=6 --time=72:00:00
      java_mem: 28
      tags:
        - multi_long

  jetstream_environments:
    - id: iu_multi
      runner: jetstream_iu
      native_spec: --partition=multi --nodes=1 --time=36:00:00
      java_mem: 28
      tags:
        - multi
      create_legacy_env: true
      create_reserved_env: true
    - id: tacc_multi
      runner: jetstream_tacc
      native_spec: --partition=multi --nodes=1 --time=36:00:00
      java_mem: 28
      create_legacy_env: true
      create_reserved_env: true
      tags:
        - multi
    - id: iu_multi_long
      runner: jetstream_iu
      native_spec: --partition=multi --nodes=1 --time=60:00:00
      java_mem: 28
      tags:
        - multi_long
    - id: tacc_multi_long
      runner: jetstream_tacc
      native_spec: --partition=multi --nodes=1 --time=60:00:00
      java_mem: 28
      tags:
        - multi_long
    - id: tacc_xlarge
      runner: jetstream_tacc
      native_spec: --partition=xlarge --nodes=1 --time=36:00:00
      java_mem: 58

  stampede_environments:
    - id: normal
      memory_mb: 94208
      native_spec: --partition=normal --nodes=1 --account=TG-MCB140147 --ntasks=68 --time=36:00:00
    - id: development
      memory_mb: 94208
      native_spec: --partition=development --nodes=1 --account=TG-MCB140147 --ntasks=68 --time=00:30:00
    - id: skx_normal
      memory_mb: 192512
      native_spec: --partition=skx-normal --nodes=1 --account=TG-MCB140147 --ntasks=48 --time=36:00:00
    - id: skx_development
      memory_mb: 192512
      native_spec: --partition=skx-dev --nodes=1 --account=TG-MCB140147 --ntasks=48 --time=00:30:00
    - id: long
      memory_mb: 94208
      native_spec: --partition=long --nodes=1 --account=TG-MCB140147 --ntasks=68 --time=60:00:00
      tags:
      - multi_long

  frontera_environments:
    - id: small
      native_spec: --partition=small --nodes=1 --ntasks=56 --time=48:00:00
      memory_mb: 194560
    - id: development
      native_spec: --partition=development --nodes=1 --ntasks=56 --time=00:30:00
      memory_mb: 194560

  bridges_environments:
    - id: normal
      native_spec: --partition=RM --time=24:00:00 --nodes=1 --ntasks=64
    - id: shared_128gb
      native_spec: --partition=RM-shared --time=24:00:00 --nodes=1 --ntasks=64
    - id: shared_64gb
      native_spec: --partition=RM-shared --time=24:00:00 --nodes=1 --ntasks=32
    - id: extreme_1tb
      native_spec: --partition=EM --time=24:00:00 --nodes=1 --ntasks=24
    - id: development
      native_spec: --partition=RM-shared --time=00:30:00 --nodes=1 --ntasks=8

  expanse_environments:
    - id: normal
      native_spec: --account=TG-MCB140147 --partition=compute --time=24:00:00 --nodes=1 --ntasks=64
    - id: shared_128gb
      native_spec: --account=TG-MCB140147 --partition=shared --time=24:00:00 --nodes=1 --ntasks=64 --mem=131072
    - id: shared_64gb
      native_spec: --account=TG-MCB140147 --partition=shared --time=24:00:00 --nodes=1 --ntasks=32 --mem=65536
    - id: development
      native_spec: --account=TG-MCB140147 --partition=debug --time=00:30:00 --nodes=1 --ntasks=4 --mem=8192
