---

shared_root: /home/xcgalaxy

pulsar_drmaa_library_path: "{{ instance_root }}/pbs-drmaa/lib/libdrmaa.so"

pulsar_yaml_config:
  staging_directory: "/crucible/mc48nsp/xcgalaxy/test/pulsar/var/staging"
  persistence_directory: "{{ pulsar_root }}/var/persisted_data"
  tool_dependency_dir: "{{ instance_root }}/deps"
  job_metrics_config_file: "{{ pulsar_config_dir }}/job_metrics_conf.xml"
  message_queue_url: "{{ pulsar_message_queue_url }}"
  dependency_resolvers_config_file: "{{ pulsar_config_dir }}/dependency_resolvers_conf.xml"
  amqp_acknowledge: True
  amqp_publish_retry: True
  amqp_publish_retry_max_retries: 5
  amqp_publish_retry_interval_start: 10
  amqp_publish_retry_interval_step: 10
  amqp_publish_retry_interval_max: 60
  managers:
    greenfield:
      type: queued_drmaa
      preprocess_action_max_retries: 10
      preprocess_action_interval_start: 2
      preprocess_action_interval_step: 2
      preprocess_action_interval_max: 60
      postprocess_action_max_retries: 20
      postprocess_action_interval_start: 2
      postprocess_action_interval_step: 4
      postprocess_action_interval_max: 120
      min_polling_interval: 15
    greenfield_nagios:
      type: queued_python
      min_polling_interval: 5
