---

shared_root: /work/galaxy

pulsar_drmaa_library_path: "{{ instance_root }}/slurm-drmaa/lib/libdrmaa.so"

pulsar_install_environments:
  pyOpenSSL:
    PKG_CONFIG_PATH: "{{ instance_root }}/libffi/lib64/pkgconfig"
    CFLAGS: "-I{{ instance_root }}/openssl/include"
    LDFLAGS: "-L{{ instance_root }}/openssl/lib"
  pycurl:
    PYCURL_SSL_LIBRARY: "nss"
