---

git_executable: ~/git/bin/git
shared_root: /brashear/xcgalaxy

pulsar_drmaa_library_path: "{{ instance_root }}/pbs-drmaa/lib/libdrmaa.so"
pulsar_staging_dir: "/bl2/xcgalaxy/test/pulsar/var/staging"
galaxy_root: "/bl2/xcgalaxy/test/galaxy"
pulsar_dependencies_dir: "/bl2/xcgalaxy/test/deps"

pulsar_job_managers:
  blacklight:
    type: queued_drmaa
    preprocess_action_max_retries: 10
    preprocess_action_interval_start: 2
    preprocess_action_interval_step: 2
    preprocess_action_interval_max: 60
    postprocess_action_max_retries: 20
    postprocess_action_interval_start: 2
    postprocess_action_interval_step: 4
    postprocess_action_interval_max: 120
    min_polling_interval: 15
  blacklight_nagios:
    type: queued_python
    min_polling_interval: 5

pulsar_install_environments:
  pyOpenSSL:
    LD_LIBRARY_PATH: ""
    PKG_CONFIG_PATH: "{{ instance_root }}/libffi/lib64/pkgconfig"
    CFLAGS: "-I{{ instance_root }}/openssl/include"
    LDFLAGS: "-L{{ instance_root }}/openssl/lib"
    PATH: "/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/games:/usr/lib64/jvm/jre/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin"
  pycurl:
    LD_LIBRARY_PATH: ""
    PYCURL_SSL_LIBRARY: "openssl"
    CFLAGS: "-I{{ instance_root }}/curl/include -I{{ instance_root }}/openssl/include"
    LDFLAGS: "-L{{ instance_root }}/curl/lib -L{{ instance_root }}/openssl/lib -Wl,-rpath,{{ instance_root }}/curl/lib -Wl,-rpath,{{ instance_root }}/openssl/lib"
    PYCURL_CURL_CONFIG: "{{ instance_root }}/curl/bin/curl-config"
    PATH: "/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/games:/usr/lib64/jvm/jre/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin"

