---

paths:
  - path: /galaxy/data
    path_types: unstructured
    action: rewrite
    source_directory: /galaxy/data
    destination_directory: /cvmfs/data.galaxyproject.org/byhand
  #- path: /galaxy-repl/test/files
  #  action: copy
  #- path: /galaxy/test/jobdir
  #  action: copy
  #- path: /jetstream
  #  action: none
