---

# FIXME: /etc/systemd/system/galaxy-main.service is manually deployed because you can't override the service name in
# galaxyproject.org

# NOTE: this is duplicated from group_vars/supervisorservers in the test env. This overrides the group var setting for
# creating ~g2main/etc/supervisor.conf since Test and Main's supervisords use different passwords.
supervisord_inet_pass: "{{ vault_supervisord_inet_pass }}"

galaxy_job_conf_pulsar_galaxy_url: https://galaxy-web-03.galaxyproject.org

# gxit_proxy_port is hardcoded here and in the template since the nginx config is deployed from the test env

galaxy_host_codename: main_k8s
galaxy_systemd_mode: null
galaxy_gravity_config_default: null
gravity_config_file: "/etc/galaxy/gravity.d/galaxy_{{ galaxy_instance_codename }}.yml"
gravity_config:
  instance_name: "{{ galaxy_instance_codename }}"
  galaxy_user: "{{ galaxy_user }}"
  galaxy_group: "{{ galaxy_group }}"
  galaxy_root: "{{ galaxy_server_dir }}"
  galaxy_config_file: "{{ galaxy_config_file }}"
  log_dir: "{{ galaxy_log_dir }}"
  virtualenv: "{{ galaxy_venv_dir }}"
  gunicorn:
    enable: false
  celery:
    enable: false
    enable_beat: false
  gx_it_proxy:
    enable: true
    port: 8980
    sessions: "{{ galaxy_interactivetools_map }}"
    verbose: true
    environment:
      # FIXME: the systemd service unit sets this as /srv/galaxay/main, which is not writable. When this is the case the
      # proxy fails to start with essentially no output (just writes an empty newline to the log file).
      HOME: "/home/g2main"
galaxy_job_conf_handlers:
  - id: main_k8s_handler0
    plugins:
      - tacc_k8s
    environment:
      PYTHONPATH: "lib:{{ galaxy_dynamic_job_rules_dir }}"
    tags:
      - k8s

## used by: supervisor
host_supervisor_configs: []

host_absent_supervisor_configs:
  - galaxy_main_k8s

# NOTE: nginx configs are in the test env
