---

galaxy_job_conf_pulsar_galaxy_url: https://galaxy-web-03.galaxyproject.org

galaxy_host_codename: main_k8s
galaxy_systemd_mode: null
galaxy_gravity_config_default: null
gravity_config_file: "/etc/galaxy/gravity.d/galaxy_{{ galaxy_instance_codename }}.yml"
gravity_virtualenv_command: /opt/rh/rh-python38/root/usr/bin/python3 -m venv
gravity_venv_dir: "{{ galaxy_root }}/gravity"
gravity_package: "gravity==1.0.6"
galaxy_gravity_command: "{{ gravity_venv_dir }}/bin/galaxyctl"
gravity_config:
  instance_name: "{{ galaxy_instance_codename }}"
  galaxy_user: "{{ galaxy_user }}"
  galaxy_group: "{{ galaxy_group }}"
  galaxy_root: "{{ galaxy_server_dir }}"
  galaxy_config_file: "{{ galaxy_config_file }}"
  log_dir: "{{ galaxy_log_dir }}"
  virtualenv: "{{ galaxy_venv_dir }}"
  gunicorn:
    enable: false
  celery:
    enable: false
    enable_beat: false
  handlers:
    main_k8s_handler:
      name_template: "{name}{process}"
      processes: 1
      pools:
        - job-handlers.k8s
      environment:
        HDF5_USE_FILE_LOCKING: "FALSE"

galaxy_job_conf_runners:
  jetstream2_k8s:
    load: galaxy.jobs.runners.pulsar:PulsarKubernetesJobRunner
    manager: jetstream2_k8s

## used by: supervisor
host_supervisor_configs: []

host_absent_supervisor_configs:
  - galaxy_main_k8s

# NOTE: nginx configs are in the test env
