---

nginx_flavor: full

nginx_conf_ssl_certificate: /etc/nginx/ssl/athena.galaxyproject.org_cert.pem
nginx_conf_ssl_certificate_key: /etc/nginx/ssl/athena.galaxyproject.org_privatekey.pem

nginx_conf_http:
  server_names_hash_bucket_size: 128
  client_max_body_size: 1g
  proxy_read_timeout: 3600

nginx_srv: /srv/nginx
nginx_configs:
  - galaxyproject
  - cloudlaunch
