---

local_users:
  - name: launch
    comment: 'Galaxy Cloud Launch'
    system: 'yes'
    shell: '/bin/bash'
    groups: 'www-data'
  - name: sites
    comment: 'Web sites'
    system: 'yes'
    shell: '/bin/bash'
    groups: 'www-data'

authorized_key_users:
  - name: root
    authorized:
      - nate
  - name: launch
    authorized:
      - nate
      - enis
  - name: ubuntu
    authorized:
      - nate
      - enis
  - name: sites
    authorized:
      - nate
      - anton
      - dave_c

directories:
  - path: /srv/cloudlaunch
    owner: launch
    group: launch
  - path: /srv/nginx
    owner: sites
    group: sites

nginx_flavor: full

nginx_conf_ssl_certificate: /etc/nginx/ssl/athena.galaxyproject.org_cert.pem
nginx_conf_ssl_certificate_key: /etc/nginx/ssl/athena.galaxyproject.org_privatekey.pem

nginx_conf_http:
  server_names_hash_bucket_size: 128
  client_max_body_size: 1g
  proxy_read_timeout: 3600

nginx_srv: /srv/nginx
nginx_configs:
  - galaxyproject
  - cloudlaunch
