---

postgresql_backup_dir: /galaxy-repl/pgsql/backup/galaxy05.tacc.utexas.edu
postgresql_backup_mail_recipient: root@galaxyproject.org

postgresql_conf:
  listen_addresses: "'*'"
  max_connections: 250
  shared_buffers: 64MB
  temp_buffers: 16MB
  max_prepared_transactions: 50
  work_mem: 8MB
  maintenance_work_mem: 32MB

postgresql_pg_hba_conf:
  - "host    all             all             129.114.60.173/32       password"
  - "host    galaxy_test     g2test          129.114.60.176/32       password"
  - "local   galaxy_test     g2ftp                                   password"
