---

postgresql_backup_dir: /galaxy-repl/pgsql/backup/galaxy-db-01.tacc.utexas.edu
postgresql_backup_mail_recipient: root@galaxyproject.org

postgresql_conf:
  listen_addresses: "'*'"
  max_connections: 500
  shared_buffers: 2048MB
  temp_buffers: 64MB
  max_prepared_transactions: 100
  work_mem: 64MB
  maintenance_work_mem: 64MB
  checkpoint_completion_target: 0.9
  log_checkpoints: "on"

postgresql_pg_hba_conf:
  - "host    all             all             129.114.60.179/32       password"
  - "host    all             all             129.114.60.180/32       password"
  - "host    all             all             129.114.60.51/32        password"
  - "host    all             all             129.114.60.52/32        password"
  - "host    galaxy_main     g2main          129.114.60.176/32       password"
