---

postgresql_backup_dir: /galaxy-repl/pgsql/backup/galaxy01.tacc.utexas.edu
postgresql_backup_mail_recipient: root@galaxyproject.org

postgresql_conf:
  max_connections: 250
  shared_buffers: 64MB
  temp_buffers: 16MB
  max_prepared_transactions: 50
  work_mem: 8MB
  maintenance_work_mem: 32MB

postgresql_pg_hba_conf:
  - "local   galaxy_test     g2ftp                                   password"
