---

local_users:
  - name: shed
    comment: 'Galaxy Tool Shed'
    system: 'yes'
    shell: '/bin/bash'
    groups: 'www-data'
  - name: gxsrc
    comment: 'Galaxy Code'
    system: 'yes'
    shell: '/bin/bash'

authorized_key_users:
  - name: shed
    authorized:
      - nate
      - james
      - carl
      - dave_b
      - dave_c
      - marten
      - dannon
      - jeremy
      - dan
      - anton
      - enis
      - jen
      - jmchilton
      - nturaga
      - guerler
  - name: gxsrc
    authorized:
      - nate
      - james
      - carl
      - dave_b
      - dave_c
      - marten
      - dannon
      - jeremy
      - dan
      - anton
      - enis
      - jen
      - jmchilton
      - nturaga
      - guerler

directories:
  - path: /srv/toolshed/test
    owner: gxsrc
    group: gxsrc
  - path: /srv/toolshed/test/log
    owner: shed
    group: shed
  - path: /srv/toolshed/test/var
    owner: shed
    group: shed
  - path: /srv/toolshed/main
    owner: gxsrc
    group: gxsrc
  - path: /srv/toolshed/main/log
    owner: shed
    group: shed
  - path: /srv/toolshed/main/var
    owner: shed
    group: shed

host_packages:
  - nfs-common
  - xfsprogs
  - python-virtualenv
  - python-psycopg2
  - uwsgi
  - uwsgi-plugin-python

crontabs:
  - id: test_shed_backup
    name: Test Toolshed Backup
    user: shed
    hour: 23
    minute: 0
    job: rsync -av --delete /srv/toolshed/test/var /srv/toolshed/test/log zfsdump-radegast@westvleteren.galaxyproject.org:/zones/westvleteren/backup/radegast/testshed && ssh -T zfsdump-radegast@westvleteren.galaxyproject.org -- /usr/bin/zfs snapshot zones/westvleteren/backup/radegast/testshed@`date -u +\%Y\%m\%dT\%H\%M\%SZ`
  - id: main_shed_backup
    name: Main Toolshed Backup
    user: shed
    hour: 0
    minute: 0
    job: rsync -av --delete /srv/toolshed/main/var /srv/toolshed/main/log zfsdump-radegast@westvleteren.galaxyproject.org:/zones/westvleteren/backup/radegast/mainshed && ssh -T zfsdump-radegast@westvleteren.galaxyproject.org -- /usr/bin/zfs snapshot zones/westvleteren/backup/radegast/mainshed@`date -u +\%Y\%m\%dT\%H\%M\%SZ`


postgresql_pgdata: /var/lib/postgresql/9.4/main
postgresql_backup_local_dir: /var/lib/postgresql/backup
postgresql_backup_active_dir: zfsdump-radegast@westvleteren.galaxyproject.org:/zones/westvleteren/backup/radegast/postgres/active
postgresql_conf_dir: /etc/postgresql/9.4/main
postgresql_backup_dir: zfsdump-radegast@westvleteren.galaxyproject.org:/zones/westvleteren/backup/radegast/postgres
postgresql_backup_mail_recipient: nate@bx.psu.edu
postgresql_backup_rotate: false
postgresql_backup_remote_rsync_path: /opt/local/bin/rsync
postgresql_backup_post_command: ssh -T zfsdump-radegast@westvleteren.galaxyproject.org -- /usr/bin/zfs snapshot zones/westvleteren/backup/radegast/postgres/current@`date -u +\%Y\%m\%dT\%H\%M\%SZ`

nginx_flavor: full

nginx_conf_ssl_certificate: /etc/nginx/ssl/montana.galaxyproject.org_cert.pem
nginx_conf_ssl_certificate_key: /etc/nginx/ssl/montana.galaxyproject.org_privatekey.pem

nginx_conf_http:
  server_names_hash_bucket_size: 128
  client_max_body_size: 1g
  proxy_read_timeout: 3600
