---

# set -e restart=false to disable restart
restart: true

## these vars are defined in vault.yml
galaxy_database_password: "{{ vault_galaxy_database_password }}"
tiaas_database_password: "{{ vault_tiaas_database_password }}"

galaxy_virtualenv_command: "/cvmfs/main.galaxyproject.org/deps/_conda/envs/__python@3.11/bin/python3 -m venv"
galaxy_repo: https://github.com/{{ galaxy_repo_owner }}/galaxy.git
galaxy_repo_owner: galaxyproject
galaxy_commit_id: release_23.2

galaxy_force_checkout: true
galaxy_user: g2main
galaxy_group: G-803372
galaxy_privileged_user: gxsrc
galaxy_instance_hostname: usegalaxy.org
galaxy_instance_codename: main
galaxy_cvmfs_repo: main.galaxyproject.org
galaxy_version_file: "{{ inventory_dir }}/files/galaxy/galaxy_version.yml"
galaxy_diff_mode_verbose: false
galaxy_config_perms: 0644
galaxy_additional_venv_packages:
  - "redis>=4.5.2,<6.0.0,!=4.5.5"

# FIXME: don't want the backups of the TPV configs to be watched, maybe add a per-item backup option to
# galaxy_config_{files,templates}, or maybe we really don't need backups
galaxy_backup_configfiles: false

nginx_srv: /srv/nginx

galaxy_layout: custom
galaxy_config_style: yaml

galaxy_venv_dir: /cvmfs/{{ galaxy_cvmfs_repo }}/venv

# disable running tusd from the galaxyproject.tusd role
tusd_systemd: false
