---

## these vars are defined in vault.yml
galaxy_database_password: "{{ vault_galaxy_database_password }}"
tiaas_database_password: "{{ vault_tiaas_database_password }}"

#galaxy_commit_id: release_21.09
galaxy_commit_id: usegalaxy
galaxy_force_checkout: true
galaxy_user: g2main
galaxy_privileged_user: gxsrc
galaxy_instance_hostname: usegalaxy.org
galaxy_instance_codename: main
galaxy_cvmfs_repo: main.galaxyproject.org
galaxy_version_file: "{{ inventory_dir }}/files/galaxy/galaxy_version.yml"
galaxy_diff_mode_verbose: false

nginx_srv: /srv/nginx

galaxy_layout: custom
galaxy_config_style: yaml

galaxy_venv_dir: /cvmfs/{{ galaxy_cvmfs_repo }}/venv
