---

# set -e restart=false to disable restart
restart: true

## these vars are defined in vault.yml
galaxy_database_password: "{{ vault_galaxy_database_password }}"
tiaas_database_password: "{{ vault_tiaas_database_password }}"

galaxy_commit_id: release_23.1
galaxy_force_checkout: true
galaxy_user: g2main
galaxy_group: G-803372
galaxy_privileged_user: gxsrc
galaxy_instance_hostname: usegalaxy.org
galaxy_instance_codename: main
galaxy_cvmfs_repo: main.galaxyproject.org
galaxy_version_file: "{{ inventory_dir }}/files/galaxy/galaxy_version.yml"
galaxy_diff_mode_verbose: false
galaxy_config_perms: 0644

# FIXME: don't want the backups of the TPV configs to be watched, maybe add a per-item backup option to
# galaxy_config_{files,templates}, or maybe we really don't need backups
galaxy_backup_configfiles: false

nginx_srv: /srv/nginx

galaxy_layout: custom
galaxy_config_style: yaml

galaxy_venv_dir: /cvmfs/{{ galaxy_cvmfs_repo }}/venv

# disable running tusd from the galaxyproject.tusd role
tusd_systemd: false
