---

## these vars are defined in vault.yml
#
# used by: galaxy_config var
galaxy_config_admin_users: "{{ vault_galaxy_config_admin_users }}"
galaxy_config_id_secret: "{{ vault_galaxy_config_id_secret }}"
galaxy_config_sentry_dsn: "{{ vault_galaxy_config_sentry_dsn }}"
galaxy_config_amqp_internal_connection: "{{ vault_galaxy_config_amqp_internal_connection }}"

galaxy_config_database_connection: "postgresql://g2main:{{ galaxy_database_password }}@{{ groups.galaxydbservers[0] }}/galaxy_main"

galaxy_root: "/srv/galaxy/{{ galaxy_instance_codename }}"
galaxy_new_file_path: "/corral4/{{ galaxy_instance_codename }}/scratch3"
galaxy_job_working_directory: "/corral4/{{ galaxy_instance_codename }}/jobs"
galaxy_nginx_upload_dir: "/corral4/{{ galaxy_instance_codename }}/_upload"
galaxy_nginx_upload_job_files_dir: "/corral4/{{ galaxy_instance_codename }}/_upload_job_files"
galaxy_tus_upload_store: "/corral4/{{ galaxy_instance_codename }}/_upload_tus"
galaxy_tool_dependency_dir: "/cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/deps"
galaxy_file_path: "{{ galaxy_mutable_data_dir }}/datasets"
galaxy_log_dir: "{{ galaxy_root }}/log"
galaxy_tool_cache_data_dir: "/srv/galaxy/{{ galaxy_instance_codename }}/var/tool_cache"
galaxy_tool_search_index_dir: "/srv/galaxy/{{ galaxy_instance_codename }}/var/tool_search_index"
galaxy_object_store_cache_path: "/corral4/{{ galaxy_instance_codename }}/object_store_cache"

galaxy_interactivetools_map: "/srv/galaxy/{{ galaxy_instance_codename }}/var/interactivetools_map.sqlite"
# FIXME: use the role functionality to install these and drop galaxy_dynamic_rule_dir, this is the one used by the systemd template in the role
galaxy_dynamic_job_rules_dir: "{{ galaxy_root }}/dynamic_rules"


## used by: galaxyproject.galaxy
base_app_main: &BASE_APP_MAIN

  # message box
  message_box_visible: true

  #message_box_class: info
  message_box_class: warning
  #message_box_class: error

  # informational messages
  #message_box_content: The US Galaxy Team is exploring the possibility of hosting user-focused US-centric Galaxy meetings for the presentation of new research use Galaxy, building relationships, and facilitating communication between the user community and Galaxy developers. Please help us out by completing <a href="https://forms.gle/zgpwse47fGjWZuHi8" target="_blank">a very short survey</a> so that we can gauge interest.
  #message_box_content: Galaxy has recently been updated to a pre-release of the next Galaxy stable release (22.05), and you might encounter problems as we iron out the wrinkles. Please report any issues you encounter using the bug icon on error (red) datasets, or email <a href="mailto:galaxy-bugs@galaxyproject.org">galaxy-bugs</a>.
  #message_box_content: Galaxy has recently been upgraded to a pre-release of the next Galaxy stable release (18.05). Please report any issues you encounter using the bug icon on error (red) datasets, or email <a href="mailto:galaxy-bugs@galaxyproject.org">galaxy-bugs</a>.
  message_box_content: Galaxy's <a href="https://galaxyproject.org/main/#user-data-and-job-quotas">job concurrency limits and maximum allowed run times</a> have been decreased in order to ensure enough resources are available to students participating in the <a href="https://gxy.io/smorgasbord3/">GTN Smörgåsbord 3</a>.

  # emergency downtimes
  #message_box_content: Interactive tools (Jupyter, RStudio) are currently not running due to a cluster outage. We are working on the issue.
  #message_box_content: All tools should be functioning normally with the exception of RNA STAR.
  #message_box_content: We are operating with temporarily reduced cluster capacity and jobs may take longer than usual to execute. We are working on increasing capacity as quickly as possible.
  #message_box_content: We are operating with temporarily reduced capacity due to VM failures and apologize for any delays and errors you may encounter. We are working on restoring regular services as quickly as possible. Please see <a href="https://status.galaxyproject.org/" target="_blank">status.galaxyproject.org</a> for more information.

  # scheduled downtimes
  #message_box_content: Galaxy will be down for four hours beginning at <a target="_blank" href="https://www.timeanddate.com/worldclock/fixedtime.html?iso=20220613T090000&p1=24&ah=">2:00 PM UTC, Monday, June 13</a> for upgrades. For additional details see <a href="https://status.galaxyproject.org/">status.galaxyproject.org</a>.
  #message_box_content: Cluster upgrades are in progress, jobs will not run until upgrades are complete (by <a target="_blank" href="https://www.timeanddate.com/worldclock/fixedtime.html?iso=20180417T160000&p1=24&ah=">9:00 PM UTC, Tuesday, April 17</a>).
  #message_box_content: Tools that run on <a target="_blank" href="https://www.psc.edu/resources/bridges/">PSC Bridges</a> (Unicycler, SPAdes, Trinity) are experiencing delays due to heavy utilization on that system. Please leave your jobs queued, they will run when resources are available.

  # this can be removed after 9/22 and the datatypes_conf.xml update
  gbrowse_display_sites: wormbase,tair,modencode_worm,modencode_fly
  ucsc_display_sites: main,archaea,ucla

  # secrets

  database_connection: "{{ galaxy_config_database_connection }}"
  install_database_connection: "sqlite:////cvmfs/main.galaxyproject.org/var/galaxy_main_install.sqlite?isolation_level=IMMEDIATE"
  id_secret: "{{ galaxy_config_id_secret }}"
  admin_users: "{{ galaxy_config_admin_users }}"
  sentry_dsn: "{{ galaxy_config_sentry_dsn }}"
  sentry_sloreq_threshold: 10.0
  sentry_traces_sample_rate: 0.01
  amqp_internal_connection: "{{ galaxy_config_amqp_internal_connection }}"

  # logging
  #log_rotate_size: 200 MB
  #log_rotate_count: 10

  # paths

  config_dir: "{{ galaxy_config_dir }}"
  tool_config_file: "{{ galaxy_config_dir }}/tool_conf.xml,{{ galaxy_shed_tool_conf_file }}"
  tool_dependency_dir: "{{ galaxy_tool_dependency_dir }}"
  #job_working_directory: "{{ galaxy_job_working_directory }}"
  tool_data_path: /corral4/main/tool_data
  nginx_upload_store: "{{ galaxy_nginx_upload_dir }}"
  nginx_upload_job_files_store: "{{ galaxy_nginx_upload_job_files_dir }}"
  tus_upload_store: "{{ galaxy_tus_upload_store }}"
  #library_import_dir: /corral4/main/import
  galaxy_data_manager_data_path: /corral4/manageddata/data
  tool_cache_data_dir: "{{ galaxy_tool_cache_data_dir }}"
  tool_search_index_dir: "{{ galaxy_tool_search_index_dir }}"

  tool_sheds_config_file: "{{ galaxy_config_dir }}/tool_sheds_conf.xml"
  tool_data_table_config_path:
    - "{{ galaxy_config_dir }}/tool_data_table_conf.xml"
    - "/cvmfs/data.galaxyproject.org/byhand/location/tool_data_table_conf.xml"
    - "/cvmfs/data.galaxyproject.org/managed/location/tool_data_table_conf.xml"
  build_sites_config_file: "{{ galaxy_config_dir }}/build_sites.yml"
  #datatypes_config_file: "{{ galaxy_config_dir }}/datatypes_conf.xml"
  object_store_config_file: "{{ galaxy_config_dir }}/object_store_conf.xml"
  job_config_file: "{{ galaxy_config_dir }}/job_conf.yml"
  workflow_schedulers_config_file: "{{ galaxy_config_dir }}/workflow_schedulers_conf.xml"
  trs_servers_config_file: "{{ galaxy_config_dir }}/trs_servers_conf.yml"
  job_resource_params_file: "{{ galaxy_config_dir }}/job_resource_params_conf.xml"
  data_manager_config_file: "{{ galaxy_config_dir }}/data_manager_conf.xml"
  job_metrics_config_file: "{{ galaxy_config_dir }}/job_metrics_conf.xml"
  dependency_resolvers_config_file: "{{ galaxy_config_dir }}/dependency_resolvers_conf.xml"
  themes_config_file: "{{ galaxy_server_dir }}/config/themes_conf.yml.sample"

  migrated_tools_config: "/cvmfs/main.galaxyproject.org/config/migrated_tools_conf.xml"
  shed_tool_data_table_config: "/cvmfs/main.galaxyproject.org/config/shed_tool_data_table_conf.xml"
  shed_data_manager_config_file: "/cvmfs/main.galaxyproject.org/config/shed_data_manager_conf.xml"
  integrated_tool_panel_config: "{{ galaxy_mutable_config_dir }}/integrated_tool_panel.xml"
  sanitize_whitelist_file: /corral4/main/config/sanitize_whitelist.txt

  user_preferences_extra_conf_path: "{{ galaxy_config_dir }}/user_preferences.yml"
  container_image_cache_path: "{{ galaxy_mutable_data_dir }}/container_images"

  # disabled because potentially eating memory and didn't work for the message box anyway
  #watch_config: true
  watch_job_rules: true

  #environment_setup_file: /galaxy/main/job_env.bash

  builds_file_path: "/cvmfs/data.galaxyproject.org/managed/location/builds.txt"
  ucsc_build_sites: "/cvmfs/data.galaxyproject.org/managed/location/ucsc_build_sites.txt"

  # TODO: this was for GIEs but other stuff uses this now?
  galaxy_infrastructure_url: https://usegalaxy.org
  #trust_ipython_notebook_conversion: "True"

  interactivetools_enable: true
  # TODO: required?
  interactivetools_proxy_host: usegalaxy.org
  interactivetools_map: "{{ galaxy_interactivetools_map }}"
  interactivetools_prefix: interactivetool

  # general stuff

  load_tool_shed_datatypes: false
  database_engine_option_pool_size: 10
  database_engine_option_max_overflow: 20
  database_engine_option_server_side_cursors: false
  manage_dependency_relationships: "False"
  len_file_path: /cvmfs/data.galaxyproject.org/managed/len/ucsc
  collect_outputs_from: job_working_directory
  smtp_server: localhost
  error_email_to: galaxy-bugs@galaxyproject.org
  mailing_join_addr: galaxy-announce-join@lists.galaxyproject.org
  email_from: "UseGalaxy.org Support <galaxy-bugs@galaxyproject.org>"
  instance_resource_url: "https://galaxyproject.org/support"
  email_domain_blocklist_file: "{{ galaxy_config_dir }}/disposable_email_blacklist.conf"
  registration_warning_message: "Please register only one account. The {{ galaxy_instance_hostname }} service is provided free of charge and has limited computational and data storage resources. <strong>Registration and usage of multiple accounts is tracked and such accounts are subject to termination and data deletion.</strong>"
  user_activation_on: "True"
  activation_grace_period: 6
  inactivity_box_content: "Your account has not been activated yet.  Feel free to browse around and see what's available, but you won't be able to upload data or run jobs until you have verified your email address."
  terms_url: "https://{{ galaxy_instance_hostname }}/static/terms.html"
  ga_code: "UA-45719423-10"
  static_enabled: "True"
  nginx_x_accel_redirect_base: /_x_accel_redirect
  nginx_upload_path: /_upload
  nginx_upload_job_files_path: /_job_files
  #upstream_mod_zip: true
  log_events: "False"
  log_actions: "False"
  debug: "False"
  use_interactive: "False"
  use_pbkdf2: "True"
  allow_user_deletion: "True"
  allow_user_dataset_purge: "True"
  enable_openid: "True"
  enable_quotas: "True"
  track_jobs_in_database: "True"
  retry_metadata_internally: "False"
  retry_job_output_collection: 5
  cleanup_job: onsuccess
  monitor_thread_join_timeout: 60
  cache_user_job_count: "True"
  max_metadata_value_size: 1000000
  allow_user_impersonation: "True"

  #tool_search_limit: 30
  #tool_name_boost: 12
  #tool_section_boost: 5

  # tool search index build params from usegalaxy.eu
  tool_name_boost: 0.1
  tool_section_boost: 1
  tool_description_boost: 0.1
  tool_label_boost: 1
  tool_stub_boost: 1
  tool_help_boost: 1
  tool_search_limit: 160

  conda_prefix: "/cvmfs/main.galaxyproject.org/deps/_conda"

  mulled_resolution_cache_data_dir: "{{ galaxy_mutable_data_dir }}/mulled/data"
  mulled_resolution_cache_lock_dir: "{{ galaxy_mutable_data_dir }}/mulled/lock"

  container_resolvers:
    - type: cached_mulled_singularity
      cache_directory: /cvmfs/singularity.galaxyproject.org/all
      cache_directory_cacher_type: dir_mtime
    - type: cached_mulled_singularity
      cache_directory: /corral4/singularity/precache
      cache_directory_cacher_type: dir_mtime
    - type: explicit_singularity

  # For handler heartbeats
  #use_heartbeat: "True"
  #heartbeat_interval: "-1"
  #heartbeat_log: "{{ galaxy_log_dir }}/heartbeat_{server_name}_{pid}.log"

  # stats
  statsd_host: "127.0.0.1"
  statsd_port: "8125"
  statsd_prefix: "main"

  # start high, decrease when we've fixed things
  slow_query_log_threshold: "2"

  legacy_eager_objectstore_initialization: "False"

  enable_celery_tasks: false

  expose_potentially_sensitive_job_metrics: true
  enable_tool_source_display: true

# galaxy.yml contents
galaxy_config_hash:
  uwsgi:
    # basic settings
    - master: true
    - processes: "{{ galaxy_uwsgi_processes | default(8) }}"
    - threads: 4

    # uwsgi performance/robustness features
    - single-interpreter: true
    - thunder-lock: true
    - harakiri: 600
    - buffer-size: 16384

    # logging
    - log-maxsize: 134217728
    - log-master-bufsize: 15865856

    # application
    - pythonpath: lib
    - module: galaxy.webapps.galaxy.buildapp:uwsgi_app_factory()

    # zerg mode
    - master-fifo:
      # fifo '0'
      - "{{ galaxy_mutable_data_dir }}/zerg-new.fifo"
      # fifo '1'
      - "{{ galaxy_mutable_data_dir }}/zerg-run.fifo"
      # fifo '2'
      - "{{ galaxy_mutable_data_dir }}/zerg-old.fifo"

    # attach to zerg
    - zerg: "{{ galaxy_mutable_data_dir }}/zergpool.sock"

    # signal the currently running instance to release the running fifo and terminate
    - if-exists:
      - "{{ galaxy_mutable_data_dir }}/zerg-run.fifo"
      - hook-accepting1-once: writefifo:{{ galaxy_mutable_data_dir }}/zerg-run.fifo 2q
    # force this instance to became the running one (slot 1)
    - hook-accepting1-once: spinningfifo:{{ galaxy_mutable_data_dir }}/zerg-new.fifo 1

  galaxy:
    <<: *BASE_APP_MAIN
    new_file_path: "{{ galaxy_new_file_path }}"
