---

- name: Create swarm scale directory
  file:
    path: "{{ swarm_scale_root }}"
    state: directory
    owner: "{{ galaxy_user }}"

- name: Install dependencies
  yum:
    name: "{{ item }}"
  with_items:
    - python-virtualenv
    - openssl-devel

- name: Create swarm scale virtualenv
  pip:
    name: "{{ item }}"
    virtualenv: "{{ swarm_scale_root }}"
    state: latest
  with_items:
    - pip
    - setuptools
  become: yes
  become_user: "{{ galaxy_user }}"

# using `latest` with these can be disastrous e.g. if a new major release of Ansible is uploaded or a C extension
# dependency (e.g. cffi) is updated without wheels.
- name: Install swarm scale dependencies
  pip:
    name: "{{ item }}"
    virtualenv: "{{ swarm_scale_root }}"
  with_items:
    - ansible
    - shade
    - python-openstackclient
  become: yes
  become_user: "{{ galaxy_user }}"

- name: Create swarm scale ansible directory
  file:
    path: "{{ swarm_scale_root }}/{{ item }}"
    state: directory
    owner: "{{ galaxy_user }}"
  with_items:
    - etc/ansible

- name: Copy playbook files
  synchronize:
    archive: no
    recursive: yes
    links: no
    times: yes
    perms: yes
    copy_links: yes
    src: files/
    dest: "{{ swarm_scale_root }}/etc/ansible"
    rsync_path: "sudo -u {{ galaxy_user }} rsync"

- name: Install private data
  copy:
    content: "{{ item.content }}"
    dest: "{{ swarm_scale_root }}/etc/ansible/{{ item.dest }}"
    owner: "{{ galaxy_user }}"
    mode: "0400"
  with_items:
    - content: "{{ swarm_ssh_key }}"
      dest: "swarm_kp.pem"
    - content: "{{ clouds_yaml | to_nice_yaml }}"
      dest: "clouds.yaml"
