---

## used by: supervisor
galaxystagingservers_group_supervisor_configs:
  - galaxy


## used by: galaxyproject.nginx
nginx_conf_ssl_certificate: wildcard_cert.pem
nginx_conf_ssl_certificate_key: wildcard_privatekey.pem
nginx_conf_ssl_trusted_certificate: incommon_chain.pem
# TODO: disable 1.0, 1.1
nginx_conf_ssl_protocols:
    - TLSv1
    - TLSv1.1
    - TLSv1.2

# this is just used in the webservers group vars
nginx_conf_client_max_body_size: 80g

nginx_configs:
  - usegalaxy_staging


## used by the sysctl task in the galaxy_infrastructure playbook
sysctl_conf:
  - name: net.core.rmem_max
    value: 15990784
  - name: net.core.wmem_max
    value: 15990784
