---

## used by: supervisor
galaxywebservers_group_supervisor_configs: []

galaxywebservers_group_absent_supervisor_configs:
  - galaxy
  - galaxy_impersonate
  - galaxy_group

nginx_conf_ssl_protocols:
  - TLSv1.2

nginx_conf_ssl_ciphers:
  - ECDHE-ECDSA-AES128-GCM-SHA256
  - ECDHE-RSA-AES128-GCM-SHA256
  - ECDHE-ECDSA-AES256-GCM-SHA384
  - ECDHE-RSA-AES256-GCM-SHA384
  - ECDHE-ECDSA-CHACHA20-POLY1305
  - ECDHE-RSA-CHACHA20-POLY1305
  - DHE-RSA-AES128-GCM-SHA256
  - DHE-RSA-AES256-GCM-SHA384

# this is just used in the webservers group vars
nginx_conf_client_max_body_size: 20g

nginx_servers:
  - certbot_redirects

nginx_ssl_servers:
  - usegalaxy

nginx_extra_configs:
  - usegalaxy_rewrites.conf

certbot_domains:
  - usegalaxy.org
  - "{{ inventory_hostname_short }}.galaxyproject.org"
  - www.usegalaxy.org

# Run Galaxy with Gravity (systemd service unit is set up in the stack playbook)
galaxy_systemd_mode: gravity
galaxy_gravity_config_default:
  galaxy_root: "{{ galaxy_server_dir }}"
  log_dir: "{{ galaxy_log_dir }}"
  virtualenv: "{{ galaxy_venv_dir }}"
  app_server: unicornherder
  gunicorn:
    bind: localhost:8080
    workers: 8
    # when preload is enabled, gunicorn still detaches shortly after spawn, but does not write the pidfile until after
    # the application loads, so unicornherder fails after 5 tries (with a 1 second wait) to read the pidfile and then
    # exits.
    preload: false
  tusd:
    enable: true
    tusd_path: /usr/local/sbin/tusd
    upload_dir: "{{ galaxy_tus_upload_store }}"

# tus is run from gravity
tusd_systemd: false

# used by nginx template
galaxy_tusd_port: 1080

## used by the sysctl task in the galaxy_infrastructure playbook
sysctl_conf:
  - name: net.core.rmem_max
    value: 15990784
  - name: net.core.wmem_max
    value: 15990784
