---

## used by: uwsgi.ini.j2
galaxy_uwsgi_processes: 4


## used by: supervisor
galaxystagingservers_group_supervisor_configs:
  - galaxy


## used by: galaxyproject.nginx
# TODO: disable 1.0, 1.1
nginx_conf_ssl_protocols:
    - TLSv1
    - TLSv1.1
    - TLSv1.2

# this is just used in the webservers group vars
nginx_conf_client_max_body_size: 80g

nginx_servers:
  - certbot_redirects

nginx_ssl_servers:
  - usegalaxy_staging

certbot_domains:
  - "{{ inventory_hostname_short }}.galaxyproject.org"

certbot_auth_method: --webroot


## used by the sysctl task in the galaxy_infrastructure playbook
sysctl_conf:
  - name: net.core.rmem_max
    value: 15990784
  - name: net.core.wmem_max
    value: 15990784
