---

## used by: supervisor
galaxyjobservers_group_supervisor_configs: []

galaxyjobservers_group_absent_supervisor_configs:
  - galaxy_handler
  - galaxy_dynamic_handler
  - galaxy_workflow_scheduler
  - galaxy_group

## used by: usegalaxy_privileged
usegalaxy_dynamic_job_rules:
  - job_router.py
  #- reserved.py
  #- multi_dynamic_walltime.py
  #- bridges_select.py
  #- stampede_select.py
  - nvc_dynamic_memory.py
  #- mpi.py

# Disable handlers in role, use playbook handlers
galaxy_systemd_mode: null
galaxy_gravity_config_default:
  process_manager: systemd
  galaxy_user: "{{ galaxy_user }}"
  galaxy_group: "{{ galaxy_group }}"
  galaxy_root: "{{ galaxy_server_dir }}"
  log_dir: "{{ galaxy_log_dir }}"
  virtualenv: "{{ galaxy_venv_dir }}"
  gunicorn:
    - bind: localhost:8080
      workers: 2
      timeout: 600
      preload: true
      environment:
        PYTHONPATH: "lib:{{ galaxy_dynamic_job_rules_dir }}"
    - bind: localhost:8081
      workers: 2
      timeout: 600
      preload: true
      environment:
        PYTHONPATH: "lib:{{ galaxy_dynamic_job_rules_dir }}"
  #tusd:
  #  enable: false
  #  tusd_path: /usr/local/sbin/tusd
  #  upload_dir: "{{ galaxy_tus_upload_store }}"
  handlers: "{{ galaxy_workflow_schedulers }}"
    # job handlers are configured in host_vars and pulled by gravity from the job conf
    # workflow schedulers are configured in host_vars
