---

## used by: uwsgi.ini.j2
galaxy_uwsgi_processes: 4


## used by: supervisor
galaxystagingservers_group_supervisor_configs: []

galaxystagingservers_group_absent_supervisor_configs:
  - galaxy

## used by: galaxyproject.nginx
nginx_conf_ssl_protocols:
  - TLSv1.2

nginx_conf_ssl_ciphers:
  - ECDHE-ECDSA-AES128-GCM-SHA256
  - ECDHE-RSA-AES128-GCM-SHA256
  - ECDHE-ECDSA-AES256-GCM-SHA384
  - ECDHE-RSA-AES256-GCM-SHA384
  - ECDHE-ECDSA-CHACHA20-POLY1305
  - ECDHE-RSA-CHACHA20-POLY1305
  - DHE-RSA-AES128-GCM-SHA256
  - DHE-RSA-AES256-GCM-SHA384

# this is just used in the webservers group vars
nginx_conf_client_max_body_size: 80g

nginx_servers:
  - certbot_redirects

# the usegalaxy config and certs are included for emergency web serving when the web VMs are down

nginx_ssl_servers:
  - usegalaxy_staging
  - usegalaxy

nginx_extra_configs:
  - usegalaxy_rewrites.conf

certbot_domains:
  - "{{ inventory_hostname_short }}.galaxyproject.org"
  - usegalaxy.org
  - www.usegalaxy.org


## used by the sysctl task in the galaxy_infrastructure playbook
sysctl_conf:
  - name: net.core.rmem_max
    value: 15990784
  - name: net.core.wmem_max
    value: 15990784

# used by nginx template
galaxy_tusd_port: 1080

tusd_version: v1.10.0

# Gravity config is in galaxyjobservers
