---

## used by: supervisor
galaxywebservers_group_supervisor_configs:
  - galaxy
  - galaxy_impersonate
  - galaxy_group


# TODO: disable 1.0, 1.1
nginx_conf_ssl_protocols:
    - TLSv1
    - TLSv1.1
    - TLSv1.2

# this is just used in the webservers group vars
nginx_conf_client_max_body_size: 20g

nginx_servers:
  - certbot_redirects

nginx_ssl_servers:
  - usegalaxy

nginx_extra_configs:
  - usegalaxy_rewrites.conf

certbot_domains:
  - usegalaxy.org
  - "{{ inventory_hostname_short }}.galaxyproject.org"
  - www.usegalaxy.org


## used by the sysctl task in the galaxy_infrastructure playbook
sysctl_conf:
  - name: net.core.rmem_max
    value: 15990784
  - name: net.core.wmem_max
    value: 15990784
