---

## used by: supervisor
galaxy_handlers:
  - count: 2
  - pool: multi
    count: 1

galaxy_workflow_scheduler_count: 1

galaxyjobservers_group_supervisor_configs:
  - galaxy_dynamic_handler
  - galaxy_workflow_scheduler
  - galaxy_group

galaxyjobservers_group_absent_supervisor_configs:
  - galaxy_handler

## used by: usegalaxy_privileged
usegalaxy_dynamic_job_rules:
  - reserved.py
  - multi_dynamic_walltime.py
  - bridges_select.py
  - nvc_dynamic_memory.py
