---

## used by: uwsgi.ini.j2
galaxy_uwsgi_processes: 4


## used by: supervisor
galaxystagingservers_group_supervisor_configs: []

galaxystagingservers_group_absent_supervisor_configs:
  - galaxy

## used by: galaxyproject.nginx
nginx_conf_http:
  server_names_hash_bucket_size: 128
  gzip: 'on'
  gzip_vary: 'on'
  gzip_proxied: any
  gzip_comp_level: 6
  gzip_buffers: 16 8k
  gzip_http_version: 1.1
  gzip_types: text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript
  client_max_body_size: "{{ nginx_conf_client_max_body_size }}"
  proxy_read_timeout: 600

nginx_conf_ssl_protocols:
  - TLSv1.2

nginx_conf_ssl_ciphers:
  - ECDHE-ECDSA-AES128-GCM-SHA256
  - ECDHE-RSA-AES128-GCM-SHA256
  - ECDHE-ECDSA-AES256-GCM-SHA384
  - ECDHE-RSA-AES256-GCM-SHA384
  - ECDHE-ECDSA-CHACHA20-POLY1305
  - ECDHE-RSA-CHACHA20-POLY1305
  - DHE-RSA-AES128-GCM-SHA256
  - DHE-RSA-AES256-GCM-SHA384

# this is just used in the webservers group vars
nginx_conf_client_max_body_size: 500g

nginx_servers:
  - certbot_redirects

# the usegalaxy config and certs are included for emergency web serving when the web VMs are down

nginx_ssl_servers:
  - usegalaxy_staging
  #- usegalaxy

#nginx_extra_configs:
#  - usegalaxy_rewrites.conf

certbot_domains:
  - "{{ inventory_hostname_short }}.galaxyproject.org"
  - usegalaxy.org
  - www.usegalaxy.org


# used by nginx template
galaxy_tusd_port: 1080

# Gravity config is in galaxyjobservers
