---

# Disable handlers in role, use playbook handlers
galaxy_systemd_mode: null
# Disable gravity config in galaxy.yml, use standalone Gravity config
galaxy_gravity_config_default: null
gravity_config_file: "/etc/galaxy/gravity.d/galaxy_{{ galaxy_instance_codename }}.yml"
gravity_virtualenv_command: /opt/rh/rh-python38/root/usr/bin/python3 -m venv
gravity_venv_dir: "{{ galaxy_root }}/gravity"
gravity_package: "gravity==1.0.6"
galaxy_gravity_command: "{{ gravity_venv_dir }}/bin/galaxyctl"

gravity_config:
  instance_name: "{{ galaxy_instance_codename }}"
  process_manager: systemd
  galaxy_user: "{{ galaxy_user }}"
  galaxy_group: "{{ galaxy_group }}"
  galaxy_root: "{{ galaxy_server_dir }}"
  galaxy_config_file: "{{ galaxy_config_file }}"
  log_dir: "{{ galaxy_log_dir }}"
  virtualenv: "{{ galaxy_venv_dir }}"
  memory_limit: 3
  gunicorn:
    - bind: localhost:8080
      workers: 1
      timeout: 600
      restart_timeout: 600
      preload: true
      #extra_args: --max-requests 50000 --max-requests-jitter 10000
      environment:
        HDF5_USE_FILE_LOCKING: "FALSE"
    - bind: localhost:8081
      workers: 1
      timeout: 600
      restart_timeout: 600
      preload: true
      #extra_args: --max-requests 50000 --max-requests-jitter 10000
      environment:
        HDF5_USE_FILE_LOCKING: "FALSE"
  celery:
    enable: true
    enable_beat: "{{ galaxy_enable_celery_beat }}"
    concurrency: 8
    environment:
      TMPDIR: /corral4/main/celery-scratch
      # TODO: this can be removed once the base OS version of pango is >= 1.44.0
      LD_LIBRARY_PATH: "/cvmfs/{{ galaxy_cvmfs_repo }}/deps/_conda/envs/_galaxy_weasyprint_deps_/lib"
      HDF5_USE_FILE_LOCKING: "FALSE"
  tusd:
    # this is for if we need handlers to serve web during downtimes
    - enable: true
      tusd_path: /usr/local/sbin/tusd
      upload_dir: "{{ galaxy_tus_upload_store }}"
      memory_limit: 2
    - enable: true
      tusd_path: /usr/local/sbin/tusd
      upload_dir: "{{ galaxy_tus_upload_store_job_files }}"
      port: 1081
      hooks_http: /api/job_files/tus_hooks
      memory_limit: 2
  handlers: "{{ gravity_handlers }}"
    # job handlers are and workflow schedulers configured in host_vars
