---

## used by: supervisor
galaxy_handler_count: 3
galaxy_workflow_scheduler_count: 1

supervisord_galaxyjobservers_group_configs:
  - galaxy_handler
  - galaxy_workflow_scheduler
  - galaxy_group


## used by: usegalaxy_privileged
usegalaxy_dynamic_job_rules:
  - reserved.py
  - multi_dynamic_walltime.py
  - bridges_select.py
  - nvc_dynamic_memory.py
