---

## used by: supervisor
galaxywebservers_group_supervisor_configs:
  - galaxy
  - galaxy_impersonate
  - galaxy_group


nginx_conf_ssl_protocols:
  - TLSv1.2

nginx_conf_ssl_ciphers:
  - ECDHE-ECDSA-AES128-GCM-SHA256
  - ECDHE-RSA-AES128-GCM-SHA256
  - ECDHE-ECDSA-AES256-GCM-SHA384
  - ECDHE-RSA-AES256-GCM-SHA384
  - ECDHE-ECDSA-CHACHA20-POLY1305
  - ECDHE-RSA-CHACHA20-POLY1305
  - DHE-RSA-AES128-GCM-SHA256
  - DHE-RSA-AES256-GCM-SHA384

# this is just used in the webservers group vars
nginx_conf_client_max_body_size: 20g

nginx_servers:
  - certbot_redirects

nginx_ssl_servers:
  - usegalaxy

nginx_extra_configs:
  - usegalaxy_rewrites.conf

certbot_domains:
  - usegalaxy.org
  - "{{ inventory_hostname_short }}.galaxyproject.org"
  - www.usegalaxy.org

galaxy_tusd_port: 1080

tusd_instances:
  - name: galaxy-main
    user: g2main
    group: G-803372
    args:
      - -host=localhost
      - -port={{ galaxy_tusd_port }}
      - -upload-dir=/galaxy-repl/test/scratch
      - -hooks-http=https://usegalaxy.org/api/upload/hooks
      - -hooks-http-forward-headers=X-Api-Key,Cookie

## used by the sysctl task in the galaxy_infrastructure playbook
sysctl_conf:
  - name: net.core.rmem_max
    value: 15990784
  - name: net.core.wmem_max
    value: 15990784
