---

webservers_group_directories:
  - path: "{{ certbot_well_known_root }}"
    mode: "0755"

## used by: galaxyproject.nginx
nginx_flavor: galaxy
nginx_default_redirect_uri: https://usegalaxy.org$request_uri
nginx_conf_user: g2main
nginx_conf_group: G-803372
nginx_conf_worker_processes: 8
nginx_enable_default_ipv6: false

## used by: usegalaxy, usegalaxy_static, errdocs_dest var below, not the role directly
nginx_srv: /srv/nginx

nginx_conf_http:
  server_names_hash_bucket_size: 128
  gzip: 'on'
  gzip_vary: 'on'
  gzip_proxied: any
  gzip_comp_level: 6
  gzip_buffers: 16 8k
  gzip_http_version: 1.1
  gzip_types: text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript
  client_max_body_size: "{{ nginx_conf_client_max_body_size }}"
  proxy_read_timeout: 600
  uwsgi_read_timeout: 300

nginx_ssl_role: usegalaxy_eu.certbot
nginx_conf_ssl_certificate: /etc/ssl/certs/fullchain.pem
nginx_conf_ssl_certificate_key: /etc/ssl/private/privkey.pem

certbot_auto_renew_hour: "{{ 23 |random(seed=inventory_hostname)  }}"
certbot_auto_renew_minute: "{{ 59 |random(seed=inventory_hostname)  }}"
certbot_auth_method: --webroot
certbot_install_method: virtualenv
certbot_auto_renew: yes
certbot_auto_renew_user: root
certbot_environment: production
certbot_well_known_root: "{{ nginx_srv }}/_well-known_root"
#certbot_share_key_users:
#  - "{{ nginx_conf_user }}"
certbot_post_renewal: |
    systemctl restart nginx || true
certbot_agree_tos: --agree-tos
