# List GA4GH Tool Registry Services to connect Galaxy with.
# 'id' is used to key API interactions and should be unique, the backend uses 'api_url'
# to build requests. The remaining fields 'label', 'link_url', and 'doc' are used to render
# information in the user interface.

- id: dockstore
  api_url: https://dockstore.org/api
  link_url: https://dockstore.org
  label: Dockstore
  doc: |
    Dockstore is an open platform used by the GA4GH for sharing Docker-based tools and workflows.

- id: workflowhub
  api_url: https://workflowhub.eu
  link_url: https://workflowhub.eu
  label: workflowhub.eu
  doc: |
    WorkflowHub is a registry of scientific workflows.
