---

deploy_env: stage

galaxy_branch: dev
galaxy_changeset_id: UNUSED
galaxy_vcs: git
galaxy_instance_codename: test
galaxy_user: g2test

# the galaxy_group supervisor template assumes this is set
# override in host vars
supervisord_host_configs: []
