---

## these vars are defined in the vaulted (secret) vars file
#
# used by: galaxyprojectdotorg.galaxy (templating job_conf.xml)
#galaxy_job_conf_amqp_url
#
# used by: galaxy_config var
#galaxy_config_database_connection
#galaxy_config_install_database_connection
#galaxy_config_admin_users
#galaxy_config_id_secret
#galaxy_config_biostar_key
#galaxy_config_sentry_dsn
#galaxy_config_amqp_internal_connection


## used by: other vars in this vars file
galaxy_log_dir: "{{ galaxy_root }}/log"

# instance_root and galaxy_root are set in the play
# these are the same on galaxy servers
# on pulsar servers, galaxy_root is a subdirectory of instance_root
#instance_root:
#galaxy_root:


## used by: the play itself
# As of Ansible 2.0, a variable name matching a word used in a with_items loop
# (as in supervisord_group_configs) will be expanded, despite the fact that
# bare word expansion is deprecated. D=
galaxy_system_group: G-803372
# alsu by usegalaxy_admin
galaxy_privileged_user: gxsrc

galaxy_root: /srv/galaxy/{{ galaxy_instance_codename }}
galaxy_server_dir: "/cvmfs/test.galaxyproject.org/galaxy"


## used by: supervisor
galaxy_handler_count: 5
supervisord_group_configs:
  - galaxy
  - galaxy_installer
  - galaxy_datamanager
  - galaxy_reports
  - galaxy_group

# supervisor template
galaxy_installer_venv_dir: "/cvmfs/test.galaxyproject.org/venv"
galaxy_datamanager_venv_dir: "/cvmfs/test.galaxyproject.org/venv"


## used by: galaxyprojectdotorg.nginx
nginx_flavor: galaxy
nginx_default_redirect_uri: https://test.galaxyproject.org$request_uri

nginx_conf_http:
  server_names_hash_bucket_size: 128
  gzip_vary: 'on'
  gzip_proxied: any
  gzip_comp_level: 6
  gzip_buffers: 16 8k
  gzip_http_version: 1.1
  gzip_types: text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript
  client_max_body_size: 10g
  proxy_read_timeout: 600
  uwsgi_read_timeout: 300

nginx_configs:
  - galaxy_test
  - galaxy_main_installer
  - tacc_protected

nginx_conf_user: g2test
nginx_conf_group: G-803372
nginx_conf_worker_processes: 4
nginx_conf_ssl_certificate: "{{ nginx_conf_dir }}/ssl/wildcard_cert.pem"
nginx_conf_ssl_certificate_key: "{{ nginx_conf_dir }}/ssl/wildcard_privatekey.pem"
nginx_enable_default_ipv6: false
nginx_supervisor: true

## used by: usegalaxy, usegalaxy_static
nginx_srv: /srv/nginx

galaxy_instance_hostname: test.galaxyproject.org

usegalaxy_dynamic_job_rules:
  - files/galaxy/{{ galaxy_instance_hostname }}/dynamic_rules/reserved.py
  - files/galaxy/{{ galaxy_instance_hostname }}/dynamic_rules/multi_dynamic_walltime.py
  - files/galaxy/{{ galaxy_instance_hostname }}/dynamic_rules/greenfield_select.py
  - files/galaxy/{{ galaxy_instance_hostname }}/dynamic_rules/nvc_dynamic_memory.py

usegalaxy_nagios_tools:
  - echo_test_handler0
  - echo_test_handler1
  - echo_test_cluster
  - echo_test_stampede
  - echo_test_greenfield


## used by usegalaxy_privileged
# this didn't work...
#galaxy_dynamic_rule_dir: "{{ galaxy_root }}/dynamic_rules"


## used by the sysctl task in the galaxy_infrastructure playbook
sysctl_conf:
  - name: net.core.rmem_max
    value: 15990784
  - name: net.core.wmem_max
    value: 15990784


## used by: usegalaxy_admin
galaxy_log_archive_dir: /galaxy-repl/{{ galaxy_instance_codename }}/backup/log


## used by: galaxyprojectdotorg.tools
galaxy_instance_url: "{{ galaxy_instance_hostname }}"
tool_list_file: files/galaxy/test.galaxyproject.org/tool_list.yaml


## used by: galaxyprojectdotorg.interactive_environments
interactive_environments_install_method: copy
interactive_environments_plugins_local_path: "{{ deploy_env }}/files/interactive_environments/plugins"
interactive_environments_proxy_local_path: "{{ deploy_env }}/files/interactive_environments/proxy"
interactive_environments_plugins_path: "{{ galaxy_root }}/interactive_environments/plugins"
interactive_environments_proxy_path: "{{ galaxy_root }}/interactive_environments/proxy"
interactive_environments_enabled:
  - jupyter
interactive_environments_config_files:
  - ie_name: jupyter
    file: jupyter.ini
    contents:
      docker:
        command: "docker -H tcp://iedocker.galaxyproject.org:2376 --tlsverify {docker_args}"
        galaxy_url: "https://test.galaxyproject.org"
        docker_hostname: "iedocker.galaxyproject.org"
  - ie_name: jupyter
    file: allowed_images.yml
    contents:
      - image: "quay.io/bgruening/docker-jupyter-notebook:16.01.1"
        description: >
          The Jupyter notebook is the next iteration of IPython, allowing
          analysis in many different languages. This image features the Python,
          R, Julia, Haskell, Bash kernels and many scientific analysis stacks for
          each.
interactive_environments_supervisor_conf_dir: "{{ galaxy_root }}/supervisor/etc/supervisord.conf.d"
interactive_environments_nginx_conf_dir: "{{ galaxy_root }}/nginx.conf.d"
interactive_environments_proxy_user: "{{ galaxy_user }}"
interactive_environments_access_log_path: "{{ galaxy_log_dir }}/gie_proxy-access.log"
interactive_environments_error_log_path: "{{ galaxy_log_dir }}/gie_proxy-error.log"


## used by: galaxyprojectdotorg.galaxy
pip_virtualenv_command: "{{ galaxy_root }}/python/bin/virtualenv"

# some things are always local
galaxy_venv_dir: "/cvmfs/test.galaxyproject.org/venv"
galaxy_config_dir: "{{ galaxy_root }}/config"
galaxy_config_file: "{{ galaxy_config_dir }}/galaxy.ini"
galaxy_mutable_config_dir: "{{ galaxy_root }}/var"
galaxy_mutable_data_dir: "{{ galaxy_root }}/var"

galaxy_admin_email_to: galaxy-lab@bx.psu.edu

base_app_main: &BASE_APP_MAIN

  # message box

  #message_box_visible: "True"
  #message_box_content: 'Galaxy will be unavailable between 10:45 AM - 1:30 PM EST (UTC -0500) on Tuesday, December 16th due to <a target="_blank" href="https://portal.tacc.utexas.edu/user-news/-/news/101689">scheduled filesystem maintenance</a>. Running jobs may be interrupted during this period.'
  #message_box_class: warning

  # secrets

  database_connection: "{{ galaxy_config_database_connection }}"
  install_database_connection: "{{ galaxy_config_install_database_connection }}"
  id_secret: "{{ galaxy_config_id_secret }}"
  admin_users: "{{ galaxy_config_admin_users }}"
  biostar_key: "{{ galaxy_config_biostar_key }}"
  sentry_dsn: "{{ galaxy_config_sentry_dsn }}"
  amqp_internal_connection: "{{ galaxy_config_amqp_internal_connection }}"

  # paths

  tool_config_file: "{{ galaxy_config_dir }}/tool_conf.xml,/cvmfs/test.galaxyproject.org/config/shed_tool_conf.xml,{{ galaxy_config_dir }}/nagios_tool_conf.xml"
  tool_dependency_dir: /galaxy/test/deps
  job_working_directory: /galaxy/test/jobdir
  tool_data_path: /galaxy-repl/test/tool_data
  nginx_upload_store: /galaxy-repl/test/upload
  nginx_upload_job_files_store: /galaxy-repl/test/upload_job_files
  ftp_upload_dir: /galaxy/test/ftp
  user_library_import_dir: /galaxy/test/ftp
  library_import_dir: /galaxy-repl/test/import
  galaxy_data_manager_data_path: /galaxy-repl/manageddata/data

  tool_sheds_config_file: "{{ galaxy_config_dir }}/tool_sheds_conf.xml"
  tool_data_table_config_path: "{{ galaxy_config_dir }}/tool_data_table_conf.xml"
  datatypes_config_file: "{{ galaxy_config_dir }}/datatypes_conf.xml"
  object_store_config_file: "{{ galaxy_config_dir }}/object_store_conf.xml"
  job_config_file: "{{ galaxy_config_dir }}/job_conf.xml"
  job_resource_params_file: "{{ galaxy_config_dir }}/job_resource_params_conf.xml"
  data_manager_config_file: "{{ galaxy_config_dir }}/data_manager_conf.xml"
  job_metrics_config_file: "{{ galaxy_config_dir }}/job_metrics_conf.xml"

  migrated_tools_config: "/cvmfs/test.galaxyproject.org/config/migrated_tools_conf.xml"
  shed_tool_data_table_config: "/cvmfs/test.galaxyproject.org/config/shed_tool_data_table_conf.xml"
  integrated_tool_panel_config: "{{ galaxy_mutable_config_dir }}/integrated_tool_panel.xml"
  sanitize_whitelist_file: /galaxy-repl/test/config/sanitize_whitelist.txt

  #environment_setup_file: /galaxy/test/job_env.bash

  builds_file_path: "{{ galaxy_config_dir }}/builds.txt"
  ucsc_build_sites: "{{ galaxy_config_dir }}/ucsc_build_sites.txt"

  # interactive environments
  interactive_environment_plugins_directory: "{{ interactive_environments_plugins_path }}"
  dynamic_proxy_manage: "False"
  dynamic_proxy_session_map: /srv/galaxy/test/var/gie_proxy_session_map.sqlite
  dynamic_proxy_bind_port: 4280
  dynamic_proxy_bind_ip: 0.0.0.0
  dynamic_proxy_debug: "True"
  dynamic_proxy_external_proxy: "True"
  dynamic_proxy_prefix: gie_proxy
  galaxy_infrastructure_url: https://test.galaxyproject.org
  #trust_ipython_notebook_conversion: "True"

  # general stuff

  database_engine_option_pool_size: 10
  database_engine_option_max_overflow: 20
  database_engine_option_server_side_cursors: "True"
  manage_dependency_relationships: "False"
  len_file_path: /galaxy-repl/localdata/chrom
  collect_outputs_from: job_working_directory
  smtp_server: localhost
  error_email_to: galaxy-bugs@bx.psu.edu
  activation_email: "Galaxy Activation <activate@galaxyproject.org>"
  instance_resource_url: "http://wiki.galaxyproject.org/Support"
  blacklist_file: "{{ galaxy_config_dir }}/disposable_email_blacklist.conf"
  registration_warning_message: "Please register only one account. The {{ galaxy_instance_hostname }} service is provided free of charge and has limited computational and data storage resources. <strong>Registration and usage of multiple accounts is tracked and such accounts are subject to termination and data deletion.</strong>"
  user_activation_on: "True"
  activation_grace_period: 6
  inactivity_box_content: "Your account has not been activated yet.  Feel free to browse around and see what's available, but you won't be able to upload data or run jobs until you have verified your email address."
  wiki_url: "http://wiki.galaxyproject.org/"
  terms_url: "https://{{ galaxy_instance_hostname }}/static/terms.html"
  ga_code: "UA-45719423-9"
  static_enabled: "False"
  enable_cloud_launch: "True"
  cloudlaunch_default_ami: ami-a7dbf6ce
  nginx_x_accel_redirect_base: /_x_accel_redirect
  nginx_upload_path: /_upload
  nginx_upload_job_files_path: /_job_files
  log_events: "False"
  log_actions: "False"
  debug: "False"
  use_interactive: "False"
  use_pbkdf2: "False"
  allow_user_deletion: "True"
  allow_user_dataset_purge: "True"
  enable_openid: "True"
  ftp_upload_site: "{{ galaxy_instance_hostname }}"
  enable_quotas: "True"
  track_jobs_in_database: "True"
  retry_metadata_internally: "False"
  retry_job_output_collection: 5
  #cleanup_job: onsuccess
  cleanup_job: never
  biostar_url: "https://biostar.galaxyproject.org"
  biostar_key_name: biostar-login
  biostar_enable_bug_reports: "False"
  allow_user_impersonation: "True"
  max_metadata_value_size: 1000000
  brand: 'Test'
  enable_beta_tool_command_isolation: "True"

  # stats
  statsd_host: "galaxy06.tacc.utexas.edu"
  statsd_port: "8125"
  statsd_prefix: "test"

# galaxy.ini contents
galaxy_config_hash:
  "app:main":
    <<: *BASE_APP_MAIN
    new_file_path: /galaxy/test/scratch

installer_config_hash:
  "server:test_installer":
    threadpool_workers: 5
    port: 9999

  "app:main":
    <<: *BASE_APP_MAIN
    new_file_path: /srv/galaxy/test/var/installer_tmp

datamanager_config_hash:
  "server:test_datamanager":
    threadpool_workers: 5
    port: 9998

  "app:main":
    <<: *BASE_APP_MAIN
    new_file_path: /galaxy-repl/test/data-scratch

# specifies config files to copy from the playbook
galaxy_config_files:
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/tool_data_table_conf.xml
    dest: "{{ galaxy_config['app:main']['tool_data_table_config_path'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/tool_conf.xml
    dest: "{{ galaxy_config_dir }}/tool_conf.xml"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/nagios_tool_conf.xml
    dest: "{{ galaxy_config_dir }}/nagios_tool_conf.xml"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/object_store_conf.xml
    dest: "{{ galaxy_config['app:main']['object_store_config_file'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/data_manager_conf.xml
    dest: "{{ galaxy_config['app:main']['data_manager_config_file'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/tool_sheds_conf.xml
    dest: "{{ galaxy_config['app:main']['tool_sheds_config_file'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/job_metrics_conf.xml
    dest: "{{ galaxy_config['app:main']['job_metrics_config_file'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/job_resource_params_conf.xml
    dest: "{{ galaxy_config['app:main']['job_resource_params_file'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/pulsar_stampede_actions.yml
    dest: "{{ galaxy_config_dir }}/pulsar_stampede_actions.yml"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/pulsar_jetstream.yml
    dest: "{{ galaxy_config_dir }}/pulsar_jetstream.yml"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/pulsar_jetstream_actions.yml
    dest: "{{ galaxy_config_dir }}/pulsar_jetstream_actions.yml"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/builds.txt
    dest: "{{ galaxy_config['app:main']['builds_file_path'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/ucsc_build_sites.txt
    dest: "{{ galaxy_config['app:main']['ucsc_build_sites'] }}"

# specifies config files to template from the playbook
galaxy_config_templates:
  - src: templates/galaxy/{{ galaxy_instance_hostname }}/config/job_conf.xml.j2
    dest: "{{ galaxy_config_dir }}/job_conf.xml"
  - src: templates/galaxy/{{ galaxy_instance_hostname }}/config/datatypes_conf.xml.j2
    dest: "{{ galaxy_config['app:main']['datatypes_config_file'] }}"
  - src: templates/galaxy/{{ galaxy_instance_hostname }}/config/disposable_email_blacklist.conf.j2
    dest: "{{ galaxy_config['app:main']['blacklist_file'] }}"
  - src: templates/galaxy/{{ galaxy_instance_hostname }}/config/reports.ini.j2
    dest: "{{ galaxy_config_dir }}/reports.ini"
  - src: templates/galaxy/{{ galaxy_instance_hostname }}/config/uwsgi.ini.j2
    dest: "{{ galaxy_config_dir }}/uwsgi.ini"
