---

## these vars are defined in the vaulted (secret) vars file
#
# used by: galaxyprojectdotorg.galaxy (templating job_conf.xml)
#galaxy_job_conf_amqp_url
#
# used by: galaxy_config var
#galaxy_config_database_connection
#galaxy_config_install_database_connection
#galaxy_config_admin_users
#galaxy_config_id_secret
#galaxy_config_biostar_key
#galaxy_config_sentry_dsn
#galaxy_config_amqp_internal_connection


## used by: other vars in this vars file
galaxy_log_dir: "{{ galaxy_web_root }}/log"

# instance_root and galaxy_root are set in the play
# these are the same on galaxy servers
# on pulsar servers, galaxy_root is a subdirectory of instance_root
#instance_root: 
#galaxy_root: 


## used by: the play itself
galaxy_user: g2test
galaxy_group: G-803372

galaxy_web_root: /srv/galaxy/{{ galaxy_instance_codename }}
galaxy_web_server_dir: "{{ galaxy_web_root }}/server"
galaxy_web_eggs_path: "{{ galaxy_web_root }}/eggs"
galaxy_handler_root: /galaxy-repl/instances/{{ galaxy_instance_codename }}
galaxy_handler_server_dir: "{{ galaxy_handler_root }}/server"
galaxy_handler_eggs_path: "{{ galaxy_handler_root }}/eggs"


## used by: supervisor
galaxy_instance_codename: test
galaxy_handler_count: 4
supervisord_group_configs:
  - galaxy.conf
  - galaxy_installer.conf
  - galaxy_reports.conf
  - galaxy_group.conf


## used by: usegalaxy, usegalaxy_static
nginx_srv: /srv/nginx

galaxy_instance_hostname: test.galaxyproject.org

usegalaxy_dynamic_job_rules:
  - files/galaxy/{{ galaxy_instance_hostname }}/dynamic_rules/reserved.py
  - files/galaxy/{{ galaxy_instance_hostname }}/dynamic_rules/multi_dynamic_walltime.py
  - files/galaxy/{{ galaxy_instance_hostname }}/dynamic_rules/stampede_select.py
  - files/galaxy/{{ galaxy_instance_hostname }}/dynamic_rules/blacklight_select.py
  - files/galaxy/{{ galaxy_instance_hostname }}/dynamic_rules/single_dynamic_memory.py
  - files/galaxy/{{ galaxy_instance_hostname }}/dynamic_rules/nvc_dynamic_memory.py

usegalaxy_nagios_tools:
  - echo_test_handler0
  - echo_test_handler1
  - echo_test_stampede
  - echo_test_blacklight


## used by: galaxyprojectdotorg.galaxy
pip_virtualenv_command: "{{ galaxy_web_root }}/python/bin/virtualenv"

# some things are always local
galaxy_venv_dir: "{{ galaxy_web_root }}/venv"
galaxy_config_dir: "{{ galaxy_web_root }}/config"
galaxy_config_file: "{{ galaxy_config_dir }}/galaxy.ini"
galaxy_mutable_config_dir: "{{ galaxy_web_root }}/var"
galaxy_mutable_data_dir: "{{ galaxy_web_root }}/var"

galaxy_admin_email_to: galaxy-lab@bx.psu.edu

# galaxy.ini contents
galaxy_config:
  "server:test_installer":
    threadpool_workers: 5
    port: 9999

  uwsgi:
    socket: "127.0.0.1:4001"
    stats: "127.0.0.1:9191"
    processes: 8
    threads: 4
    master: True
    logto: "{{ galaxy_log_dir }}/uwsgi.log"
    # this causes an infinite loop waiting for the touch-logreopen file at uwsgi startup, why?
    #"log-reopen": True
    #"touch-logreopen": "{{ galaxy_log_dir }}/uwsgi.logreopen"
    pythonpath: lib
  "app:main":

    # message box

    #message_box_visible: "True"
    #message_box_content: 'Galaxy will be unavailable between 10:45 AM - 1:30 PM EST (UTC -0500) on Tuesday, December 16th due to <a target="_blank" href="https://portal.tacc.utexas.edu/user-news/-/news/101689">scheduled filesystem maintenance</a>. Running jobs may be interrupted during this period.'
    #message_box_class: warning

    # secrets

    database_connection: "{{ galaxy_config_database_connection }}"
    install_database_connection: "{{ galaxy_config_install_database_connection }}"
    id_secret: "{{ galaxy_config_id_secret }}"
    admin_users: "{{ galaxy_config_admin_users }}"
    biostar_key: "{{ galaxy_config_biostar_key }}"
    sentry_dsn: "{{ galaxy_config_sentry_dsn }}"
    amqp_internal_connection: "{{ galaxy_config_amqp_internal_connection }}"

    # paths

    tool_config_file: "{{ galaxy_config_dir }}/tool_conf.xml,{{ galaxy_mutable_config_dir }}/shed_tool_conf.xml,{{ galaxy_config_dir }}/nagios_tool_conf.xml"
    new_file_path: /galaxy/test/scratch
    tool_dependency_dir: /galaxy/test/deps
    job_working_directory: /galaxy/test/jobdir
    tool_data_path: /galaxy-repl/test/tool_data
    nginx_upload_store: /galaxy-repl/test/upload
    ftp_upload_dir: /galaxy/test/ftp
    user_library_import_dir: /galaxy/test/ftp
    library_import_dir: /galaxy-repl/test/import
    galaxy_data_manager_data_path: /galaxy-repl/manageddata/data

    tool_sheds_config_file: "{{ galaxy_config_dir }}/tool_sheds_conf.xml"
    tool_data_table_config_path: "{{ galaxy_config_dir }}/tool_data_table_conf.xml"
    datatypes_config_file: "{{ galaxy_config_dir }}/datatypes_conf.xml"
    object_store_config_file: "{{ galaxy_config_dir }}/object_store_conf.xml"
    job_config_file: "{{ galaxy_config_dir }}/job_conf.xml"
    job_resource_params_file: "{{ galaxy_config_dir }}/job_resource_params_conf.xml"
    data_manager_config_file: "{{ galaxy_config_dir }}/data_manager_conf.xml"
    job_metrics_config_file: "{{ galaxy_config_dir }}/job_metrics_conf.xml"

    migrated_tools_config: "{{ galaxy_mutable_config_dir }}/migrated_tools_conf.xml"
    shed_tool_data_table_config: "{{ galaxy_mutable_config_dir }}/shed_tool_data_table_conf.xml"

    environment_setup_file: /galaxy/test/job_env.bash

    builds_file_path: "{{ galaxy_config_dir }}/builds.txt"
    ucsc_build_sites: "{{ galaxy_config_dir }}/ucsc_build_sites.txt"

    # general stuff

    database_engine_option_pool_size: 10
    database_engine_option_max_overflow: 20
    database_engine_option_server_side_cursors: "True"
    manage_dependency_relationships: "False"
    len_file_path: /galaxy-repl/localdata/chrom
    collect_outputs_from: job_working_directory
    smtp_server: localhost
    error_email_to: galaxy-bugs@bx.psu.edu
    activation_email: "Galaxy Activation <activate@galaxyproject.org>"
    instance_resource_url: "http://wiki.galaxyproject.org/Support"
    blacklist_file: "{{ galaxy_config_dir }}/disposable_email_blacklist.conf"
    registration_warning_message: "Please register only one account. The {{ galaxy_instance_hostname }} service is provided free of charge and has limited computational and data storage resources. <strong>Registration and usage of multiple accounts is tracked and such accounts are subject to termination and data deletion.</strong>"
    user_activation_on: "True"
    activation_grace_period: 6
    inactivity_box_content: "Your account has not been activated yet.  Feel free to browse around and see what's available, but you won't be able to upload data or run jobs until you have verified your email address."
    wiki_url: "http://wiki.galaxyproject.org/"
    terms_url: "https://{{ galaxy_instance_hostname }}/static/terms.html"
    ga_code: "UA-45719423-9"
    static_enabled: "False"
    enable_cloud_launch: "True"
    cloudlaunch_default_ami: ami-a7dbf6ce
    nginx_x_accel_redirect_base: /_x_accel_redirect
    nginx_upload_path: /_upload
    log_events: "False"
    log_actions: "False"
    debug: "False"
    use_interactive: "False"
    use_pbkdf2: "False"
    allow_user_deletion: "True"
    allow_user_dataset_purge: "True"
    enable_openid: "True"
    ftp_upload_site: "{{ galaxy_instance_hostname }}"
    enable_quotas: "True"
    track_jobs_in_database: "True"
    retry_metadata_internally: "False"
    retry_job_output_collection: 5
    cleanup_job: never
    biostar_url: "https://biostar.galaxyproject.org"
    biostar_key_name: biostar-login
    biostar_enable_bug_reports: "False"
    allow_user_impersonation: "True"
    ga_code: "UA-45719423-9"

# specifies config files to copy from the playbook
galaxy_config_files:
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/tool_data_table_conf.xml
    dest: "{{ galaxy_config['app:main']['tool_data_table_config_path'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/tool_conf.xml
    dest: "{{ galaxy_config_dir }}/tool_conf.xml"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/nagios_tool_conf.xml
    dest: "{{ galaxy_config_dir }}/nagios_tool_conf.xml"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/object_store_conf.xml
    dest: "{{ galaxy_config['app:main']['object_store_config_file'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/data_manager_conf.xml
    dest: "{{ galaxy_config['app:main']['data_manager_config_file'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/tool_sheds_conf.xml
    dest: "{{ galaxy_config['app:main']['tool_sheds_config_file'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/job_metrics_conf.xml
    dest: "{{ galaxy_config['app:main']['job_metrics_config_file'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/job_resource_params_conf.xml
    dest: "{{ galaxy_config['app:main']['job_resource_params_file'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/pulsar_stampede_actions.yml
    dest: "{{ galaxy_config_dir }}/pulsar_stampede_actions.yml"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/builds.txt
    dest: "{{ galaxy_config['app:main']['builds_file_path'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/ucsc_build_sites.txt
    dest: "{{ galaxy_config['app:main']['ucsc_build_sites'] }}"

# specifies config files to template from the playbook
galaxy_config_templates:
  - src: templates/galaxy/{{ galaxy_instance_hostname }}/config/job_conf.xml.j2
    dest: "{{ galaxy_config_dir }}/job_conf.xml"
  - src: templates/galaxy/{{ galaxy_instance_hostname }}/config/datatypes_conf.xml.j2
    dest: "{{ galaxy_config['app:main']['datatypes_config_file'] }}"
  - src: templates/galaxy/{{ galaxy_instance_hostname }}/config/disposable_email_blacklist.conf.j2
    dest: "{{ galaxy_config['app:main']['blacklist_file'] }}"
  - src: templates/galaxy/{{ galaxy_instance_hostname }}/config/reports.ini.j2
    dest: "{{ galaxy_config_dir }}/reports.ini"
