---

## these vars are defined in the vaulted (secret) vars file
#
# used by: galaxyprojectdotorg.galaxy (templating job_conf.xml)
#galaxy_job_conf_amqp_url
#
# used by: galaxy_config var
#galaxy_config_database_connection
#galaxy_config_install_database_connection
#galaxy_config_admin_users
#galaxy_config_id_secret
#galaxy_config_biostar_key
#galaxy_config_sentry_dsn
#galaxy_config_amqp_internal_connection


## used by: other vars in this vars file
galaxy_home: /home/{{ galaxy_user }}
galaxy_log_dir: "{{ galaxy_home }}/log"


## used by: the play itself
deploy_env: stage
hg_virtualenv: /home/g2test/hgenv

galaxy_user: g2test
galaxy_handler_venv_dir: /galaxy-repl/test/venv
galaxy_handler_server_dir: /galaxy-repl/test/server
galaxy_handler_config_file: /galaxy-repl/test/config/galaxy.ini
galaxy_handler_object_store_config_file: /galaxy-repl/test/config/object_store_conf.xml


## used by: usegalaxy, usegalaxy_static
nginx_srv: /srv/nginx

galaxy_instance_hostname: test.galaxyproject.org

usegalaxy_dynamic_job_rules:
  - files/galaxy/{{ galaxy_instance_hostname }}/dynamic_rules/reserved.py
  - files/galaxy/{{ galaxy_instance_hostname }}/dynamic_rules/roundup_multi_walltime.py


## used by: galaxyprojectdotorg.galaxy
hg_executable: "{{ hg_virtualenv }}/bin/hg"
galaxy_venv_dir: "{{ galaxy_home }}/venv"
galaxy_server_dir: "{{ galaxy_home }}/server"
galaxy_config_dir: "{{ galaxy_home }}/config"
galaxy_mutable_config_dir: "{{ galaxy_home }}/var"

galaxy_config_file: "{{ galaxy_config_dir }}/galaxy.ini"

galaxy_repo: https://bitbucket.org/galaxy/galaxy-central/
galaxy_changeset_id: e5e05b2b242a99ab7a1c2748057db1f71ebd70ae

galaxy_admin_email_to: galaxy-lab@bx.psu.edu

# galaxy.ini contents
galaxy_config:
  "server:test_handler0":
    threadpool_workers: 5
    port: 9880
  "server:test_handler1":
    threadpool_workers: 5
    port: 9881
  "server:test_handler2":
    threadpool_workers: 5
    port: 9882
  "server:test_handler3":
    threadpool_workers: 5
    port: 9883
  uwsgi:
    socket: "127.0.0.1:4001"
    stats: "127.0.0.1:9191"
    processes: 8
    threads: 4
    master: True
    logto: "{{ galaxy_log_dir }}/uwsgi.log"
    "log-reopen": True
    "touch-logreopen": "{{ galaxy_log_dir }}/uwsgi.logreopen"
    pythonpath: lib
  "app:main":

    # secrets

    database_connection: "{{ galaxy_config_database_connection }}"
    install_database_connection: "{{ galaxy_config_install_database_connection }}"
    id_secret: "{{ galaxy_config_id_secret }}"
    admin_users: "{{ galaxy_config_admin_users }}"
    biostar_key: "{{ galaxy_config_biostar_key }}"
    sentry_dsn: "{{ galaxy_config_sentry_dsn }}"
    amqp_internal_connection: "{{ galaxy_config_amqp_internal_connection }}"

    # paths

    tool_config_file: "{{ galaxy_config_dir }}/tool_conf.xml,{{ galaxy_mutable_config_dir }}/shed_tool_conf.xml,{{ galaxy_config_dir }}/nagios_tool_conf.xml"
    new_file_path: /galaxy/test/scratch
    tool_dependency_dir: /galaxy/test/deps
    job_working_directory: /galaxy/test/jobdir
    tool_data_path: /galaxy-repl/test/tool_data
    nginx_upload_store: /galaxy-repl/test/upload
    ftp_upload_dir: /galaxy/test/ftp
    library_import_dir: /galaxy-repl/test/import
    galaxy_data_manager_data_path: /galaxy-repl/manageddata/data

    template_cache_path: "{{ galaxy_mutable_config_dir }}/compiled_templates"

    tool_sheds_config_file: "{{ galaxy_config_dir }}/tool_sheds_conf.xml"
    tool_data_table_config_path: "{{ galaxy_config_dir }}/tool_data_table_conf.xml"
    datatypes_config_file: "{{ galaxy_config_dir }}/datatypes_conf.xml"
    object_store_config_file: "{{ galaxy_config_dir }}/object_store_conf.xml"
    job_config_file: "{{ galaxy_config_dir }}/job_conf.xml"
    job_resource_params_file: "{{ galaxy_config_dir }}/job_resource_params_conf.xml"
    data_manager_config_file: "{{ galaxy_config_dir }}/data_manager_conf.xml"
    job_metrics_config_file: "{{ galaxy_config_dir }}/job_metrics_conf.xml"
    # we use this unmodified
    openid_config_file: "{{ galaxy_server_dir }}/openid_conf.xml.sample"

    migrated_tools_config: "{{ galaxy_mutable_config_dir }}/migrated_tools_conf.xml"
    shed_tool_data_table_config: "{{ galaxy_mutable_config_dir }}/shed_tool_data_table_conf.xml"

    environment_setup_file: /galaxy/test/job_env.bash

    builds_file_path: "{{ galaxy_config_dir }}/builds.txt"

    # general stuff

    database_engine_option_pool_size: 10
    database_engine_option_max_overflow: 20
    database_engine_option_server_side_cursors: "True"
    manage_dependency_relationships: "False"
    len_file_path: /galaxy-repl/localdata/chrom
    collect_outputs_from: job_working_directory
    smtp_server: localhost
    error_email_to: galaxy-bugs@bx.psu.edu
    activation_email: "Galaxy Activation <activate@galaxyproject.org>"
    instance_resource_url: "http://wiki.galaxyproject.org/Support"
    blacklist_file: config/disposable_email_blacklist.conf
    registration_warning_message: "Please register only one account. The {{ galaxy_instance_hostname }} service is provided free of charge and has limited computational and data storage resources. <strong>Registration and usage of multiple accounts is tracked and such accounts are subject to termination and data deletion.</strong>"
    user_activation_on: "True"
    activation_grace_period: 6
    inactivity_box_content: "Your account has not been activated yet.  Feel free to browse around and see what's available, but you won't be able to upload data or run jobs until you have verified your email address."
    wiki_url: "http://wiki.galaxyproject.org/"
    terms_url: "https://{{ galaxy_instance_hostname }}/static/terms.html"
    static_enabled: "False"
    enable_cloud_launch: "True"
    cloudlaunch_default_ami: ami-a7dbf6ce
    nginx_x_accel_redirect_base: /_x_accel_redirect
    nginx_upload_path: /_upload
    log_events: "False"
    log_actions: "False"
    debug: "False"
    use_interactive: "False"
    use_pbkdf2: "False"
    allow_user_deletion: "True"
    allow_user_dataset_purge: "True"
    enable_openid: "True"
    ftp_upload_site: "{{ galaxy_instance_hostname }}"
    enable_quotas: "True"
    track_jobs_in_database: "True"
    retry_metadata_internally: "False"
    retry_job_output_collection: 5
    cleanup_job: onsuccess
    biostar_url: "https://biostar.galaxyproject.org"
    biostar_key_name: biostar-login
    biostar_enable_bug_reports: "False"
    allow_user_impersonation: "True"

# specifies config files to copy from the playbook
galaxy_config_files:
  - name: files/galaxy/{{ galaxy_instance_hostname }}/config/tool_data_table_conf.xml
    dest: "{{ galaxy_config['app:main']['tool_data_table_config_path'] }}"
  - name: files/galaxy/{{ galaxy_instance_hostname }}/config/tool_conf.xml
    dest: "{{ galaxy_config_dir }}/tool_conf.xml"
  - name: files/galaxy/{{ galaxy_instance_hostname }}/config/nagios_tool_conf.xml
    dest: "{{ galaxy_config_dir }}/nagios_tool_conf.xml"
  - name: files/galaxy/{{ galaxy_instance_hostname }}/config/object_store_conf.xml
    dest: "{{ galaxy_config['app:main']['object_store_config_file'] }}"
  - name: files/galaxy/{{ galaxy_instance_hostname }}/config/data_manager_conf.xml
    dest: "{{ galaxy_config['app:main']['data_manager_config_file'] }}"
  - name: files/galaxy/{{ galaxy_instance_hostname }}/config/tool_sheds_conf.xml
    dest: "{{ galaxy_config['app:main']['tool_sheds_config_file'] }}"
  - name: files/galaxy/{{ galaxy_instance_hostname }}/config/job_metrics_conf.xml
    dest: "{{ galaxy_config['app:main']['job_metrics_config_file'] }}"
  - name: files/galaxy/{{ galaxy_instance_hostname }}/config/job_resource_params_conf.xml
    dest: "{{ galaxy_config['app:main']['job_resource_params_file'] }}"
  - name: files/galaxy/{{ galaxy_instance_hostname }}/config/lwr_stampede_actions.json
    dest: "{{ galaxy_config_dir }}/lwr_stampede_actions.json"
  - name: files/galaxy/{{ galaxy_instance_hostname }}/config/builds.txt
    dest: "{{ galaxy_config['app:main']['builds_file_path'] }}"

# specifies config files to template from the playbook
galaxy_config_templates:
  - name: templates/galaxy/{{ galaxy_instance_hostname }}/config/job_conf.xml.j2
    dest: "{{ galaxy_config_dir }}/job_conf.xml"
  - name: templates/galaxy/{{ galaxy_instance_hostname }}/config/datatypes_conf.xml.j2
    dest: "{{ galaxy_config['app:main']['datatypes_config_file'] }}"
