---

## these vars are defined in the vaulted (secret) vars file
#
# used by: galaxyprojectdotorg.pulsar (templating server.ini)
#lwr_conf_message_queue_url


## used by: other vars in this vars file
instance_root: "{{ shared_root }}/test"
pulsar_root: "{{ instance_root }}/pulsar"
galaxy_root: "{{ instance_root }}/galaxy"
galaxy_instance_hostname: test.galaxyproject.org


## used by: the play itself
galaxy_user: xcgalaxy
hg_virtualenv: "{{ instance_root }}/hgvenv"
pip_virtualenv_command: "{{ instance_root }}/python/bin/virtualenv"


## used by: galaxyprojectdotorg.pulsar
hg_executable: "{{ hg_virtualenv }}/bin/hg"
pulsar_pip_install: true
pulsar_changeset_id: 075226360ce0e7b7de8a967ecfa8b0ad145093aa
pulsar_venv_dir: "{{ pulsar_root }}/venv"
# Need to update the server.ini template so this is unnecessary
pulsar_server_dir: /does/not/matter
pulsar_config_dir: "{{ pulsar_root }}/config"

pulsar_optional_dependencies:
  - pyOpenSSL
  - pycurl==7.19.3.1 # https://github.com/pycurl/pycurl/issues/201
  - uwsgi
  - drmaa
  - kombu
  - requests
  - poster
  - psutil


## used by: galaxyprojectdotorg.galaxy
galaxy_server_dir: "{{ galaxy_root }}/server"
galaxy_config_dir: "{{ galaxy_root }}/config"
galaxy_venv_dir: "{{ galaxy_root }}/venv"
galaxy_config_file: "{{ galaxy_config_dir }}/galaxy.ini"

galaxy_config_files:
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/ucsc_build_sites.txt
    dest: "{{ galaxy_config_dir }}/ucsc_build_sites.txt"


galaxy_config_templates:
  - src: templates/galaxy/{{ galaxy_instance_hostname }}/config/datatypes_conf.xml.j2
    dest: "{{ galaxy_config_dir }}/datatypes_conf.xml"
