---

# variables in vault.yml
postgresql_objects_users: "{{ vault_postgresql_objects_users }}"
postgresql_objects_groups: "{{ vault_postgresql_objects_groups }}"
postgresql_objects_databases: "{{ vault_postgresql_objects_databases }}"
postgresql_objects_privileges: "{{ vault_postgresql_objects_privileges }}"
