---
# Admin tasks requiring root

# rotate conf/script are copied in usegalaxy_privileged role

- name: Schedule archival of log files
  cron: name="Galaxy Log Archival"
    cron_file="ansible_galaxy_logarchive_{{ galaxy_instance_codename }}"
    user="{{ galaxy_user }}"
    hour="2" minute="10"
    job="{{ galaxy_root }}/bin/archive_logs.sh"
