---

## these vars are defined in the vaulted (secret) vars file
#
# used by: galaxyprojectdotorg.pulsar (templating server.ini)
#lwr_conf_message_queue_url


## used by: other vars in this vars file
instance_root: "{{ shared_root }}/main"
pulsar_root: "{{ instance_root }}/pulsar"
galaxy_root: "{{ instance_root }}/galaxy"
galaxy_instance_hostname: usegalaxy.org


## used by: galaxyprojectdotorg.pulsar
pulsar_pip_install: true
pulsar_changeset_id: 71b55968f4d162b9a0308fdf3837cb1d6031c8e9
pulsar_venv_dir: "{{ pulsar_root }}/venv"
pulsar_config_dir: "{{ pulsar_root }}/config"


## used by: galaxyprojectdotorg.galaxy
galaxy_server_dir: "{{ galaxy_root }}/server"
galaxy_config_dir: "{{ galaxy_root }}/config"
galaxy_venv_dir: "{{ galaxy_root }}/venv"
galaxy_config_file: "{{ galaxy_config_dir }}/galaxy.ini"

galaxy_config_files:
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/ucsc_build_sites.txt
    dest: "{{ galaxy_config_dir }}/ucsc_build_sites.txt"

galaxy_config_templates:
  - src: templates/galaxy/{{ galaxy_instance_hostname }}/config/datatypes_conf.xml.j2
    dest: "{{ galaxy_config_dir }}/datatypes_conf.xml"
