---

postgresql_objects_users:
  - name: shed
  - name: nate

postgresql_objects_groups:
  - name: galaxy_team
    users:
      - name: nate

postgresql_objects_databases:
  - name: galaxy_toolshed
    owner: shed

postgresql_objects_privileges:
  - database: galaxy_toolshed
    objs: ALL_IN_SCHEMA
    roles: galaxy_team
    privs: SELECT
  - database: galaxy_toolshed
    objs: ALL_IN_SCHEMA
    roles: shed
    privs: ALL
  - database: galaxy_toolshed
    objs: ALL_IN_SCHEMA
    roles: shed
    privs: ALL
    type: sequence
